### ISSUE TITLE
Bug - Salvar space meta

### ISSUE THREAD

**Issue by vicmagpac** [FeliciLab/mapadasaude#100]

**Comment by victorMagalhaesPacheco** [comment]
![Uploading Captura de tela de 2020-12-22 14-58-34.png…]()

**Comment by vicmagpac** [comment]
![Captura de tela de 2020-12-22 14-58-34](https://user-images.githubusercontent.com/3487411/102918793-5c404180-4466-11eb-8645-2b4821bd0f1b.png)

**Comment by vicmagpac** [comment]
Resolvido com sucesso.
