### ISSUE TITLE
Após logado, no menu de agentes, ao clicar em [Editar] um agente, dá o erro

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#107]
![Captura de tela de 2020-12-29 08-11-53](https://user-images.githubusercontent.com/57232674/103280394-124be400-49af-11eb-96e0-d4c1a513d049.png)

**Comment by Junior-Shyko** [comment]
Fiz alguns testes em outros agentes e não apresentou erros, mas somente no agente do id 5, esse erro apresenta. 
Fiz um conferência no erro e o erro está procurando um espaço que não existe mais, como mostra na imagem.

![erro](https://user-images.githubusercontent.com/7341117/103925302-13d78380-50f6-11eb-8fe0-c46feede36cd.png)
