### ISSUE TITLE
Mesmo com um evento cadastrado, não aparece na lista

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#108]
![Captura de tela de 2020-12-29 08-41-03](https://user-images.githubusercontent.com/57232674/103281534-c2225100-49b1-11eb-8cab-94f60211eaa4.png)

Evento cadastrado:
![Captura de tela de 2020-12-29 08-42-38](https://user-images.githubusercontent.com/57232674/103281553-d5352100-49b1-11eb-8984-478e30c35b2f.png)

**Comment by Junior-Shyko** [comment]
Iniciado.

**Comment by Junior-Shyko** [comment]
Normalizado no https://mapadasaude.dev.org.br/
O problema acontece quando o espaço que será o evento não está com a localização no mapa. Por isso todo o espaço tem que constar no mapa.

![Captura de tela de 2021-01-07 15-57-31](https://user-images.githubusercontent.com/7341117/103932761-155a7900-5101-11eb-8753-09125f422a6c.png)
