### ISSUE TITLE
Adicionar serviço do Facebook para acessar o Mapas

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#111]
### Objetivo
**Como** usuário
**Quando** queira acessar o Mapas usando o seu cadastro no Facebook
**Então** deve existir a opção de login

### Escopo
O usuário deve poder se cadastrar como agente do Mapas usando seu cadastro pessoal no Facebook.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x] API do Facebook criada
- [x] Serviço de login adicionado

### Observações
Este card se liga ao card #142 e https://github.com/EscolaDeSaudePublica/IdentidadeUnicaDeSaude/issues/43

**Comment by vicmagpac** [comment]
@rmadev-master Essa configuração fica dentro do keycloak, bastando adicionar as contas com os tokens para o Google e Facebook com identity provider.

**Comment by Junior-Shyko** [comment]
> @rmadev-master Essa configuração fica dentro do keycloak, bastando adicionar as contas com os tokens para o Google e Facebook com identity provider.

Além dessa forma, tem o plugin MultipleLocalAuth 
https://github.com/mapasculturais/plugin-MultipleLocalAuth
