### ISSUE TITLE
Cadastro do agente: Adicionar outros municípios dos estados brasileiros

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#112]

**Comment by Junior-Shyko** [comment]
Iniciado! 
A princípio usarei a API do IBGE para trazer os municípios de acordo com o estado.
https://servicodados.ibge.gov.br/api/docs/localidades

**Comment by uira** [comment]
@Junior-Shyko vai ter cache, né?

deus-nos-livre uma requisição de api a cada preenchimento de perfil

**Comment by Junior-Shyko** [comment]
_Em processo_

![Captura de tela de 2021-01-07 12-30-39](https://user-images.githubusercontent.com/7341117/103911344-a96a1780-50e4-11eb-81aa-21ac2d4a46d8.png)

Seleções e endereço com CEP, funciona normalmente, mas precisa melhorar e jogar as informações no mapa.

**Comment by Junior-Shyko** [comment]
Atualização: Retirado preenchimento das opções pelo angular e usado o padrão do mapas com o plugin Jquery x-editable
![Captura de tela de 2021-01-08 14-59-29](https://user-images.githubusercontent.com/7341117/104048904-c70dae80-51c2-11eb-85b1-fa49469461ca.png)

**Comment by Junior-Shyko** [comment]
Desenvolvido e até criado um plugin nesse [link](https://github.com/EscolaDeSaudePublica/pluginsDoMapa).
Passado nos testes local e colocado em homologação para testes online.

**Comment by Junior-Shyko** [comment]
Validado em produção.
