### ISSUE TITLE
Informar ao usuário quando este já tiver cadastro em qualquer outra ferramenta integrada com o Mapas

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#116]
### Objetivo
Na página de login do ID Saúde, Mapa da saúde, o usuário ao realizar o cadastro caso já possua e-mail cadastrado no ID Saúde, então deverá receber uma mensagem informando que o e-mail já está cadastrado.

### Escopo
Informar seguinte mensagem tipo Toast ao usuário, caso este já possua e-mail cadastrado junto ao ID saúde: **E-mail já cadastrado ao ID Saúde, utilizar mesmo usuário e senha.**

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
 - [ ] Informar mensagem ao usuário com e-mail já cadastrado: **E-mail já cadastrado ao ID Saúde, utilizar mesmo usuário e senha?**

### Observações

Clarisse Castro: "quando a pessoa já tiver o email cadastrado no ID Saúde, que foi meu caso, colocar uma msg amigável pra usuária avisando isso, qndo ela for tentar se cadastrar no Mapa, pq a senha vai ser a mesma (e aí vale pensar na experiência de quem esquece a senha)."

**Comment by Junior-Shyko** [comment]
Demanda para [Id Saúde](https://github.com/EscolaDeSaudePublica/IdentidadeUnicaDeSaude)
