### ISSUE TITLE
Equilibrar identidade visual para os sistemas integrados, incluindo o Mapas

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#117]
### Objetivo
**Como** publico interno e externo
**Quando** acessar qualquer sistema do ecosistema FeliciLab, incluindo o Mapas
**Então** o ambiente acessado deverá seguir um padrão único de usabilidade

### Escopo
Quando qualquer pessoa, sendo publico interno ou externo, acessar qualquer sistema disponibilizado no ecosistema do FeliciLab, incluindo o Mapas, deverá observar o mesmo padrão de usabilidade (layout, disposição de componentes, modelos de funcionalidades, relatórios, etc.) em qualquer serviço.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [ ] Mapas, seguindo o padrão de usabilidade já homologado pelo NIT/FeliciLab.

### Observações
**Origem da demanda - mensagem do agente de testes (Clarisse Castro):** "_quando a pessoa for lançada para a tela azul, de novo cadastro, fiquei pensando que podia ser a mesma identidade visual já usada no ID Saúde, afinal estamos tratando do mesmo sistema né?_"

**Comment by RaniGub** [comment]
O Design System está no horizonte das Iniciativas. Quando concluído, afetará todas nossas soluções.
