### ISSUE TITLE
Selos (https://mapadasaude.dev.org.br/): exibir os selos que o agente possui

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#121]

**Comment by Junior-Shyko** [comment]
Já está definido o nome dos selos?
Alguma regra para determinar o selo para o agente ou todos terão o mesmo selo?
Precisamos dessas informações na descrição da Issue.

**Comment by uira** [comment]
@Junior-Shyko Podemos fazer uma chamada sobre isso. 

Entendo que muitas dessas regras não estão definidas a nível de aplicação, e que tem um lado bom de continuar assim, mas precisa estruturar melhor as interfaces e funcionalidades, pra deixar claras as respostas pra essas perguntas.

**Comment by uira** [comment]
@uira

**Comment by Junior-Shyko** [comment]
No servidor de homologação está dando o seguinte erro que eu já estou investigando para correção.
![Captura de tela de 2021-01-12 16-46-43](https://user-images.githubusercontent.com/7341117/104364805-e0ca3100-54f5-11eb-8892-bf8b33643281.png)

**Comment by Junior-Shyko** [comment]
Erro era somente o ID da sequencia que estava errado. 
Corrigido e testado aplicando um selo no usuário GTCESP.
![Captura de tela de 2021-01-12 17-14-07](https://user-images.githubusercontent.com/7341117/104367605-d27e1400-54f9-11eb-9c44-e50369dd8af3.png)
