### ISSUE TITLE
Adicionar opções de compartilhamento no Facebook

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#122]
### Objetivo
**Como** usuário
**Quando** queira compartilhar algo do Mapas no Facebook
**Então** deve existir as opções de compartilhamento

### Escopo
O agente logado deverá ter a opção de divulgar informações disponibilizadas no Mapas (eventos, editais, espaços, etc.) no Facebook.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x] Compartilhamento adicionado

### Observações
Este card se liga ao card #142 .

**Comment by Junior-Shyko** [comment]
Tem esse recurso de compartilhar o conteúdo no instagram??? Eu ainda não havia tido atenção para isso, mas vou conferir a documentação.

- [ ] Compartilhar no facebook

**Comment by Junior-Shyko** [comment]
O botão está criado para fins de demostração, mais precisa criar um app dentro do facebook para gerar o código e colocar no script do botão. 
Documentação do Facebook: https://developers.facebook.com/docs/plugins/share-button/

![Captura de tela de 2021-01-27 12-50-02](https://user-images.githubusercontent.com/7341117/106016435-3aa62b80-609e-11eb-86d5-ae6c33b06e6c.png)

**Comment by rmadev-master** [comment]
Validação: Aguardando resoluções.

**Comment by Junior-Shyko** [comment]
Compartilhamento já está em homologação e produção sem métricas.
