### ISSUE TITLE
Adicionar função para o agente modificar sua senha

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#123]
Ou o agente troca sua senha em uma função dentro do mapas, ou tenha um link para que ele faça a alteração.

**Comment by rafaelmassuncao** [comment]
Entrar em contato com a equipe do idSaude para resolver o problema (bug) de troca de e-mail.

**Comment by Junior-Shyko** [comment]
Adicionado link para alterar a senha no painel do keycloak e outro para esqueci a senha.

**Comment by rafaelmassuncao** [comment]
Iniciando validação.

**Comment by rafaelmassuncao** [comment]
- [x] Abrir a função em outra aba ou em um modal, para que evite de sair da página do Mapas, o que pode ser complicado para o usuário final.

**Validação concluída.**

**Comment by Junior-Shyko** [comment]
> * [x]  Abrir a função em outra aba ou em um modal, para que evite de sair da página do Mapas, o que pode ser complicado para o usuário final.
> 
> **Validação concluída.**

Done!
