### ISSUE TITLE
Acessar painel de controle quando o usuário tem mais de 10000 espaços vinculados

### ISSUE THREAD

**Issue by vicmagpac** [FeliciLab/mapadasaude#124]
### Objetivo
**Como** responsável por vários espaços  
**Quero** realizar o login na plataforma através do id saúde  
**Para** gerenciar os espaços e agentes

### Escopo
Atualmente a aplicação, configuração do servidor da erro no memory limit da aplicação ao carregar mais de 10000 espaços vinculados a conta

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x] Realizar atualização de upgrade de memoria no php.ini
- [ ] Adicionar no container a configuração do nginx

### Observações
No momento não é prioridade à conclusão desta atividade.

**Comment by vicmagpac** [comment]
A atualização de upgrade de memoria no php.ini foi realizada, entretanto falta adicionar no container a configuração do nginx 

proxy_connect_timeout 6000;  
proxy_send_timeout 6000
proxy_read_timeout 6000  
send_timeout 6000  

default.conf

**Comment by vicmagpac** [comment]
> A atualização de upgrade de memoria no php.ini foi realizada, entretanto falta adicionar no container a configuração do nginx
> 
> proxy_connect_timeout 6000;
> proxy_send_timeout 6000
> proxy_read_timeout 6000
> send_timeout 6000
> 
> default.conf

Não é prioridade, mas para o usuário que tem mais de 10000 espaços ou agentes será necessário realizar configuração.

**Comment by luannaalves** [comment]
Já implementado.
