### ISSUE TITLE
Taxonomias: adicionar CRUDs de manipulação (01/02/2021)

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#127]
Taxonomias, categorias profissionais, especialidades, graus de escolaridade, etc.

**Comment by Junior-Shyko** [comment]
Desenvolvido a leitura dos registros e o cadastro.
Faltando:

- [x]  Editar
- [x]  Excluir

**Comment by Junior-Shyko** [comment]
> Desenvolvido a leitura dos registros e o cadastro.
> Faltando:
> 
> * [x]   Editar
> * [x]   Excluir

Finalizado de Agentes, falta da Instituição

**Comment by Junior-Shyko** [comment]
Desenvolvido a leitura dos registros e o cadastro para as **instituições**
Faltando:

- [x]  Editar
- [x]  Excluir

**Comment by Junior-Shyko** [comment]
Desenvolvido a leitura dos registros e o cadastro para os **projetos**
Faltando:

 

- [x] Editar

- [x] Excluir

**Comment by Junior-Shyko** [comment]
Desenvolvido a leitura dos registros e o cadastro para as **oportunidades**
Faltando:

 

- [x]  Editar

- [x] Excluir

**Comment by Junior-Shyko** [comment]
Desenvolvido a leitura dos registros e o cadastro para as **áreas de atuações**.
Faltando:

- [x]  Editar

- [x]  Excluir

**Comment by rafaelmassuncao** [comment]
Este card está conectado ao card #134 .
As ações deste card, foram **validadas**.

**Comment by rafaelmassuncao** [comment]
Aguardar conclusão do card #134 .
