### ISSUE TITLE
Taxonomias: quando houver um registro vinculado, não deve permitir a exclusão

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#134]
1. Informar: "Exclusão não permitida! Já existem dados vinculados ao registro."
2. Ordenar os registros por ordem alfabética.

**Comment by rafaelmassuncao** [comment]
Iniciando validação.

**Comment by rafaelmassuncao** [comment]
**Observações:**

- [x]  1. Exibir campos em **ordem alfabética**, pela coluna "Nome", em Taxonomias (todas).
- [x]  2. Ao lado do botão [Cadastrar], adicionar o botão [Fechar], direcionando o usuário para o Painel.
- [x]  3. Após cadastrar ou editar algum registro nas taxonomias, limpar os campos "Nome:" e "Descrição".
- [x]  4. Ao editar o nome, permitir editar também a "descrição" da taxonomia.
- [x]  5. Exibir no grid, entre as colunas "Nome" e "Ação", o conteúdo da "descrição" da Taxonomia.
- [x]  6 . Reordenar a ordem do registra na ordem alfabética apos a edição do registro.

**Comment by Junior-Shyko** [comment]
> **Observações:**
> 
> * [ ]   1. Exibir campos em **ordem alfabética**, pela coluna "Nome", em Taxonomias (todas).
> * [ ]   2. Ao lado do botão [Cadastrar], adicionar o botão [Fechar], direcionando o usuário para o Painel.
> * [ ]   3. Após cadastrar ou editar algum registro nas taxonomias, limpar os campos "Nome:" e "Descrição".
> * [ ]   4. Ao editar o nome, permitir editar também a "descrição" da taxonomia.
> * [ ]   5. Exibir no grid, entre as colunas "Nome" e "Ação", o conteúdo da "descrição" da Taxonomia.
> 
> **Validação concluída.**

No geral está em ordem alfabética, mas percebi que quando se edita o sistema coloca a edição para a última posição.
Irei verificar.
![Captura de tela de 2021-01-28 11-46-18](https://user-images.githubusercontent.com/7341117/106154543-7acce300-615e-11eb-9ddf-040c1a9b84a6.png)

**Comment by Junior-Shyko** [comment]
Done!

**Comment by rafaelmassuncao** [comment]
Validado! Pode ser enviado para a Produção.
