### ISSUE TITLE
Criar oportunidade/edital para inscrições da equipe do NIT

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#136]
**Link para as Inscrições:** [:arrow_down: clique aqui](https://mapadasaude.dev.org.br/oportunidade/15/)
**Edital:** [:arrow_down: clique aqui](https://mapadasaude.dev.org.br/files/opportunity/15/edital_de_testes_nit_-_01_2021.pdf)

### Objetivo
**Como** equipe de testes do Mapas
**Quando** disponibilizar uma oportunidade no Mapas
**Então** as inscrições precisam estar funcionando em definitivo

### Escopo
Foi gerada uma [oportunidade](https://mapadasaude.dev.org.br/oportunidade/15/) de testes, com [edital](https://mapadasaude.dev.org.br/files/opportunity/15/edital_de_testes_nit_-_01_2021.pdf) para testes antes de enviar para a produção, em definitivo.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x] Edital redigido
- [x] Oportunidade testada
- [x] Redação de ajustes observados

### Observações

**Comment by rafaelmassuncao** [comment]
Esses usuários abaixo são para testes como participantes, já que os usuários da Camila, Luanna e Rafael serão Avaliadores.

- Usuário de Testes da **Camila**
:bust_in_silhouette: rmadev.master@gmail.com

- Usuário de Testes da **Luanna**
:bust_in_silhouette: rafael.assuncao@esp.ce.gov.br

- Usuário de Testes do **Rafael**
:bust_in_silhouette: arieromleafar@gmail.com

O usuário **administrador** é:
- :bust_in_silhouette: desenvolvimento@esp.ce.gov.br

**Comment by rafaelmassuncao** [comment]
**Ajustes observados:** 

- Menu de avaliações: quando clica no nome do inscrito, vai para a oportunidade. Deve enviar para a inscrição.
- Informar ao usuário (de forma padrão) que, em caso de envio de vários arquivos, compactar para o formato .zip.
- Retirar sujeira "0.1" na avaliação.
- Quando avaliar o último candidato, voltar para a tela de avaliações.
- Inserir botão de retorno (voltar) para a página de avaliações, quando estiver avaliando uma inscrição.
- Na hora de avaliar cada candidato, inserir botão próximo.
- O sistema deve verificar se o avaliador concluiu a avaliação de todos os inscritos designados a ele.
- Não está filtrando por categoria. 
- Incluir função para realizar a classificação automática, por pontuação e critérios de classificação.
- Aumentar a altura das caixas de texto do tipo "textarea". Altura mínima de 100px. Largura de 80%.
- :bomb: :scream: Nas fases seguintes, não será permitido ao participante, alterar os dados já informamos na inscrição e fases anteriores da oportunidade. Tais informações devem ser exibidas somente leitura ou suprimidas:
![Captura de tela de 2021-02-04 10-37-36](https://user-images.githubusercontent.com/57232674/106900411-3ea4ff80-66d5-11eb-9efd-13fb9e20d7f8.png)

- As informações que não forem utilizadas na oportunidade (como exemplo, o "Espaço Vinculado") devem ser suprimidas.
- Mesmo após o resultado final, o botão [Solicitar Recurso] ainda aparece para o participante:
![Captura de tela de 2021-02-10 14-48-29](https://user-images.githubusercontent.com/57232674/107549865-14f54800-6baf-11eb-91ea-a7a97c923528.png)

- Na lista das suas avaliações o link para a inscrição dele se repete. Ver a possibilidade de mesclar a informação:
![Captura de tela de 2021-02-10 14-50-17](https://user-images.githubusercontent.com/57232674/107550110-66053c00-6baf-11eb-8c27-2a024603aa56.png)

**Comment by luannaalves** [comment]
**Ajustes observados:**

Sugestões:

- Organizar inscrições enviadas (na página Minhas Inscrições) por ordem da data de envio da inscrição. Atualmente está aleatório.
- Emitir alerta visual para o agente, que foi iniciado o prazo para uma nova etapa do processo;
- Emitir alerta visual para o avaliador informando que há novas inscrições para serem avaliadas;
- Melhorar visualmente link de acesso para Exposição de competências;
- Após concluir uma avaliação e enviar, o botão **Finalizar avaliação e avançar** poderia ficar desabilitado. (pois ficamos na dúvida se foi enviado mesmo ou não)
