### ISSUE TITLE
Painel de controle: padronizar css dos cards (bordas e fundo)

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#137]

**Comment by luannaalves** [comment]
Iniciando validação.

**Comment by luannaalves** [comment]
Observações:

- [x] Padronização dos css dos cards (bordas e fundo) do Painel de Controle

Identificado **erro** na nomeclatura **Taxonomia**, está escrito _Taxomonias_ Escrita, no campo tipo text do item Nome, em todas as cinco janelas (Agente, Espaço, Projeto, Oportunidade e Área).

**Comment by rafaelmassuncao** [comment]
- [ ] Substituir escrita no placeholder "Taxonomias Escrita" por "informe o nome".

**Após, subir para a Produção.**

> Observações:
> 
> * [x]  Padronização dos css dos cards (bordas e fundo) do Painel de Controle
> 
> Identificado **erro** na nomeclatura **Taxonomia**, está escrito _Taxomonias_ Escrita, no campo tipo text do item Nome, em todas as cinco janelas (Agente, Espaço, Projeto, Oportunidade e Área).
