### ISSUE TITLE
Campos telefone: permitir padrões internacionais

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#138]
## **Objetivo**

**Como** como usuário de uma inscrição
**Quero** informar meu telefone de contato independente do tipo
**Para** salvar a minha inscrição

## **Escopo**

Os campos de telefone que estão no sistema só recebem o formato brasileiro e celulares. Precisa-se receber telefones fixos e telefones em formatos internacionais.

## **Fora de Escopo**

- Não se aplica

## **Critérios de Aceitação**

- [ ] Os campos para telefone permitem inserir formatos internacionais

# Observações

Não se aplica

**Comment by luannaalves** [comment]
Aguardando @victorMagalhaesPacheco realizar commit na homologação.

**Comment by vicmagpac** [comment]
> Aguardando @victorMagalhaesPacheco realizar commit na homologação.

Em produção.
