### ISSUE TITLE
Implementação indicadores força de trabalho - mapas

### ISSUE THREAD

**Issue by vicmagpac** [FeliciLab/mapadasaude#14]
- [x] Profissionais de saúde
- [x] Profissionais médicos
- [x] Instituições
- [x] Adicionar filtros
- [x] Corrigir filtro CBO para mostrar menu dropdown para escolha
- [ ] Calcular e mostrar índice de médicos/1000hab. Comparar com valor definido pela OMS/OPAS/SUS.
- [ ] Calcular e mostrar índice de ACS/1000hab. 
- [ ] Calcular e mostrar índice de quantidade de habitantes por unidade de saúde.
- [ ] Calcular e mostrar índice de cobertura das Equipes de Saúde da Família

**Comment by thaistoscano** [comment]
Foi realizada a implementação dos indicadores, porém está suprimido atualmente. 
https://app.zenhub.com/workspaces/mapa-da-sade---dev-60f894f541f910001066bfd9/issues/escoladesaudepublica/saude/272
