### ISSUE TITLE
Oportunidades: Fase pós inscrições não abre no período solicitado

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#141]
### Objetivo
**Como** participante
**Quando** selecionado, deseja participar da próxima fase da seleção
**Então** a página não exibe a(s) opção(ões) da fase para preenchimento

### Escopo
Nas "Oportunidades", um participante que foi selecionado na fase de inscrições não consegue iniciar a próxima fase da seleção.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x] A(s) fase(s) posteriores às inscrições deverão abrir no momento correto, segundo configuração do calendário

### Observações
Seguem imagens para averiguação da problemática encontrada.
![Captura de tela de 2021-01-28 13-30-30](https://user-images.githubusercontent.com/57232674/106169092-c044dc80-616d-11eb-902c-924df1f61f1a.png)
![Captura de tela de 2021-01-28 13-30-55](https://user-images.githubusercontent.com/57232674/106169102-c33fcd00-616d-11eb-8530-e4ab36d5f756.png)
![Captura de tela de 2021-01-28 13-31-14](https://user-images.githubusercontent.com/57232674/106169110-c6d35400-616d-11eb-8a56-7c9d5b2c3bd3.png)

**Comment by Junior-Shyko** [comment]
Já existe essa forma de fazer isso, é através do painel do avaliador, exportando e importando o resultado.

**Comment by uira** [comment]
@Junior-Shyko humm.... pera.... isso é pra ser automático, não?
