### ISSUE TITLE
Adicionar opções de compartilhamento no Instagram

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#144]
### Objetivo
**Como** usuário
**Quando** queira compartilhar algo do Mapas no Instagram
**Então** deve existir as opções de compartilhamento

### Escopo
O agente logado deverá ter a opção de divulgar informações disponibilizadas no Mapas (eventos, editais, espaços, etc.) no Instagram.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [ ] API do Instagram criada (se necessário)
- [ ] Compartilhamento adicionado

### Observações
Este card se liga ao card #142 .

**Comment by Junior-Shyko** [comment]
Rede Social não dispõe de documentação para realizar essa tarefa.
