### ISSUE TITLE
Adicionar opções de compartilhamento no Twitter

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#145]
### Objetivo
**Como** usuário
**Quando** queira compartilhar algo do Mapas no Twitter
**Então** deve existir as opções de compartilhamento

### Escopo
O agente logado deverá ter a opção de divulgar informações disponibilizadas no Mapas (eventos, editais, espaços, etc.) no Twitter.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x] API do Twitter criada (se necessário)
- [x] Compartilhamento adicionado

### Observações
Este card se liga ao card #142 .

**Comment by Junior-Shyko** [comment]
Com base na [documentação](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview) do Twitter
