### ISSUE TITLE
Segurança: suprimir códigos de registros nas URLs

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#147]
### Objetivo
**Como** usuário
**Quando** exibidas as informações sobre eventos, espaços, agentes, projetos e oportunidades
**Então** a URL não deveria exibir os códigos de banco

### Escopo
Quando qualquer pessoa acessa qualquer evento, espaço, agente, projeto ou oportunidade, é exibida na URL o código daquele registro do banco. O sistema deve ocultar as informações ou substituir o que é exibido, por questão de segurança.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [ ] As URLs aparecem de forma segura aos usuários

### Observações
A proposta foi observada por um agente que se inscreveu no Mapas. 

Em contato com nossa Coordenadora de Narrativas, Dra Clarisse Castro, o mesmo enviou uma sugestão, conforme imagem a seguir:
![photo_2021-01-29_07-19-47](https://user-images.githubusercontent.com/57232674/106263032-9a1d4c00-6202-11eb-883f-a82a51dcad98.jpg)

**Comment by Junior-Shyko** [comment]
O mapas é um projeto de anos atrás e usa nas rotas parâmetros na url necessário. Eventualidades como passar somente um nome do usuário teria que ter um outro meio para identificar o usuário certo pois podem ter vários usuário com o mesmo nome.
hoje em dia, existe algumas bibliotecas .Js que usam rotas de forma diferente, como existe Vue Router, Angular Router, React Router e etc que poderia evitar um pouco mais essa questão.
Mas para não passar parametros pela url no mapas, teria que mudar a estrutura como ele está feito hoje em dia.
