### ISSUE TITLE
Atualizar para release recente

### ISSUE THREAD

**Issue by Junior-Shyko** [FeliciLab/mapadasaude#148]
## **Objetivo**

**Como**  desenvolvedor do Mapa da saúde  
**Quero** atualizar o projeto
**Para** nova release (v5.0.0-rc10) , tanto o repositório quando a imagem docker

## **Contexto**

- Na nova release tem correções de bugs e algumas melhorias tanto para o desenvolvimento quanto para os usuários

## **Escopo**

- [ ] Atualizar para release v5.0.0-rc10 - **TESTES (LOCAL)** 
- [ ] Atualizar para release v5.0.0-rc10 - **HOMOLOGAÇÃO** 
- [ ] Atualizar para release v5.0.0-rc10 - **PRODUÇÃO** 

## **Fora de Escopo**

- fora_de_escopo

# Observações

**Comment by vicmagpac** [comment]
### novas funcionalidades e melhorias
- no painel dos administradores, exibe todos os selos que o usuário logado tem permissão de editar

### correções
- corrige links quebrados no ApiOutput/Html
- impede que os selos certificadores sejam excluídos
- corrige endpoint api/opportunity/find (refs: #1636)
- corrige validação do valor '0' em campos obrigatórios das oportunidades
- corrige links do histórico de revisões das entidades (#1663)
### outras correções e melhorias
- força o tipo inteiro no retorno dos metadados das consultas à api
- adiciona método findIds à classe ApiQuery, que retorna somente os ids das entidades encontradas
- adiciona parâmetro ao Entity::getPropertiesMetadata para retornar também os nomes das colunas das propriedades
- adiciona label para o campo _type
- possibilita configuração de inicialização do php (ini_set) por rota utilizando a configuraçao ini.set
- transforma método Entity::getEntityTypeLabel estático
- faz o segundo parâmetro da função env ser opcional
-adiciona pacote para validação de contas bancárias
