### ISSUE TITLE
Apresentar notas para o candidato somente quando for avaliação técnica

### ISSUE THREAD

**Issue by vicmagpac** [FeliciLab/mapadasaude#154]
## **Objetivo**

**Como** usuária participante de uma oportunidade do mapas
**Quero** acompanhar a situação da etapa finalizada baseado no tipo de avaliação (Simplificada, documental e técnica)
**Para** visualizar com maior fidelidade o acompanhamento da situação

## **Contexto**

- Na nova funcionalidade implementar pelo @Junior-Shyko para apresentação das notas na área do candidato, independente do tipo de avaliação definida para aquele momento, o sistema sempre mostra uma nota, mesmo o momento não existindo nota. Na simplificada ou documental não gera nota e sim um status pré definido no mapas. Necessário ocultar a nota quando não existir nota baseado no tipo de avaliação.

## **Escopo**

- [x] Mostrar nota apenas quando o tipo de avaliação existir nota

## **Fora de Escopo**

- apresentar notas em tipos de avaliações (documental ou simplificada)

## **Critérios de Aceitação**

- [x] Mostrar nota apenas quando o tipo de avaliação existir nota  
**Dado que** acesso a área de participante de uma oportunidade  
**Quando** verifico a situação da etapa  
**então** é mostrado a nota somente se o tipo de avaliação existir a nota (avaliação técnica)

# Observações

Não se aplica

**Comment by fernandafnascmnt** [comment]
![Captura de tela de 2021-05-27 10-27-18](https://user-images.githubusercontent.com/44043740/119834343-3cf68600-bed6-11eb-9512-01a26f14783e.png)
![Captura de tela de 2021-05-27 10-27-04](https://user-images.githubusercontent.com/44043740/119834348-3d8f1c80-bed6-11eb-8d83-78a892d34ac6.png)
![Captura de tela de 2021-05-27 10-26-47](https://user-images.githubusercontent.com/44043740/119834349-3d8f1c80-bed6-11eb-9069-9f62e68dd9e9.png)
