### ISSUE TITLE
Gerar nova oportunidade de inscrições com fase única

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#156]
**Issue anterior, que originou a demanda:** #136 
**Link para as Inscrições:** [:arrow_down: clique aqui](https://mapadasaude.dev.org.br/oportunidade/39/)
**Formulário de Solicitação do Edital:** [:arrow_down: clique aqui](https://docs.google.com/document/d/1SMAbzL_RgrD1vtIWGfErhIxqPfVRs-umfCnBzvdgvSU/edit?usp=sharing)
**Edital:** [:arrow_down: clique aqui](https://docs.google.com/document/d/186ykkdDeaMs-_jTLesxvjqYrSkIXHgK8dq8g6DwhZcA/edit?usp=sharing)

### Objetivo
**Como** equipe de testes do Mapas
**Quando** disponibilizar uma oportunidade no Mapas
**Então** as inscrições precisam estar funcionando em definitivo.

### Escopo
Deve ser gerada uma [oportunidade] de testes, com [edital] para testes antes de enviar para a produção, em definitivo.

Essa oportunidade, precisará ter uma etapa única, onde acontecerá todo o necessário para o participante ser analisado e possivelmente aprovado.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação

- [x] Formulário (FSO) concluído
- [x] Edital redigido
- [x] Oportunidade testada
- [x] Redação de ajustes observados

### Observações
Ao final, os testadores deverão adicionar, nos comentários dessa issue, os ajustes que consideraram necessários.

**Atenção:** as obervações já apresentadas na issue #136 não deverão ser repetidas neste teste, pois já existe precisão de entrada das mesmas no backlog da próxima sprint.

**Usuários:** Esses usuários abaixo são para **testes** como participantes da oportunidade, já que os usuários da Luanna (@luannaalves ) e do Rafael (@rmadev-master ) serão **Avaliadores**.

- Usuário de Testes da **Luanna**
:bust_in_silhouette: rafael.assuncao@esp.ce.gov.br

- Usuário de Testes do **Rafael**
:bust_in_silhouette: arieromleafar@gmail.com

O usuário **administrador** é:
- :bust_in_silhouette: desenvolvimento@esp.ce.gov.br

**Comment by luannaalves** [comment]
Comentários:

- Ao clicar no botão Salvar, para armazenar as informações já descritas e continuar posteriormente, a página poderia voltar para sessão anterior, e constar no quadro que a inscrição está em andamento, caso por exemplo, o candidato necessite fazer o logoff no site.

- Quanto ao anexo de arquivos, ou permitir que anexe arquivos individualmente, ou ter um informativo que os arquivos devem ser zipados para serem enviados (no campo de anexo).

- No momento está permitindo editar a nota de uma avaliação já feita e enviada. Isso deve ser possível? O botão de envio não deveria ficar desabilitado, para evitar modificações. A não ser posteriormente à fase de recursos.

 - Do lado esquerdo da página de avaliações, tem uma coluna com notas com nome , numero de inscrição e nota do candidato. Acho que poderia ir organizando por ordem da nota de avaliação, em ordem decrescente de cima a baixo. E no caso de inscrições ainda pendentes de avaliação, o quadro ficar em vermelho.
