### ISSUE TITLE
Avaliações: Não está filtrando por categoria

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#165]
### Objetivo
**Como** agente 
**Quando** acessar o Mapa da saúde, no menu de avaliações
**Então** o select deve permitir filtrar as avaliações por categorias

### Escopo
Na página de Avaliações, deverá corrigir bug, no qual não está permitindo filtrar as avaliações por categoria.

### Critérios de Aceitação
- [ ]  Corrigir bug, permitir na página de avaliações que filtre por categoria

### Observações

**Comment by fernandafnascmnt** [comment]
Após investigações, percebeu-se que: 

- Não se trata de um _bug_ e sim de algo nativo do Mapa, o qual não permite que o avaliador filtre por categoria. O usuário do tipo administrador consegue realizar este filtro normalmente; 

Buscando por informações na comunidade do Mapas no telegram, recebemos a seguinte informação:

`Normalmente é o administrador da oportunidade que configura a distribuição das inscrições por categoria, assim o avaliador do visualiza as inscrições da sua categoria.` _André_ **SecultCE**

**Comment by luannaalves** [comment]
Já implementado.
