### ISSUE TITLE
Aumentar a altura das caixas de texto do tipo "textarea".

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#167]
## **Objetivo**

**Como** candidato a oportunidade
**Quero** visualizar uma caixa com tamanho padrão
**Para** preencher um campo de texto da aoportunidade

## **Escopo**

![Captura de tela de 2021-05-26 11-38-06](https://user-images.githubusercontent.com/44043740/119679877-17ef0e00-be17-11eb-84d9-a71be1644b1a.png)

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Campo de Text area com as especificações:
width: 550px;
height: 120px;

- [x]  campo de texto simples: 
width: 550px;

# Observações

ex: Prototipo

**Comment by fernandafnascmnt** [comment]
width: 550px;
    height: 120px;

![Captura de tela de 2021-05-26 10-34-29](https://user-images.githubusercontent.com/44043740/119669586-8da2ac00-be0e-11eb-9551-05ae882f4db6.png)

**Comment by fernandafnascmnt** [comment]
adicionar a mesma largura no campo de texto simples.

**Comment by luannaalves** [comment]
![image](https://user-images.githubusercontent.com/74267308/120795435-d8f44300-c50f-11eb-8449-b438bec6615b.png)
