### ISSUE TITLE
Não permitir ao participante, alterar dados informados na fase anterior à que está participando

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#168]
### Objetivo
**Como** participante
**Quando** acessar a próxima fase da oportunidade
**Então** não deverá ser possível alterar qualquer informação já estabelecida na primeira fase.

### Escopo
Quando o participante participa de uma oportunidade onde existe mais de uma fase, após ir para uma fase seguinte o sistema não poderá permitir a alteração de registros já escolhidos ou enviados pelo participante em uma fase anterior.

Pois isto ocorrendo, todos os critérios usados para habilitar o participante para a fase seguinte poderão ser fraldados e o mesmo poderá se aproveitar disso para se incluir em classificação.

### Critérios de Aceitação
- [x] **Não é possível alterar o filtro padrão das oportunidades**
**Dado** que 
**Quando** 
**Então** 

- [x] **Não é possível alterar, enviar ou reenviar arquivos ou dados de fases anteriores**
**Dado** que como agente participante de uma oportunidade
**Quando** esteja em uma fase atual
**Então** não possa mais alterar dados já enviados anteriormente em fases anteriores.

### Observações
---

**Comment by fernandafnascmnt** [comment]
![Captura de tela de 2021-05-04 11-02-36](https://user-images.githubusercontent.com/44043740/117015692-59811300-acc8-11eb-9408-0521baaee9ef.png)

**Comment by fernandafnascmnt** [comment]
Testado em homologação, com duas fases técnicas para constatar que não é possível alterar nenhuma informação de uma fase para a outra. 

![Captura de tela de 2021-05-05 10-22-17](https://user-images.githubusercontent.com/44043740/117147826-ffe21c80-ad8b-11eb-924a-501c18c11051.png)
