### ISSUE TITLE
Buscar Dados

### ISSUE THREAD

**Issue by Junior-Shyko** [FeliciLab/mapadasaude#17]
- ARES - Dados dos Médicos que se matricularam em Residência
- Profissionais Sesa
- Planos Privados?
- CRM
- Dados EBSERH
- ISGH
- Dados residencial dos profissionais

**Links importantes**
http://sage.saude.gov.br/#modalMapa
http://datasus.saude.gov.br/
http://tabnet.datasus.gov.br/tabdata/livroidb/2ed/indicadores.pdf
https://www.conasems.org.br/
https://www.portalgestaoconasems.net/
https://wiki.saude.gov.br/cmd/index.php/P%C3%A1gina_principal
https://conjuntominimo.saude.gov.br/#/
https://cosemsce.org.br/download/
https://cosemsce.org.br/documentos/download/Oficinas-Descentralizadas-COSEMSCE-e-SUS-AB-CMD.pdf
https://cosemsce.org.br/documentos/download/Oficinas-Descentralizadas-COSEMSCE-SIA-SIH-CNES-SIGTAP-CMD.pdf

**Comment by thaistoscano** [comment]
Estão contempladas as integrações. Algumas delas estão na EAP e outras estão despriorizadas e não estão na EAP.
