### ISSUE TITLE
Melhorar visualmente link de acesso para outras fases das oportunidades

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#175]
### Objetivo
**Como** agente candidato
**Quando** acesse as diversas etapas do processo
**Então** o sistema apresente botões de acesso à novas etapas da inscrição com melhor identificação visual.

### Escopo
Atualmente, nas páginas do processo de inscrição do candidato à um respectivo edital, os links de acesso à etapas seguintes estão no próprio título da página, por exemplo, Exposição de competências, é necessário passar a seta por cima do nome para identificar que ali é o link, tornando necessário a busca pelo link dentro da página. Com isso, inserir um campo tipo Botão, com destaque em cor (sugestão: amarelo) com o nome da etapa e link de acesso, de fácil visualização para o candidato.
Fazer isso para cada etapa da inscrição.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x]  Criar botão de fácil visibilidade com nome da etapa da inscrição e link de acesso ao candidato
 
### Observações

**Comment by Junior-Shyko** [comment]
Adicionado linha de divisão entre as oportunidades;
Adicionado o botão de acesso;
Adicionado o titulo com a indicação de acesso + nome da etapa;
**Obs**: _Adicionar o nome da etapa no botão da quebra de layout pois o nome da fase pode ser grande._

![Captura de tela de 2021-02-15 17-33-15](https://user-images.githubusercontent.com/7341117/107991038-89b3f200-6fb4-11eb-9fb4-a5c834b009e3.png)

**Comment by Junior-Shyko** [comment]
Resultado em homologação:

![Captura de tela de 2021-02-17 09-13-54](https://user-images.githubusercontent.com/7341117/108202880-8594eb00-7100-11eb-8b67-6b0a1462e63a.png)

**Comment by vicmagpac** [comment]
@Junior-Shyko Ficou bom! Bem mais organizado do que o padrão que vem do mapas.

**Comment by Junior-Shyko** [comment]
Imagem da produção com o link de acesso a inscrição e as fase se tiver.

![Captura de tela de 2021-02-17 10-35-10](https://user-images.githubusercontent.com/7341117/108211794-e83fb400-710b-11eb-98e1-984eb0c4ae09.png)
