### ISSUE TITLE
Relatórios são exibidos em: PDF

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#189]
**Issue de Origem:** #87 

### Objetivo
**Como** agente administrativo
**Quando** quiser imprimir relatórios referente a uma oportunidade
**Então** o sistema deve disponibilizar recursos de impressão em PDF 

### Escopo
O sistema deverá permitir ao agente administrativo que possa imprimir os relatórios referente a oportunidades em PDF.

### Critérios de Aceitação
- [x] Impressão de relatórios em PDF

### Observações
---

**Comment by luannaalves** [comment]
![image](https://user-images.githubusercontent.com/74267308/119181893-9aa75000-ba48-11eb-8761-e0228f595ef9.png)
Geração de relatórios de Resultados Definitivos está gerando erro na produção, não está sendo gerado.

**Comment by fernandafnascmnt** [comment]
Excepcionalmente esta oportunidade está apresentando este erro porque ela foi alterada manualmente no banco algumas vezes, então desconfiamos que por isso ela esta apresentando esse erro. Já tivemos ciẽncia dele
