### ISSUE TITLE
Utilização dados da CAPES 

### ISSUE THREAD

**Issue by rafaelalima** [FeliciLab/mapadasaude#19]
O documento de área possui uma estrutura dividida em seis tópicos contendo as considerações, requisitos e orientações a respeito do estágio atual da área, das propostas de cursos novos, da avaliação trienal, do Qualis e classificação de livros, eventos e produtos técnicos, de critérios de internacionalização, além da Ficha de Avaliação a ser utilizada no triênio para programas acadêmicos e profissionais. No mesmo arquivo, poderá ser encontrada a relação dos nomes dos consultores que participaram da comissão de área na Avaliação Trienal 2013.

Área de Avaliação: MEDICINA I
https://docs.google.com/viewer?a=v&pid=sites&srcid=Y2FwZXMuZ292LmJyfHRyaWVuYWwtMjAxM3xneDoyYjkwNDllNDMzYzk2ZDlm 

Área de Avaliação: MEDICINA II
https://docs.google.com/viewer?a=v&pid=sites&srcid=Y2FwZXMuZ292LmJyfHRyaWVuYWwtMjAxM3xneDo3MmJjNmNkNzhkYjFkYzY5

Área de Avaliação: MEDICINA III
https://docs.google.com/viewer?a=v&pid=sites&srcid=Y2FwZXMuZ292LmJyfHRyaWVuYWwtMjAxM3xneDplYzMwNGQ1N2JjZThjOTc

Área de Avaliação: ODONTOLOGIA
https://docs.google.com/viewer?a=v&pid=sites&srcid=Y2FwZXMuZ292LmJyfHRyaWVuYWwtMjAxM3xneDoxNzIzMjJkZjBhNmJkMGY1

Área de Avaliação: SAÚDE COLETIVA
https://docs.google.com/viewer?a=v&pid=sites&srcid=Y2FwZXMuZ292LmJyfHRyaWVuYWwtMjAxM3xneDo0NWYwMmU5OGRjNTkyOWYz

**Comment by thaistoscano** [comment]
Card sem contexto. Em reunião com a equipe foi decidido pelo fechamento.
