### ISSUE TITLE
Elaborar material Passo-a-passo de uso do Mapa da Saúde para processo de seleções

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#198]
**Documento editável:** [clique aqui](https://docs.google.com/document/d/1lg22DKyRcfy-Orx-VYE1tdJQoQ6APpChGfwtsAtiMHM/edit?usp=sharing)
**PDF:** [clique aqui](https://github.com/EscolaDeSaudePublica/mapadasaude/files/6051102/Criando.seu.Agente.da.Saude.no.Mapas.pdf)

****
### Objetivo
Como necessidade urgente de entrega da primeiro MVP do Mapa da Saúde para elaboração de processos de seleções, então foi proposto à adaptação do modelo Mapa da Saúde atual, já com diversas melhorias inclusas, ao modelo atual de seleções aplicado pela Secretaria da Cultura, como forma de urgência.

### Escopo
Deverá ser criado um modelo Passo-a-passo para o usuário, apresentando todo o processo de seleções do Mapa da Saúde, que irá auxiliar ao agente como utilizar a ferramenta e se inscrever em um processo de seleção, assim como fazer o acompanhamento em todas as etapas do processo.

### Critérios de Aceitação
- [x] Elaborar material Passo-a-passo de utilização da ferramenta Mapa da saúde, para uso no processo de seleções.
- [x] Lançar material Passo-a-passo em formato PDF

**Comment by Junior-Shyko** [comment]
Iniciado tarefa e tutorial ficará no link a baixo.
[Tutorial passo a passo](https://sites.google.com/view/inscricao-mapa-da-saude/inicio)

**Comment by rafaelmassuncao** [comment]
**Documento Editável:** [clique aqui](https://docs.google.com/document/d/1lg22DKyRcfy-Orx-VYE1tdJQoQ6APpChGfwtsAtiMHM/edit?usp=sharing)

**Comment by rafaelmassuncao** [comment]
Documentação iniciada e atualizada de acordo com o projeto.

**Comment by rafaelmassuncao** [comment]
Ajustes realizados. 
Aguardando revisão da equipe.

Link para o documento: [clique aqui](https://docs.google.com/document/d/1lg22DKyRcfy-Orx-VYE1tdJQoQ6APpChGfwtsAtiMHM/edit?usp=sharing)

Nesse momento, o documento está focado em orientar ao usuário sobre como se cadastrar no Mapa da Saúde, além de uma breve apresentação da ferramenta.

**Comment by luannaalves** [comment]
Revisão concluída.
