### ISSUE TITLE
Adaptar modelo de Solicitação de oportunidade do Mapa da Saúde ao da Secult

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#199]
**Modelo do FSO:** [:arrow_down: clique aqui](https://docs.google.com/document/d/1LZzQyb5ODYDq_rMxtVK5wcHH_XwmwR0qLfVBqf0OZu4/edit?usp=sharing)

### Objetivo
Como necessidade urgente de entrega da primeiro MVP do Mapa da Saúde para elaboração de processos de seleções, então foi proposto à adaptação do modelo Mapa da Saúde atual, já com diversas melhorias inclusas, ao modelo atual de seleções aplicado pela Secretaria da Cultura, como forma de urgência.

### Escopo
Deverá ser adaptado o atual modelo de Solicitação de oportunidade, elaborado para o mapa da saúde, ao modelo de Solicitação de oportunidade da Secult.

### Critérios de Aceitação
 - [x] Adaptação do modelo de Solicitação de oportunidade do Mapa da Saúde, ao modelo de Solicitação de oportunidade da Secult
 
### Observações

**Comment by luannaalves** [comment]
Análise prévia concluída.

**Comment by rafaelmassuncao** [comment]
Análise prévia concluída.
