### ISSUE TITLE
Adaptar modelo de edital do Mapa da Saúde ao modelo da Secult

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#200]
**Link do Modelo de Edital:** [:arrow_down: clique aqui](https://docs.google.com/document/d/1zlDaSZgnbaNzZVLIIu9rhpFWVxeG1MZwWikZaGA-P7A/edit?usp=sharing)

### Objetivo

Como necessidade urgente de entrega da primeiro MVP do Mapa da Saúde para elaboração de processos de seleções, então foi proposto à adaptação do modelo Mapa da Saúde atual, já com diversas melhorias inclusas, ao modelo atual de seleções aplicado pela Secretaria da Cultura, como forma de urgência.

### Escopo
Deverá ser adaptado o atual modelo de edital, elaborado para o mapa da saúde, ao modelo de edital aplicado na Secult.

### Critérios de Aceitação
 - [x] Adaptação do modelo de Edital do Mapa da Saúde, ao modelo de Edital da Secult
 
### Observações

**Comment by rafaelmassuncao** [comment]
Análise prévia realiza.

**Comment by luannaalves** [comment]
Análise prévia concluída, com comentários no próprio documento.
