### ISSUE TITLE
Criar oportunidade de testes, seguindo o modelo de edital da issue #200 e TSO da issue #199

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#204]
### Objetivo
**Como** agente administrativo
**Quando** abrir uma oportunidade de inscrições em um processo seletivo
**Então** o sistema deve estar de acordo com o edital adaptado na issue #200 e o FSO da issue #199 

### Escopo
Essa semana, uma novo objetivo surgiu em relação à entrega do Mapa da Saúde. A entrega de um processo seletivo com o modelo mais aproximado possível aos processos seletivos que ocorrem na Secult.

Após reuniões e ajustes (#201 ), várias demandas foram criadas (issues) para que chegássemos ao objetivo final.

Portanto, deve-se criar uma oportunidade seguindo os parâmetros acertados nas reuniões. Nas observações, encontrar-se-ão os materiais que originaram a demanda da issue atual.

### Critérios de Aceitação
- [x] FSO criado para esta oportunidade
- [x] Edital criado para esta oportunidade
- [x] Oportunidade criada

### Observações
- **Documento base da decisão:** [:arrow_down: clique aqui](https://docs.google.com/document/d/1FctNV0ONcj7e4ss4ziILf8M4XtAQ9_Ue-qzvOT-Fq-Q/edit?usp=sharing)
- **FSO:** [:arrow_down: clique aqui](https://docs.google.com/document/d/1lE3zoiCoChVqNmIgI5st1WlYoUw6lp0J4T71jl7RF8I/edit?usp=sharing)
- **Edital:** [:arrow_down: clique aqui](https://docs.google.com/document/d/1ay2zsSDXnzswuyamIS5ImnyvPqhpc_FmUV8irgI1wcI/edit?usp=sharing)
- **Link para a Oportunidade:** [:arrow_down: clique aqui]

**Comment by luannaalves** [comment]
Edição da oportunidade como edital 03/2021 concluída, por Luanna e Fernanda. Aguardando suas considerações Rafael.

**Comment by rafaelmassuncao** [comment]
Edital finalizado.

**Comment by luannaalves** [comment]
Foi criada oportunidades de testes de edital de seleção, e mediante o realizado foram identificados os seguintes problemas e/ou dificuldades:

- Primeiramente, foi constatado, que atualmente não é possível dentro de uma mesma oportunidade (a exemplo de um edital), ter mais de um perfil de vaga, devido o Mapa não permitir (atualmente) criar critérios de avaliação separadamente para os perfis, tornando assim necessário criar oportunidades distintas para cada perfil (vaga).

- O mapa (atualmente) não permite utilizar números decimais no cálculo dos critérios de avaliação, devendo portanto ser ajustado no edital a priori, somente para uso de números inteiros;

- Durante a avaliação de um candidato, foram identificados alguns bugs: 
         - nos valores de avaliação, em alguns campos está aparecendo o valor mínimo de 1, e no caso, os valores mínimos devem ser sempre 0;
         - em alguns casos aparece uma mensagem de erro informando que em determinado critério foi inserido uma nota inferior ao valor mínimo, sendo um bug, pois a nota inserida está de dentro dos limites de mínimo e máximo;
         - em alguns itens da avaliação aparece valor mínimo e máximo de 0, sendo um bug, pois ao inserir os critérios foi colocado os valores corretos;
         - No edital II - Mestre, ocorre um bug no item 2 da análise curricular, fica surgindo um mensagem de erro independente da nota que seja inserida;
         - Ainda no edital II- mestre, o menu inicial de avaliações não está atualizando, depois das inscrições já terem sido analisadas e enviadas.

- Foi identificado que a análise e pontuações referente aos critérios de desempate, terão que ser  realizadas manualmente, através de planilha à parte.

- Além do mais, alguns campos foram identificados que podem ser renomeados, futuramente, para ajustar ao modelo de edital da ESP, tais como: Título das opções, Descrição das opções, Opções. Assim como, algumas melhorias podem ser implantadas, como a possibilidade de importar tabelas de critérios de avaliação, uma vez já utilizadas;

- Por fim, o edital deverá ser ajustado para ser possível realizar seleções no atual modelo disponível no Mapa da saúde.

**Comment by rafaelmassuncao** [comment]
Reiniciando a revisão do Edital.

**Comment by rafaelmassuncao** [comment]
Edital revisado e atualizado.
