### ISSUE TITLE
Snomed open source - gihthub

### ISSUE THREAD

**Issue by drmarcos** [FeliciLab/mapadasaude#21]
https://github.com/IHTSDO
https://github.com/IHTSDO/snomed-boot
Traduções:
https://refset.ihtsdotools.org/#/directory
No Brasil:
https://www.ofaj.com.br/colunas_conteudo.php?cod=757

**Comment by thaistoscano** [comment]
Card sem contexto. Em reunião com a equipe foi decidido pelo fechamento.
