### ISSUE TITLE
Ao clicar no campo "Ir para página de recursos"  destacar o recurso clicado

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#214]
### Objetivo
**Como** agente usuário do Mapa da saúde
**Quando** clique no botão Ir para página de Recursos 
**Então** a página seguinte  já abra no quadro do recurso em questão e ainda com uma borda destaque

### Escopo
Atualmente, ao clicar no botão *ir para página de recursos*, a página seguinte é aberta com lista de recursos, os quais podem dificultar o usuário encontrar mais rapidamente o recurso da oportunidade em questão. Com isso, é necessário vincular o botão *Ir para página de recursos* da oportunidade aberta, para que ao clicar no botão, a nova página abra já mostrando o quadro do recurso referente à esta oportunidade, e este quadro deverá ter uma borda destaque na cor vermelha.

### Critérios de Aceitação
- [x] Vincular o botão Ira para página de recursos, da oportunidade, com quadro do referido recurso na página seguinte
- [x] Criar borda de destaque vermelha no quadro do item do recurso clicado na página anterior

### Observações

**Comment by fernandafnascmnt** [comment]
![Captura de tela de 2021-03-30 11-46-41](https://user-images.githubusercontent.com/44043740/113011838-92215000-9150-11eb-840b-3e0186620f78.png)

**Comment by fernandafnascmnt** [comment]
![Captura de tela de 2021-03-30 11-46-50](https://user-images.githubusercontent.com/44043740/113011872-99485e00-9150-11eb-94f3-8fb3229f7622.png)
