### ISSUE TITLE
Gerar lista de inscrições deferidas e indeferidas do Edital 02/2021

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#225]
### Objetivo
**Como** participante da oportunidade do Edital 02/2021
**Quando** acessar o painel administrativo do Mapa
**Então** as inscrições deverão estar atualizadas

### Escopo
Essa demanda surgiu de forma extraordinária, baseada em reunião realizada junto à equipe da Banca Executora e outros gestores da ESP e, após reanálise da listagem de participantes selecionados, foi-se caracterizado que a participação de profissionais e estudantes com o CRM ou não (antes obrigatório).

Essa exigência somente se dará durante o ato da homologação.

### Critérios de Aceitação
- [x] Refinar a planilha
- [x] Enviar para a Elci
- [x] Atualizar candidatos aprovados (selecionados)
- [x] Ver a possibilidade de mostrar o link do meet para o candidato

### Observações
---

**Comment by rafaelmassuncao** [comment]
@Junior-Shyko e @FernandaNascimento26 

**Inscrições a serem atualizadas como selecionadas:** 

720655057
1593864955
1750691250
763896078
1894078682
746673928
55472778
951124457
547184045
369823586
1023689487
2053771627
1076435879
1003755102
2097088208
413170950
2132611397
1796934430
1911255323
1669211369
971249312
781333704
1321084410
1406417555
285421349
1197944516
186935371
880881252
1590050088
1095648388
351549470
1617436567
1713339263
1999655537
799162201
580143309
2078570307
1289227210
808599373
1258779129
1501321144
55467548
876303184
1872252479
710305782
1857686137
1926833684
737299867
1024681946
1349454734
1905133426
1196425610
2114402738
735327624
1064847687
1905996667
1628309214
1010119886
1760505757
1897288207
1311731059
728303155
1792557953
1066273876
1747868673
372079845
45750589
854327801
1033993309
1943760209
465050282
836900462
272591666
1640063714
1976134803
922422293
1603021348
51194629
1363627415
792482838
1471510495
46934370
1189370091
1057036830
53809381
71728323
2043770700
2087858115
1671168026
2078688332
80298941
1451494330
914425207
1194937653
1063869827
703875365
305558134
1840999761
1152256520
1049782164
810426513
998976231
47267711
1015887097
1017321090
1056571863
21713904
1724911746
1985157870
77937072
1287864011
1458071060
1661166278
69609902
1359544633
1689674626
39668131
1558123949
71593151
2141605481
764567039
3936455
2092524228
275986871
303722792
1970483263
902053773
1809980248
1720589178
2135164718
339830927
1967657373
816673366
1307458161
1746363116
1037443185
1266238238
179462845
2065503491
14440502
1678801807
651629989
1931953252
1299524162
65351559
2056400910
2107525124
1959339358
1731020007
993600571
585397858
1670215485
186261264
576481439
1715162904
2122020582
1014450428
905535019
1054747332
659363205
242618599
1424578877
1411800365
74121422
166941686
1620182769
2113280872
777211243
1562527908
1765157150
2007893649
1020199467
1074096054

**Comment by Junior-Shyko** [comment]
Status dos candidatos já estão como selecionados!!!

**Comment by rafaelmassuncao** [comment]
Relatório: [clique aqui](https://docs.google.com/document/d/1ueRkwJrFvw19Q19j6hqOk4GH6pIQwqF-yqNWBidNhpE/edit?usp=sharing)
