### ISSUE TITLE
Treinar equipe de coordenadores para responder recursos dentro do sistema

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#234]
**Edital:** 02/2021 - DIPSA
**Treinamento:** como responder recursos
**Responsáveis:** Luanna e Juninho
**Horário:** 09h a 10h
**Local:** Consultar agenda

**Comment by fernandafnascmnt** [comment]
**Reunião Treinamento Responder Recurso para os avaliadores do edital 02/2021**

- Primeiramente o Júnior se apresentou e explicou que esta funcionalidade do recurso é exclusiva do Mapa da Saúde

- Inicialmente foi mostrada a tela de Oportunidade, já criada (Teste 30/03/2021) 

- Importaram-se os candidatos inscritos no teste para a fase que simula a solicitação de recurso contra o gabarito. 

- Abriu-se a página do candidato e simulou-se o cenário em que o candidato clica na página de recurso, adiciona seu texto e envia seu recurso. 

- Em seguida, realizou-se login com um avaliador teste (os avaliadores questionaram se nós iriamos passar o login já pronto pra eles ); 

- Iniciou-se o cenário em que o avaliador visualiza e responde os recursos (deferindo, indeferindo, atribuindo nova nota) (BUG - aparecendo nome de outra pessoa na mensagem do banco) 

- Salientou-se que uma vez o avaliador se torne responsável pelo recurso, outro avaliador não poderá editá-lo

- Salientou-se que todos os recursos só poderão ser publicados após todos os recursos estarem respondidos. 

- Finalizou-se o cenário de teste; 

- Os avaliadores informaram que não serão eles que responderão o recurso e sim quem elaborou as questões. Então eles gostariam que a pessoa que elaborou respondessem, mas que eles (como avaliadores) poderiam complementar. 

- Em comum acordo, concordou-se que os avaliadores presentes se tornem responsáveis por adicionar as respostas do elaborador para que fique tudo centralizado no avaliador. 

- Os desenvolvedores se disponibilizaram a criar outro cenário de teste e enviar para os avaliadores, com o propósito de que eles possam realizar a atividade antes de estar de fato na avaliação real. 

- Abriu-se espaço para tirar possíveis dúvidas, no entanto, os avaliadores se disseram tranquilos com relação ao cenário apresentado. 

- Posterior a esta reunião será enviado o link com a gravação para os avaliadores.

**Comment by fernandafnascmnt** [comment]
[Link para a gravação do treinamento](https://drive.google.com/file/d/1C_ZW8AUWooa3DSonM053odD070Ocfnue/view?usp=sharing)
