### ISSUE TITLE
Criar documento comparativo Mapa x SACS

### ISSUE THREAD

**Issue by glaucia-posso** [FeliciLab/mapadasaude#264]
Elaborar um documento comparando os sistemas MAPA e SACS para ser apresentado ao Superintendente.
Enaltecer as fortalezas do MAPA e ter argumentos para contra argumentar o SACS.
Sugestão: Na tramitação dos processos de Editais inserir o NIT para validar a formatação do edital para o sistema. Sugestão de tramitação. GT CESP - NIT - ASJUR - SUP

**Comment by glaucia-posso** [comment]
> Elaborar um documento comparando os sistemas MAPA e SACS para ser apresentado ao Superintendente.
> Enaltecer as fortalezas do MAPA e ter argumentos para contra argumentar o SACS.
> Sugestão: Na tramitação dos processos de Editais inserir o NIT para validar a formatação do edital para o sistema. Sugestão de tramitação. GT CESP - NIT - ASJUR - SUP

**Comment by rafaelmassuncao** [comment]
### Documentos que servirão de subsídio para implementação da resposta

1. Comparativos: [clique aqui](https://docs.google.com/presentation/d/1LR0KF9-0svDfLWeyLlLtlOe7XscGj5fJr9dk7sZ2mXQ/edit?usp=sharing)
2. Planilha de detalhamento das funcionalidades: [clique aqui](https://docs.google.com/spreadsheets/d/1ujszsPKN68SjyZZ4Kabh05NFSaEmpmS9vX00BYoFduc/edit?usp=sharing)
3. Modelo proposto de Edital: [clique aqui](https://docs.google.com/document/d/1bOBIatKkNtAz8Wb0DmQZx0T5mVBjPJ1yB0j5n8Qpeg4/edit?usp=sharing)
4. Modelo proposto de solicitação de Processos Seletivos: [clique aqui](https://docs.google.com/document/d/1gjJEfv5uQBJgylPFHijXYDXFgjcktNoEOCimj2vUw-Y/edit?usp=sharing)
