### ISSUE TITLE
Adicionar campo de compartilhamento de PDF no hostsite

### ISSUE THREAD

**Issue by FernandaNascimento26** [FeliciLab/mapadasaude#267]
### Objetivo
**Como** usuário
**Quando** clicar em um botão de compartilhamento
**Então** quero compartilhar o pdf no whatsapp

### Escopo
Criar compartilhamento de link de algumas páginas do site: https://coronavirus.ceara.gov.br/profissional/manejoclinico/cenarios-de-atendimento/ pelo whatsapp

### Fora de Escopo
Não se aplica

**Comment by fernandafnascmnt** [comment]
Houve um ruído de comunicação e esta demanda não era direcionada ao Mapa. No entanto, a funcionalidade já havia sido iniciada, sendo enviada para os desenvolvedores responsáveis darem continuidade. 

https://user-images.githubusercontent.com/44043740/115294869-87465380-a12f-11eb-9127-0bc69d46f2ca.mp4
