### ISSUE TITLE
Relações de Taxonomias

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#272]
## **Objetivo**

**Como** solicitante do DesignLab
**Quero** a lista das taxonomias praticadas no Mapa da Saúde
**Para** consistir dados em outros produtos, iniciando pelo iSUS

## **Escopo**
- Ter as relações com as taxonomias no Mapa da Saúde.

## **Contexto**
- Em reunião realizada hoje, 22/04/2021 (#273 ), foi solicitado que houvesse a relação das taxonomias praticadas no Mapa da Saúde, conforme critérios de aceitação.

## **Critérios de Aceitação**
- [x] Relação de Áreas de Atuação
- [x] Relação de Categorias Profissionais
- [x] Relação de Especialidades
- [x] Relação de Graus Acadêmicos
- [x] Relação de Tipos de Espaços
- [x] Relação de Tipos de Oportunidade

# Observações
As listagens devem ser adicionadas ao corpo desta issue, para que conste como documentação.

**Comment by fernandafnascmnt** [comment]
**Agente**

[Relações de Taxonomias.pdf](https://github.com/EscolaDeSaudePublica/mapadasaude/files/6365354/Relacoes.de.Taxonomias.pdf)

**Comment by fernandafnascmnt** [comment]
**Espaço**
[_Taxonomias Espaços.pdf](https://github.com/EscolaDeSaudePublica/mapadasaude/files/6365361/_Taxonomias.Espacos.pdf)

**Comment by fernandafnascmnt** [comment]
**Oportunidade**
[_Oportunidade Taxonomia.pdf](https://github.com/EscolaDeSaudePublica/mapadasaude/files/6365363/_Oportunidade.Taxonomia.pdf)

**Comment by fernandafnascmnt** [comment]
**Área**
[_Area Taxonomia.pdf](https://github.com/EscolaDeSaudePublica/mapadasaude/files/6365367/_Area.Taxonomia.pdf)

**Comment by fernandafnascmnt** [comment]
**Projeto**
[_Projeto Taxonomia.pdf](https://github.com/EscolaDeSaudePublica/mapadasaude/files/6365369/_Projeto.Taxonomia.pdf)

**Comment by fernandafnascmnt** [comment]
![image](https://user-images.githubusercontent.com/44043740/115874293-4cd40380-a41a-11eb-8177-b3c3954e3d1c.png)
