### ISSUE TITLE
Reunião com CEATS

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#287]
**Dados da reunião**

**Data:** 30/04/2021
**Hora:** 14h00
**Assunto:** (Ceats) Apresentação do Mapa da Saúde
**Reunião gravada:** [clique aqui](https://youtu.be/u0ejK1j-XF4)
**Reunião:** [https://meet.google.com/ink-mdvp-gnj](https://meet.google.com/ink-mdvp-gnj)
**Apresentação:** [clique aqui](https://docs.google.com/presentation/d/1aykfrjFge0GKrDpqKRf3ISCiplzMxWePFNfQZHi-gpw/edit?usp=sharing)
**Apresentação PDF:** [clique aqui](https://github.com/EscolaDeSaudePublica/mapadasaude/files/6395111/apresentacao-mapas-2021-04-28.pdf)

**Participantes:**
- Adriana Melo de Farias - Psicóloga, Bolsista do CEATS (Atenção Psicossocial)
- Brenda Pinheiro - Enfermeira e Bolsista do CEATS
- Dra. Fátima Elias - Médica, Pediatra e Coordenadora do CEATS
- Profa. Gláucia Posso - Coordenadora do Projeto de Avaliação e Diagnóstico da Força de Trabalho do SUS
- José Luis - Assessoria Técnica do CEGES
- Larissa Rodrigues - Bolsista do CEATS
- Luanna Araújo - Business Analyst do Mapa da Saúde
- Naska Farias - Psicóloga e Gerente de Projetos do CEATS (Projeto de Saúde Mental)
- Rafael Moreira - Product Manager do Mapa da Saúde
- Viviane Gularte - Bolsista do CEATS (Projeto de Saúde Mental)

**Contexto**
- Rafael inicia agradecendo a presença de todos  e pede para que todos se apresentem rapidamente.
- Profa. Gláucia fala sobre dar início à apresentação da ferramenta e posteriormente dialogar a respeito do próprio mapa.
- Rafael fala:
  - Mapa da Saúde é uma iniciativa da ESP, porém foi desenvolvido em outro momento.
  - Sobre o Mapa da Saúde, está no mercado desde 2013, utilizado por 17 instituições, as quais atendem os mais diversos órgãos. Nós estamos adaptando para formação de rede da área da saúde, no momento estamos trabalhando para o projeto de Diagnóstico da Força de trabalham, que inicialmente contempla 4 áreas da saúde. Não impede que seja trabalhado para saúde mental.
  - Possibilidade de criar redes, de formalizar contatos, efetuar eventos, simpósios, fóruns, workshops, processos seletivos, mapeamento. É uma ferramenta que permite georreferenciamento, e permite cadastrar profissionais, ações de saúde da escola, do governo estadual, em diversas escalas, desde local a internacional.
  - Permite criar sua rede de colaboradores em uma única só ferramenta.
  - O Projeto do diagnóstico, por exemplo, permitirá tomar decisões, mediante dados como quantidade de profissionais atuais por região, quais áreas estão em defasagem, enfim, diversas formas de ações serão possíveis mediante os diagnósticos dos dados levantados.
  - Apresenta algumas das instituições que utilizam o Mapa.
   - Apresenta os endereços oficiais do Mapa, da ferramenta final e de testes.
  - Apresenta a plataforma de testes do Mapa da Saúde: os eventos que são possíveis de cadastrar dentro do Mapa.
  -  Mostra as instituições que podem ser cadastradas dentro do Mapa e visualizá-las dentro do mapa, com georreferenciamento. Apresenta como exemplo o cadastro da ESP, os dados que podem ser inseridos para a instituição, os setores que podem ser criados dentro da instituição informando os profissionais que atuam em cada um. Pode ser inserido grupos de trabalhos, sem limites de inserção de agentes.
  - Apresenta o cadastro da Instituição HGF no Mapa.
  - Apresenta o cadastro de agentes, as informações que ele pode inserir, todas opções, inclusive ele pode definir se serão públicas ou privadas, e se quer constar no Mapa ou não. O agente pode ser individual ou coletivo. Pode se ligar a outros agentes, ou a outras instituições. Um agente também pode cadastrar outros agentes.
  - É possível adicionar vídeos, imagens na galeria.
  - É possível adicionar projetos, dizer os participantes daquele grupo, adicionar subprojetos, dar descrição, criar rede, gerenciar responsáveis.
   - No link de oportunidades é onde se pode lançar diversos tipo de oportunidades, simpósios, eventos, editais, congressos, processo seletivos e diversos outros. É possível listar documentações, anexos, verificar lista de inscritos, pontuação, avaliadores. Apresenta um edital como modelo lançado no mapa. 
   - Há todo o controle para a LGPD, para as informações que são compartilhadas.
   - Há, ainda, o painel de controle, onde o usuário poderá gerir todas as suas informações e acompanhar as informações disponibilizadas no Mapa.
   - Há ainda a aplicação dos selos, que serão indicativos de qualidade, do nível de conhecimento e de contribuições de um agente na ferramenta e na área da saúde. Esta funcionalidade está ativa mas as políticas de qualificação estão em construção.
  
- Profa. Gláucia apresenta sobre o projeto de Diagnóstico da Força de Trabalho:
  - Título provisório, que está sob minha coordenação.
  - Possui 2 objetos: 1- Principal desafio é o diagnóstico da força de Trabalho do SUS do Estado do Ceará, das três esferas, municipal, estadual e federal, mediante cadastro de todos estes profissionais, saber quem são eles e onde estão atuando, mediante a possibilidade de georreferenciamento no mapa; 
  - Deverá ser levantado toda a força de trabalho do SUS, seja celetista, cooperado, concursado, dentre outros vínculos. Será possível identificar até se eles atuam em mais de uma unidade de saúde.
  - O intuito é que o CPF funcione como um chip para aquele profissional, para sabermos onde ele está trabalhando, dentro do Mapa. Deverá ser mais preciso que o CNES, até porque tem categorias profissionais que não estão no CNES.
  - Será também utilizado o Quiz para avaliar uma parte dessa força de trabalho.
  - Objetivo 2 - avaliar as competências de 4 áreas prioritárias (Ginecologia e Obstetrícia, Estratégia de saúde da família, terapia intensiva, Urgência e emergência), área médica e de enfermagem.
  
- Andréia sugere: Uma dica já que está estruturando este novo plano seria inserir a fisioterapia também na urgência e emergência como já iniciaram um trabalho efetivo. Profa. Gláucia responde que pode ser analisado, pois o projeto ainda está em construção.

- Dra. Fátima elogia a ferramenta, ressalta os entendimentos que obteve da apresentação da ferramenta. E pontua algumas dúvidas: 
  - Como se dará a atualização destes dados para os profissionais, para que o cadastro se mantenha sempre atualizado, visto que a rotatividade dos profissionais é dinâmica. 
  - Como se dará a questão dos cadastros fakes, qualquer um poderá se cadastrar, haverá alguma validação?
  - Quanto ao projeto de Diagnóstico, será apenas para a rede pública?
  - Posteriormente se pensa em ampliar esse cadastro do Projeto de Diagnóstico para demais áreas de atuação e níveis de profissionais, como os técnico?
  - Quanto à nossa demanda, eu entendi que para nosso projeto seria cadastrado um Evento, e nele cadastraria os profissionais que participam desse projeto.

- Profa. Gláucia responde:
  - O projeto se destina inicialmente um diagnóstico da Força de Trabalho do SUS, para atendimento à população que necessita e utiliza o SUS. Posteriormente a atingir esse objetivo, possa se estender aos serviços privados.7
  - Quanto a avaliação, inicialmente, é para os profissionais do ensino superior, destas 4 áreas. Pelo fato de que o profissional de nível superior deve deter conhecimento referente às áreas de atuação que o profissional de nível técnico atua.
  - Essa é uma proposta diagnóstica para promover a capacitação permanente a estes profissionais.
  - Um próximo passo será para os profissionais do nível técnico.
  
- Rafael responde:
  - Para vincular à informações verdadeiras, é vinculado a um CPF. Outras opções é conseguir com a receita o direcionamento da TI, conseguir com os conselhos. Outro controle do mapa é que um agente não pode se vincular a uma instituição, caso a mesma não aceite. Quanto aos selos, só recebe o usuário que seja aprovado pelo sistema. Outra forma, um usuário administrador consegue desativar um cadastro.
  - Quanto ao histórico do profissional, será adicionado ao sistema uma análise de histórico de por onde o profissional já atuou. 
  - Quanto a como vincular o projeto de saúde mental sim poderia ser cadastrado como evento. Porém há outras formas, tudo se inicia com o cadastro do agente, a partir daí você poderá criar um grupo de trabalho e vincular outros agentes. Outra forma é cadastrar uma instituição e posteriormente cadastrar os profissionais que atuam nessa instituição. 

- Profa. Gláucia reforça que a plataforma de testes pode ser utilizada amplamente, justamente para realizar cadastros de diversas possibilidades, pois estes dados não estarão disponíveis ao público.

- Rafael ressalta que todos as nossas ferramentas são integradas, por exemplo, se você se cadastra em uma das ferramentas, como Isus, automaticamente você estará cadastrado ao ID Saúde, e as demais ferramentas da ESP, sendo necessário apenas um único cadastrado, e você poderá logar nas demais.

- Dra. Fátima pergunta caso um profissional mude de instituição de trabalho, como fica o cadastro junto a ferramenta. 

- Rafael responde que uma das maneiras de incentivo para que o profissional mantenha seu cadastro atualizado á através das pontuações dos selos.  Outra parceria que está sendo formada é com o ISGH, que permitirá vincular uma grande quantidade de profissionais, e assim migrar informações de profissionais. 

- Dra. Fátima parabeniza por todo trabalho já realizado até então.

- Profa. Gláucia agradece e se coloca à disposição para contribuição.

- Rafael reforça que esse é um trabalho de construção conjunta, onde são necessárias diversas parcerias dos mais diversos setores. Esse é um trabalho pioneiro. Permitirá tomadas de decisões e políticas públicas.

- Rafael se disponibiliza à marcar um outro momento para treinamento do uso da ferramenta. 

- Todos agradecem e dar-se a reunião por encerrada.

**Comment by rmadev-master** [comment]
**Contexto:**

(aguardando)
