### ISSUE TITLE
Configurar Domínio

### ISSUE THREAD

**Issue by uira** [FeliciLab/mapadasaude#29]
Solicitar a configuração do domínio para a disponibilização do Mapa da Saúde:

- mapa.saude.ce.gov.br

**Comment by thaistoscano** [comment]
Tramitação já acontece pelo board do Administrativo
https://trello.com/c/K5AjtJwd/30-204-2020-of%C3%ADcio-processo-04551105-2020-of%C3%ADcio-2042020-cria%C3%A7%C3%A3o-de-novos-dom%C3%ADnios-para-projetos-de-inova%C3%A7%C3%A3o
