### ISSUE TITLE
Reunião com GTCESP - Treinamento de uso da ferramenta Mapa para Seleções

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#315]
### Dados da reunião

**Data:** 26/05/2021
**Hora:** 13h30
**Assunto:** Treinamento da Ferramenta Mapa da Saúde para uso de Seleções
**Reunião:** https://meet.google.com/zuu-rqdp-tdg
**Gravação da Reunião:** [clique aqui](https://youtu.be/tPXbEY5noTc)

### Participantes:

- Dra Gláucia Posso - Coordenadora do Projeto Força SUS
- Elci Galvão - Coordenadora do GTCesp
- Luanna Araújo - BA do Mapa da Saúde
- Rafael Moreira - Gestor do Mapa da Saúde
- Luciana Magalhães - Apoio técnico GTCesp
- Ricardo Araújo - Apoio técnico GTCesp

### Contexto:

- Rafael inicia pedindo que todos se apresentem rapidamente. Os participantes apresentam-se e suas respectivas funções.
- Elci sugere que seja tratado apenas sobre a primeira pauta referente a ferramenta SACS.
- Rafael reforça que é possível falar sobre as três pautas pois elas se intercalam.
- Rafael fala:
  - Inicia falando sobre a ferramenta SACS, que á a ferramenta utilizada até então pela ESP, porém que gera um certa complexidade para lançamento de um edital e demanda bastante tempo.
  - Hoje se tem descoberto uma nova ferramenta, o Mapa da saúde, que possibilita diversas vantagens em comparação ao SACS, no lançamento de editais.
  - Ao longo dos anos os processos foram mudando na ESP, novos projetos foram sendo implantados, e dos profissionais que estão na ESP a mais tempo, que só são 3 (Vitor, Helen, Rafael), foram deslocados para outras funções e setores, devido esta nova demanda de projetos que hoje compõem a ESP. Então apenas 2 destes profissionais atuavam no sistema de seleções, eu Rafael e a Helen, e hoje estes profissionais estão atuando em outros projetos, o que faz com que não tenha nenhuma equipe fixa no SACS. Posteriormente, houve acréscimo de um novo funcionário que foi o Júnior, e deu apoio ao SACS, porém posteriormente ele foi deslocado para outros projetos e hoje atua como desenvolvedor sênior no Mapa da Saúde. Temos outra desenvolvedora, que chegou a pouco, a Fernanda, que está dando apoio ao Júnior. 
  - Além dos desenvolvedores, nós temos na equipe além de mim, a Luanna, atuando como Analista de Negócios, que faz a ponte entre os desenvolvedores e as atividades que devem ser implantadas no Mapa. E contamos com a Dra. Glaucia, que compõe a equipe do Mapa, como PO para o projeto de Diagnóstico da Força de Trabalho do SUS, que é um projeto prioritário para superintendência.
  - Em meio a estes tantos projetos, tentamos conciliar as atividades para que o SACS e as demandas do GTCesp e da escola não fiquem sem ser atendidas. O sistema SACS é um sistema estrutural, ele foi criado com a tecnologia que dispunha na época, ou seja, ele tem uma estrutura base que deve ser mantida, pois se é alterada esta estrutura no banco é necessário fazer uma série de modificações no sistema, que geram um desafio enorme ao desenvolvedor e demanda de tempo.
  - Houve um tempo que o prazo para lançar os editais de seleção, eram de 15 dias, hoje é de 5 dias úteis. O profissional que tua hoje no SCAS faz o trabalho de 4 profissionais, um que analisa o edital, outro que cuida do banco de dados, o terceiro profissional é o que vai construir o sistema em si e deixar pronto para o usuário, e o quarto profissional é que vai fazer toda a verificação do trabalho realizado (que são os analista de testes), para assim garantir a funcionalidade do sistema antes de ele ser lançado da produção. E não dispomos de todos estes profissionais, e como são atividades que dependem que a anterior seja concluída para que a próxima seja realizada, o NIT adotou apenas um profissional para atuar no SACS, que sou eu. Porém além destas atividades junto ao SACS, tenho diversas funções como gestor do Mapa da Saúde, reuniões junto ao ministério público, setores da ESP, setores externos, acompanhamento do sistema SIGRH, apoio a outros projetos como o de Diagnóstico, dentre outros. E hoje para atender todas as estas demandas do GTCesp, com os prazos curtos que estão sendo colocados, está sendo necessário que eu trabalhe fora do expediente, o que além de prejudicar a vida pessoal pode ocasionar erros no trabalho que está sendo executado, devido a sobrecarga de rotina.
  - Atualmente, para dar um apoio a todas estas demandas, estamos contando com apoio da Luanna, na análise do edital, para que eu possa atender às outras demandas e reuniões que disponho.
  - Com base nisso é que se identificou que a possibilidade de uso da ferramenta do Mapa para aplicar seleções públicas da ESP seria de fundamental vantagem para cumprimento destas demandas e prazos.
  - Quais seriam as vantagens caso seja utilizado o mapa da saúde para este fim: 
     1. O primeiro seria o custo (pois não seria necessário a aquisição de um funcionário) o próprio setor do GTCESP poderia lançar o edital.
     2. O sistema permite que seja distribuído as avaliações entre outros avaliadores.
     3. Permite a mobilidade de distribuição de pesos para os critérios de avaliação e criar as avaliações de acordo com a necessidade;
     4. O sistema permite adicionar quantos campos sejam necessários ao edital (apresenta na própria ferramenta do Mapa);
  - Rafael apresenta a ferramenta do Mapa junto à homologação, e como utilizar a ferramenta para criação de uma oportunidade.
  - Elci fala que foi acordado em reunião com Uirá e Dr. Marcelo que ficou acordado de se elaborar um projeto em que o setor do GTCESP trabalhe as necessidades do setor para os editais e partir daí identificar como a ferramenta se enquadraria e se está apta juridicamente para ser substituída. Pois é necessário que se conheça a ferramenta se ela é confiável, se é transparente, e se de fato pode ser utilizada para seleções.
  - Elci pede que o NIT forneça um relatório sobre informações sobre o Mapa, que disponha sobre todas informações referente ao Mapa, sobre sua criação e todos os detalhes, para que o jurídico possa analisar.
  - Rafael pergunta a Elci de qual setor o GTCESP gostaria de receber esse parecer sobre o Mapa da saúde.
  - Elci reforça que quer todas as informações sobre histórico, funcionalidade, dados da ferramenta por escrito, em forma de processo encaminhado ao setor.
  - Glaucia fala que o Mapa não é um site, é uma plataforma utilizada para diversas necessidades da Escola hoje, um software livre. O Mapa não irá interferir na forma que o edital é criado ou como é elaborado o perfil dentro do GTCESP, a única alteração seria o sistema que seria utilizado para lançar as seleções, conforme o edital que foi elaborado pelo GTCESP. Então é uma ferramenta que pode ser customizada de acordo à necessidade do GTCESP, na qual nós já começamos a customizar para isso.
  - Luanna repassa os encaminhamentos da reunião e sugere que para auxílio da elaboração do Projeto pelo GTCESP seja trabalhado em conjunto por ambas as equipes a colocação de um ou mais editais que estão sendo lançados no SACS, que seja lançado como teste no Mapa, para que assim o GTCESP possa conhecer as funcionalidades, pontuar o que se enquadra ou que é necessário alterar ou melhorar.
  - Elci sugere que seja primeiramente elaborado as documentações propostas e posteriormente seja feito qualquer treinamento, principalmente após análise do jurídico.

### Encaminhamentos:
  - Elaboração de processo pelo setor do NIT, sobre informações da ferramenta Mapa da saúde, histórico, dados da tecnologia, domínio, dentre outros.
  - Elaboração de projeto pelo setor do GTCESP, com apoio de um profissional da equipe do Mapa, sobre as necessidades do setor nos processos de seleções e os critérios que a ferramenta Mapa da saúde deverá conter para adequação ao GTCESP.
  
Dar-se a reunião por encerrada.

**Comment by rafaelmassuncao** [comment]
Gravação anexada
