### ISSUE TITLE
Reunião Gerencial - 2021-06-01

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#323]
**Dados da reunião**

**Data:** 01/06/2021
**Hora:** 15h00
**Assunto:** Reunião Gerencial Semanal
**Reunião:** https://meet.google.com/ytz-bykf-qso?authuser=0

**Participantes:**
- Luanna Araújo - Business Analyst do Mapa da Saúde
- Rafael Moreira - Product Manager do Mapa da Saúde
- Victor Magalhães - Líder Técnico do FeliciLab

<table border="1" align="center">
  <tr>
    <td colspan="2"> <strong> :rocket: Boards</strong> </td>
  </tr>
  <tr>
    <td> <strong>IMG</strong> </td>
    <td>
      <a href='https://github.com/orgs/EscolaDeSaudePublica/projects/37' target='_blank'>[clique aqui]</a>
    </td>
  </tr>
  <tr>
    <td> <strong>DEV</strong> </td>
    <td>
      <a href='https://github.com/orgs/EscolaDeSaudePublica/projects/25' target='_blank'>[clique aqui]</a>
    </td>
  </tr>
</table>

<table border="1" align="center">
  <tr>
    <td colspan="2"> <strong> :card_file_box: Arquivos</strong> </td>
  </tr>

  <tr>
    <td> <strong>Apresentação</strong> </td>
    <td>
      <a href='https://docs.google.com/presentation/d/1gBhQ5RCfabPYuDhpw9j_lub1p4624XgwRjUTgzG5FGM/edit#slide=id.gd91d58f134_1_57'>[clique aqui]</a>
    </td>
  </tr>
</table>

**Comment by rafaelmassuncao** [comment]
A reunião não aconteceu.
