### ISSUE TITLE
Na tela de ordenação de oportunidades, como critério de ordenação utilizar data pra realização da oportunidade e, sem seguida, a ordem alfabética

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#352]
![Captura de tela de 2021-07-02 11-31-38](https://user-images.githubusercontent.com/57232674/124289944-3e484d80-db29-11eb-963e-36e976ab11c2.png)

**Comment by uira** [comment]
@rmadev-master isso precisa passar pelo designlab
