### ISSUE TITLE
Subprojetos vinculados a um projeto "guarda-chuva" deverão ser exibidos no formato de árvore de diretórios ou relacionados ao lado do projeto principal

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#353]
![Captura de tela de 2021-07-02 11-33-46](https://user-images.githubusercontent.com/57232674/124290321-abf47980-db29-11eb-9b02-1e64c0745ee1.png)

**Comment by uira** [comment]
@rmadev-master isso tambem
