### ISSUE TITLE
Adicionar validação de CPF

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#36]

**Comment by thaistoscano** [comment]
Já existe a validação de CPF, porém ainda é possível ter vários cadastros em um mesmo CPF (para esse segundo já existe uma issue: https://app.zenhub.com/workspaces/mapa-da-sade---refinamento-610039a15670a0000e67211f/issues/escoladesaudepublica/mapadasaude/498)
