### ISSUE TITLE
Retirar obrigatoriedade dos campos Descrição e Área de Atuação do cadastro do Agente

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#361]
### Objetivo
Como usuário rascunho do Mapa da Saúde
Quando acesse a página de cadastro do agente
Então não devo encontrar como obrigatoriedade de preenchimento os campos Área de Atuação e Descrição

**Escopo**
Deverá ser retirada a obrigatoriedade de preenchimento dos campos Descrição e Área de Atuação na página de cadastro do agente.

### Critérios de Aceitação
 - [x] Campo **Área de Atuação**, da página de cadastro do agente, Não deverá ser obrigatório
 - [x] Campo **Descrição**, da página de cadastro do agente, Não deverá ser obrigatório

### Observações

**Comment by fernandafnascmnt** [comment]
Develop atualizada e testada
Aguardando o @victorMagalhaesPacheco subir para a homologação

**Comment by vicmagpac** [comment]
> Develop atualizada e testada
> Aguardando o @victorMagalhaesPacheco subir para a homologação

Atualização em homologação realizada com sucesso.

**Comment by fernandafnascmnt** [comment]
Alterações foram solicitadas:
adicionar os arquivos alterados no tema Saude, no entanto apenas o arquivo widget-areas que faz que é parte do layout funcionou corretamente no tema, não sendo possivel adicionar a entidade Agente, que permanece no mapadasaude. 

Develop atualizada e testada

Aguardando subir para a homologação
