### ISSUE TITLE
Retornar para a página de inscrição, após usuário ter realizado cadastro no ID Saúde

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#362]
### Objetivo
Como usuário sem cadastro do Mapa da Saúde
Quando acesse uma inscrição e seja redirecionado para realizar cadastro no ID Saúde
Então quero retornar para a página da inscrição após conclusão do cadastro

### Escopo
Deverá ser realizado redirecionamento de páginas, para que quando um usuário sem cadastro esteja acessando uma oportunidade e queira realizar sua inscrição, quando o sistema o redirecionar para página do ID Saúde para criar o cadastro, então após o usuário concluir o cadastro no ID saúde, o acesso deverá voltar para a página que o usuário estava inicialmente, da oportunidade em questão.

### Critérios de Aceitação
- [x] Usuário sem cadastro ao acessar oportunidade para fazer inscrição, deverá ser redirecionado para página de cadastro do ID Saúde
- [x] Após usuário concluir cadastro na página do ID Saúde, o sistema deverá retornar para página que estava inicialmente, da oportunidade

**Comment by vicmagpac** [comment]
Em homologação.
