### ISSUE TITLE
Inserir campo de busca de agente no próprio card de inscrição da oportunidade de um Subprojeto

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#363]
### Objetivo
Como usuário cadastrado no Mapa da Saúde
Quando acesse um card de inscrição em uma oportunidade de um Subprojeto
Então já quero encontrar o campo para busca  e adição do agente.

### Escopo
Deverá ser adicionado no próprio card da inscrição na oportunidade de um subprojeto o campo para buscar e selecionar um agente já cadastrado.
Deverá ser seguido conforme protótipo.

### Critérios de Aceitação
- [x] Inserir campo para busca e seleção de agente no card da inscrição da oportunidade de um subprojeto

### Observações
Ver protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=20%3A260

**Comment by matheuscpl** [comment]
UX REVIEW: Há apenas uma alteração que gostaria de considerar, na aba inscrições ao listar as oportunidades e seus cards, o título da oportunidade se aproxima mais do card a que não pertence.!

![Screenshot_69.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/e108d90c-6c37-4555-924d-94089c2c9aac)

Sugestão, que a distancia de cima seja maior que a de baixo

**Comment by luannaalves** [comment]
**RESOLVER BUG**. No Menu Projetos, quando o usuário clica no botão de atalho de busca de um agente para realizar a inscrição em uma determinada oportunidade, ao selecionar o agente, o sistema está direcionando o usuário para outra oportunidade, distinta a que o candidato estava tentando se inscrever. Também ao tentar fechar a janela pelo botão cancelar, a janela tornava a aparecer repetidas vezes.

**Comment by vicmagpac** [comment]
Implementado na seguinte branch https://github.com/EscolaDeSaudePublica/Saude/compare/feature/busca-agent-multi-oportunidades

Foi testado com 4 oportunidades na mesma página, necessário simular com mais oportunidades, para simular o ambiente parecido com a homologação.

**Comment by Junior-Shyko** [comment]
**TESTES:** 

- [x] Realizado teste com 4 oportunidades de projetos 

- [ ]  Realizado teste com 3 oportunidade de eventos

- [x] Realizado teste com 3 de espaço

- [x] Realizar inscrição na própria página da oportunidade.
