### ISSUE TITLE
Permitir que usuário rascunho complete o cadastro e volte ao fluxo de inscrição

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#364]
### Objetivo
Como usuário rascunho do Mapa da Saúde
Quando seja redirecionado à página para completar o cadastro ao acessar uma inscrição
Então devo retornar para a página que estava inicialmente, após a conclusão do cadastro.

### Escopo
 Quando um usuário rascunho do mapa acesse uma oportunidade, clique para realizar a inscrição e seja redirecionado para página de conclusão do seu cadastro, após ele concluir o cadastro, quando salvar as informações então o sistema deverá redirecionar o usuário para a página que ele estava incialmente, da inscrição da oportunidade.
Deverá ser seguido conforme protótipo.

### Critérios de Aceitação
- [x] Sistema deverá redirecionar usuário para página que estava (Inscrição) após conclusão de cadastro do usuário

### Observações
Ver protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=24%3A263

**Comment by ericsonmoreira** [comment]
Atividades dessa _issue_ já foi realizada juntamente com a _issue_ #362 e está no PR #390.

**Comment by vicmagpac** [comment]
Em homologação.
