### ISSUE TITLE
Inserir Itens na relação de Especialiades (Agente) e Tipos de Unidade (Espaços)

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#369]
### Objetivo
Como usuário do Mapa da Saúde
Quando acesse a página do perfil para realização de cadastro de agente ou de um espaço
Então quero encontrar na relação itens conforme descrito no escopo.

### Escopo
Deverá ser incluído novos itens na relação de **especialidades** para que quando um agente realize seu cadastro então possa encontrar esses itens na lista de opções:
Campo especialidades, incluir:
- **Psiquiatria** (na categoria Saúde e Bem-estar)
- **Psicopedagogia** (na categoria Saúde e Bem-estar)
- **Administrativo** (na categoria Administração)

Deverá ser incluído novos itens na relação de Tipos de Unidade para que quando um usuário realize o cadastro de um **espaço** então possa encontrar esses itens na lista de opções para tipos de Unidade:
- **UBS**
- **NASF**
- **CAPS geral I**
- **CAPS geral II**
- **CAPS geral III**
- **CAPS AD I**
- **CAPS AD II**
- **CAPS AD III**
- **Unidade de acolhimento adulto** 
- **Unidade de acolhimento infanto-juvenil** 
- **Comunidade terapêutica**
- **Serviço de residência terapêutica** 
- **Ambulatório de saúde mental** 
- **Leitos especializados em hospital geral** 
- **Hospital psiquiátrico** 
- **SAMU**
- **Hospital - Dia**

Inserir itens com letras todas em MAIÚSCULA conforme padrão já existente no Mapa.

### Critérios de Aceitação
- [x] Incluir os itens: Psiquiatria, Psicopedagogia, Administrativo na relação de especialidades.
- [ ] Incluir os itens: UBS, NASF, CAPS geral I, II, III. CAPS AD I, II, III, Unidade de acolhimento adulto, Unidade de acolhimento infanto-juvenil, Comunidade terapêutica, Serviço de residência terapêutica, Ambulatório de saúde mental, Leitos especializados em hospital geral, Hospital psiquiátrico, SAMU, Hospital - Dia
 
### Observações
Demanda solicitada à partir do Projeto Vidas Preservadas - Ministério Público.

**Comment by fernandafnascmnt** [comment]
@luannaalves com relação a estes espaços que estão somente com a sigla, é para adicionar tal e qual está escrito?
UBS
NASF

com relação a estes espaços será adicionado assim mesmo ou são 3 separados ?
CAPS geral I, II, III
CAPS AD I, II, III

**Comment by uira** [comment]
@FernandaNascimento26 Gente, isso aqui precisa passar por um refinamento com o DesignLab. 

impacta diretamente na nossa arquitetura da informação e também no UX writing da aplicação. 

surgiro marcarem um refinamento com @Matheuscpl e @ClarisCaval, Luanna Araujo e @FeNasciment

**Comment by fernandafnascmnt** [comment]
Finalizada! Aguardando aprovação da @luannaalves

**Comment by RaniGub** [comment]
Gente, por gentileza, reabrir a issue e adicionar uma tarefa para o DesignLab adicionar desses campos no mapeamento da AI do Mapa da Saúde. Farei o apontamento quando for concluído.
