### ISSUE TITLE
Resolver Bugs relacionados a Categorias e Especialidades Profissionais

### ISSUE THREAD

**Issue by FernandaNascimento26** [FeliciLab/mapadasaude#375]
### Objetivo
**Como** usuário do Mapa da Saúde
**Quando** for adicionar ou editar categoria / especialidade profissional
**Então** o processo deve acontecer sem erros, e após finalizado deve exibir as opções selecionadas

### Escopo

Durante a oficina com o Ministério público, observaram os problemas: 
Quando inclui uma especialidade ele apresenta outra aleatória que não a selecionada (saúde mental -> apresentou auditoria) 

### Critérios de Aceitação
- [ ] Exibir a especialidade e/ou categoria selecionada sem erros

### Observações

**Comment by fernandafnascmnt** [comment]
Resolvido.

**Comment by Junior-Shyko** [comment]
Ajustado no banco.

**Comment by luannaalves** [comment]
Conferido na produção. O bug foi resolvido, quando se adiciona uma especialidade e categoria então esta é salva conforme escolhido. Porém, após resolução os itens adicionados recentemente pela issue 369 desapareceram.
