### ISSUE TITLE
Atualizar a versão do Mapa da saúde

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#406]
### Objetivo
Como desenvolvedor do Mapa da Saúde
Quando utilize o sistema
Então devo encontrar uma versão atualizada

### Escopo
Mediante pareamento com a equipe do Hacklab, desenvolvedora do sistema inicial do Mapa, foi identificado que na nova versão disponibilizada pelo Hacklab, já consta correção de alguns bugs que dificultam o atual desenvolvimento do nosso sistema Mapa da saúde. Portanto, é imprescindível que seja feita a atualização da homologação do Mapa da saúde para a nova versão disponível pelo Hacklab.

### Critérios de Aceitação
 - [ ] Atualizar versão do Mapa da Saúde
 - [ ] Realizar testes após atualização de versão

**Comment by vicmagpac** [comment]
Nos testes realizados para atualização da nova versão do mapas, para que funcione deve usar o composer.json e composer.lock do projeto já existente, pois se realizar a atualização para alguma versão mais nova por exemplo do doctrine, acontece problemas de classes não existentes como por exemplo 

> Class '\Doctrine\Common\Cache\ApcuCache' not found

Outro problema encontrado na nova versão do mapas é referente ao JWT, como o keycloak necessita do JWT, então na atualização para a versão mais nova como por exemplo a 4.0, retorna erro da classe JWT não encontrada possivelmente devido ao namespace não especificado.

Os dois arquivos de atualização devem ser:
https://github.com/EscolaDeSaudePublica/mapadasaude/blob/main/src/protected/composer.json
https://github.com/EscolaDeSaudePublica/mapadasaude/blob/main/src/protected/composer.lock

**Comment by vicmagpac** [comment]
Problema no tema:

arquivo src/protected/application/themes/Saude/layouts/parts/singles/opportunity-about.php
inserindo o arquivo: <?php $this->part('singles/opportunity-registrations--importexport', ['entity' => $entity]) ?>entretanto o arquivo não existe no tema

**Comment by vicmagpac** [comment]
Teste no formulário de oportunidade na nova versão, 
![Capturar36.PNG](https://images.zenhubusercontent.com/60a700715abeb69728eb42ba/9426d8a1-8113-40a6-a842-4a3debcb8c50)

O erro apresenta a seguinte mensagem: Data final obrigatória caso data inicial preenchida
Entretanto a data foi informada como consta na imagem acima.

**Comment by vicmagpac** [comment]
> Teste no formulário de oportunidade na nova versão,
> ![Capturar36.PNG](https://camo.githubusercontent.com/2704b1ee9537d187cdb81b7fae4aee25710190ef9198c6b258164091f2095889/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630613730303731356162656236393732386562343262612f39343236643861312d383131332d343061362d613834322d346133646562636238633530)
> 
> O erro apresenta a seguinte mensagem: Data final obrigatória caso data inicial preenchida
> Entretanto a data foi informada como consta na imagem acima.

Devido as mudanças nos controllers, BaseV1 (split de arquivos), o tema da saúde está baseado na versão 5.0.0, a versão atualizada 5.1.6 mudou a estrutura e consequentemente o contrato que existia na versão 5.0.0 com o tema não existe mais em alguns pontos da aplicação, principalmente no gerenciamento de oportunidades.

**Comment by vicmagpac** [comment]
Depois de desabilitar o layout parts do tema para buscar do BaseV1 e realizar a inscrição em uma oportunidade retorna a seguinte mensagem:
![Capturar-erro-insert-inscrito](https://user-images.githubusercontent.com/3487411/130650895-d33530ff-fbdf-4497-a471-9da62ff66b3f.PNG)

**Comment by vicmagpac** [comment]
> Depois de desabilitar o layout parts do tema para buscar do BaseV1 e realizar a inscrição em uma oportunidade retorna a seguinte mensagem:
> ![Capturar-erro-insert-inscrito](https://user-images.githubusercontent.com/3487411/130650895-d33530ff-fbdf-4497-a471-9da62ff66b3f.PNG)

Ao desabilitar os arquivos js do angular no tema funciona.

**Comment by vicmagpac** [comment]
Na nova versão 5.1.6 os arquivos de upload para os inscritos continuam mostrando a mensagem "Arquivo não enviado" como consta na imagem abaixo:

![Capturar-erro-insert-inscrito2](https://user-images.githubusercontent.com/3487411/130653465-d94d1bc7-f75a-46b9-8396-d808d133795d.PNG)

**Comment by vicmagpac** [comment]
Ao realizar a instalação de uma nova instância sem o tema mapa da saúde, ou seja usando o tema SpCultura todo o fluxo de editais funciona bem.  Desde 1 ou várias etapas com anexos de arquivos, usando o comando 
`./dev-scripts/start-dev.sh` para instalar e executar o mapasculturais.

**Comment by vicmagpac** [comment]
Teste realizado com a versão 5.1.11, o principal conflito é o tema da Saude. Passos realizados:

- Downgrade da versão composer e lock
https://github.com/EscolaDeSaudePublica/mapadasaude/blob/main/src/protected/composer.json
https://github.com/EscolaDeSaudePublica/mapadasaude/blob/main/src/protected/composer.lock

- Refazer configuração do Keycloak adicionando o arquivo OpauthKeyCloak.php dentro do diretório src/protected/application/lib/MapasCulturais/AuthProviders. Em seguida baixar o keycloak no vendor opauth

- Adicionar o tema Saúde e em seguida renomear ou remover o diretório "singles" em src/protected/application/themes/Saude/layouts/parts/ para que o mapas busque o dados do BaseV1

- Renomear ou remover JS do tema em src/protected/application/themes/Saude/assets para que o mapas busque o dados do BaseV1
 
Teste realizado com 2 fases e submissão de arquivos.

**Comment by vicmagpac** [comment]
Relato Atualização 5.0.0 -> 5.1.11

Passos para atualização

`git clone https://github.com/EscolaDeSaudePublica/mapadasaude.git`
`cd mapadasaude`
`git remote add mapasculturais https://github.com/mapasculturais/mapasculturais.git`
`git fetch --all`
`git merge v5.1.11`

Em seguida resolver os conflitos

- Baixar o tema na branch https://github.com/EscolaDeSaudePublica/Saude/tree/feature/compatibilidade-versao-5.1.11 e executar o build.

O testes realizados na versão foram, criar projeto, criar oportunidade, fazer login com id saúde, atualizar oportunidade com 1 inscrição e a segunda fase avaliação técnica e o restante do fluxo ok. Entretanto as melhorias de layouts feitas foram excluídas da branch informada acima.

**Comment by vicmagpac** [comment]
Relato nova atualização 5.0.0 -> 5.1.11

Passos para atualização

`git clone https://github.com/EscolaDeSaudePublica/mapadasaude.git`
`cd mapadasaude`
`git remote add mapasculturais https://github.com/mapasculturais/mapasculturais.git`
`git fetch --all`
`git merge v5.1.11`

Em seguida resolver os conflitos

- Baixar o tema na branch https://github.com/EscolaDeSaudePublica/Saude/tree/feature/compatibilidade-versao-5.1.11 e executar o build.

Passos para testes das oportunidades

- [x] 1. Autenticação ID Saúde usuário responsável pela oportunidade
- [x] 2. Criação do Projeto
- [x] 3. Criação da oportunidade com 2 fases
- [x] 4. Fase 1 inscrição
- [x] 5. Fase 2 com gerenciamento de datas e submissão de anexos
- [x] 6. Inscrição na fase 1
- [x] 7. Fechamento da fase 1 e aprovação dos selecionados
- [x] 8. Publicação de resultado
- [x] 9. Importação na segunda fase dos inscritos selecionados da primeira fase
- [x] 10. Acesso pelo inscrito na segunda fase
- [x] 11. Acesso pelo inscrito na segunda fase e submissão de arquivos
- [x] 12. Fechamento da segunda fase

Observação: As alterações realizadas foram enviadas para um repositório pessoal, para realizar os testes mais refinados e em seguida atualizar o mapa da saúde https://github.com/victorMagalhaesPacheco/mapadasaude
A branch para merge do mapa da saúde deve ser a main, pois a branch develop tem muitas atualizações no próprio core do mapas o que sobreescreve as atualizações da versão mais nova, como a versão MAIN não foi atualizada baseada na develop então funciona bem nos testes realizados para o repositório informado acima.
