### ISSUE TITLE
Criar api para o SACS e fornecer endpoint de inscritos para o Mapa

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#428]
### Objetivo
Como desenvolvedor do Mapa da Saúde
Quando acesse o sistema do Mapa da saúde
Então quero encontrar as informações migradas pelo sistema SACS

### Escopo
Deverá ser migrada as informações das pessoas que estão cadastradas no sistema SACS - ESP (em torno de 30.000 cadastros), sendo portanto necessário habilitar esta integração dentro do Mapa.
O Mapa atualmente possui uma api para realizar o cadastro via api dos agentes, porém é necessário realizar os testes dentro do Mapa, para verificar se esta api está recebendo o cadastro destes agentes. Uma vez implementada essa api dentro Mapa, deverá ser possível utilizar essa mesma api para integração com os demais sistemas.

### Critérios de Aceitação
- [ ] Criar api genérica para o SACS e fazer requisição para envio de informações para o Mapa

**Comment by vicmagpac** [comment]
API do SACS criado com sucesso retornando a seguinte estrutura:

```json
[
  {
    "codigo": 1,
    "lattes": 12443242,
    "cpf": "000.000.000-00",
    "rg": "00000",
    "nome": "NOME PESSOA",
    "cidade": "Fortaleza",
    "estado": "Ceará",
    "nmsexo": "FEMININO",
    "naturalidade": "FLORIANO",
    "nacionalidade": "BRASILEIRO",
    "datanascimento": "2000-01-01",
    "telefone1": "(86)00000-0000",
    "telefone2": "(88)0000-0000",
    "telefone3": null,
    "email": "mail@mail.com",
    "logradouro": "LOGRADOURO",
    "numero": 000,
    "complemento": "0000",
    "bairro": "BAIRO",
    "cep": "000000-000"
  },
 ...
]
```

API no ambiente de homologação.
