### ISSUE TITLE
Realizar Estudo de Integração com Base de dados CNES

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#433]
### Contexto
Realizar integração com a base de dados do CNES, com intuito de migrar informações dos profissionais já cadastrados para o banco de dados do Mapa da Saúde.

### Escopo
Necessário realizar estudo da forma que será integrado o Mapa da saúde com o CNES. A forma disponível atualmente, é via webservice e via csv. 
Contudo, a integração pelo Webservice é limitada a apenas 10.000 requisições para o webservice do CNES de forma contínua. Ou seja, para integrar todo o quantitativo de profissionais de saúde cadastrados, que são mais de 120 mil, não é possível através deste webservice devido às limitações do próprio sistema CNES.
Outra forma seria através de um arquivo baixado no site do CNES, onde o mesmo retorna todos os profissionais de um período, entretanto, os dados contidos no csv são insuficientes (não contém CPF).
Com isso, é necessário realizar um estudo para avaliar a melhor forma de integração com o CNES para atualizar em tempo real os dados dos profissionais e instituições do Estado do Ceará.

Sugestões para análise e estudo:
  - Utilizar a RNDS - Rede Nacional de Dados em Saúde

### Critérios de Aceitação
- [ ] Realizar análise do serviço que irá fornecer os dados 

### Observações

Analisar documentos abaixo:
https://rnds-guia.saude.gov.br/docs/passo-a-passo

https://documenter.getpostman.com/view/2163377/TVRd9Wad#fe7f8da3-dee2-4769-a71a-eaf89501d644

**Comment by ricardopoppi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/mapadasaude/433?planning-poker) with ZenHub @JesseOliveiraUFC @victorMagalhaesPacheco @andersondantas81 @nestorufpe
