### ISSUE TITLE
Implementar rotina de atualização do CNES via integrador do Mapa da Saúde

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#435]
### Contexto
Realizar integração com a base de dados do CNES, com intuito de migrar informações dos profissionais já cadastrados para o banco de dados do Mapa da Saúde.

### Escopo
Após realização do estudo e definição do serviço de fornecimento dos dados pelo CNES para o Mapa da saúde, deverá ser implementada rotina de atualização destes dados através do integrador criado para o Mapa da Saúde.

### Critérios de Aceitação
- [ ] Implementar rotina de atualização via integrador do Mapa da Saúde
- [ ] Definir periodicidade de atualização

**Comment by vicmagpac** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/mapadasaude/435?planning-poker) with ZenHub @JesseOliveiraUFC @andersondantas81 @nestorufpe

**Comment by ricardopoppi** [comment]
deprecada pela issue #730
