### ISSUE TITLE
Criar Gitbook para Tutoriais do Mapa da Saúde

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#440]
### Objetivo
Como usuário do Mapa da Saúde
Quando necessite de tutoriais para utilização do Mapa
Então já quero encontrar disponível na internet

### Escopo
Deverá ser criado Gitbook para o Mapa da saúde, para que possa ser adicionado tutoriais de uso da ferramenta e disponibilizado na web ao usuário. Deverá ser revisado o tutorial **Como criar seu Agente** , para deixá-lo de forma mais didática e posteriormente transformá-lo para o formato do Gitbook.

### Critérios de Aceitação
- [ ]  Criar Gitbook para Tutoriais do Mapa da Saúde
- [ ]  Revisar tutorial Como criar seu Agente e transformá-lo para o formato do Gitbook

### Observações
[Tutorial Criando seu Agente](https://www.esp.ce.gov.br/wp-content/uploads/sites/78/2021/07/Criando-seu-Agente-da-Saude-no-Mapa-Digital-da-Saude-1.pdf)

[Modelo Gitbook Mapas culturais](https://cultura-ceara.gitbook.io/tutorial-para-o-usuario-do-mapa-cultural/)

**Comment by fernandafnascmnt** [comment]
https://mapa-da-saude.gitbook.io/manual-mapa-da-saude/

Gitbook criado e inserido o tutorial Como criar seu Agente.

Aguardando feedbacks e melhorias!

**Comment by vicmagpac** [comment]
@FernandaNascimento26 Que lindo 😻

**Comment by uira** [comment]
@FernandaNascimento26 Importante um olhar do @Matheuscpl sobre esse conteúdo. 

Também vale conversar com o André, do IDM, sobre esse manual.

Não entendi se estamos customizando o manual da secult ou se estamos criando o nosso do zero.
