### ISSUE TITLE
BUG. Ao criar uma oportunidade estava sendo criada várias outras novas oportunidades

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#445]
### Objetivo
Como administrado de uma oportunidade no Mapa da Saúde
Quando estou criando uma oportunidade com outras fases
Então o sistema estava criando várias outras oportunidades em branco

### Escopo
Foi identificado, através de testes de criação de uma oportunidade, que ao criar novas fases para uma oportunidade, estava ocorrendo um bug de criação de várias outras oportunidades em branco. 

Como replicar o erro:
- Criar um Projeto Pai no Menu de Projetos;
- Criar um subprojeto dentro deste Projeto Pai;
- Criar uma oportunidade dentro deste Subprojeto;
- Criar novas fases dentro desta oportunidade;
- Identificar se ocorre o bug novamente.

### Critérios de Aceitação
 - [x] Corrigir bug de criação de oportunidades em branco não inseridas pelo administrador

### Observações

![image.png](https://images.zenhubusercontent.com/61003068ef5298ed706152a1/cdd5c98b-1d14-4a44-9ceb-77a0d18cee79)

**Comment by ericsonmoreira** [comment]
Em meus testes, verifiquei em esse bug não está acontecendo.
