### ISSUE TITLE
BUG. A página principal de uma oportunidade está apresentando erro na ordenação das fases

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#446]
### Objetivo
Como administrado de uma oportunidade no Mapa da Saúde
Quando estou criando uma oportunidade com outras fases
Então o sistema estava ordenando as fases seguintes aleatoriamente e não na sequencia criada 

### Escopo
Foi identificado, através de testes de criação de uma oportunidade, que ao criar novas fases para uma oportunidade, estava ordenando as fases aleatoriamente e não na sequência das fases criadas. Por exemplo, a terceira fase estava aparecendo no meio, entre a primeira e a segunda fase.

### Critérios de Aceitação
- [ ] Corrigir bug de ordenação das fases de uma oportunidade

### Observações

**Comment by ericsonmoreira** [comment]
Não consegui replicar o erro.
