### ISSUE TITLE
Revisão de Fluxo de Gerenciamento de Oportunidades (Avaliação, Recursos e Resultados)

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#447]
### Objetivo
Como administrador de uma oportunidade no Mapa da Saúde
Quando crie gerencie uma oportunidade dentro do Mapa
Então devo encontrar um bom fluxo para gerenciamento desta oportunidade.

### Escopo
Deverá ser revisto todo o fluxo de gerenciamento de uma oportunidade dentro do Mapa da saúde. Analisando as etapas de Avaliação, análise e resposta de recurso de um candidato e recebimento e divulgação das notas.

### Critérios de Aceitação
[ ]

Observações
Deverá passar pela análise do UX Design.

**Comment by RaniGub** [comment]
@matheuscpl as jornadas se relacionam a:
1- Pessoa que vai criar/gerir a oportunidade, considerando a publicação dos resultados;
2- Pessoa vai se inscrever numa oportunidade, considerando a visualização dos resultados e recursos (card #454);
3- Pessoa que vai avaliar uma oportunidade, considerando os critérios de avaliação e resposta aos recursos;

Todas no ambiente de homologação.

**Comment by RaniGub** [comment]
Bom dia @matheuscpl , coloque o link do Figma no Escopo para que eu e o @uira consigamos acompanhar a evolução da tarefa.
