### ISSUE TITLE
Permitir que o administrador possa excluir uma oportunidade

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#451]
### Objetivo
Como administrador de uma oportunidade no Mapa da Saúde
Quando queira excluir uma oportunidade criada
Então devo encontrar um botão para exclusão desta oportunidade.

### Escopo
Atualmente, não é possível que o administrador de uma oportunidade exclua uma oportunidade já criada, sendo necessário solicitar a exclusão ao desenvolvedor no banco de dados. Portanto, deverá ser possível que o administrador da oportunidade possa excluí-la.

Critérios de Aceitação
[ ]

Observações
Deverá passar pela análise do UX Design.

**Comment by RaniGub** [comment]
@matheuscpl você pode indicar o link do Figma para essa solução?

**Comment by thaistoscano** [comment]
@RaniGub para revisão

**Comment by thaistoscano** [comment]
@luannaalves e @thaistoscano revisão
