### ISSUE TITLE
Mudança de nomeclatura de Agentes para Pessoas e Espaços para Unidades

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#457]
### Objetivo
Como usuário do mapa da Saúde
Quando acesse a plataforma
Então deverei encontrar as informações de Pessoas, ao invés de Agentes e Unidades ao invés de Espaços

### Escopo
Deverá ser trocada a nomeclatura atual de Agentes para **Pessoas** e de Espaços para **Unidades**. Essa alteração deverá ser feita em todos os locais da plataforma onde apareçam estes nomes de agentes e espaços. Deverá ser pareado com o Rafael - Hacklab, como realizar essa alteração.

### Critérios de Aceitação
- [ ] Alterar a nomeclatura de agentes para Pessoas, em todos os locais na plataforma em que apareçam esse nome.
- [ ] Alterar a nomeclatura de espaços para Unidades, em todos os locais na plataforma em que apareçam esse nome.

### Observações

**Comment by vicmagpac** [comment]
Em análise no tira dúvidas com o hacklab sobre a alteração dos termos AGENTE para PESSOAS e ESPAÇOS para UNIDADE, verificou se que a alteração constando atualmente no mapas, não é aplicado e mudar em todos os lugares onde é chamado os termos informados acima.  Abaixo existem duas soluções possíveis apresentadas pelo hacklab:

Opção 1 - Usar o dicionário do mapas dentro do tema - (necessário refatorar)
Opção 2 - Utilizar o POEDIT para realizar a traduçãor - (necessário refatorar)

O ideal é usar de fato o POEDIT, Rafa informou que o arquivo pt_BR.po deve ser montado pelo container pelos volume do dockers e não devem ser visionado no core do mapas.
O arquivo pt_BR.po deve ficar em mapadasaude\src\protected\application e versionado em um repositório separado.

Observação: o Arquivo pt_BR.po deve ser atualizado, pois existem várias strings que estão em espanhol. Necessário verificar 100% do arquivo.

**Comment by vicmagpac** [comment]
O arquivo pt_BR.po foi enviado para o grupo hacklab/ + Escola de Saúde Pública. Não será feito o upload nos comentário do github, pois o mesmo não permite a extensão.

**Comment by thaistoscano** [comment]
Fazer após a revisão da arquitetura.

**Comment by uira** [comment]
@thaistoscano pra cima deles, @RaniGub 🚀🚀🚀

**Comment by RaniGub** [comment]
@thaistoscano precisamos conversar sobre esse card.

**Comment by RaniGub** [comment]
@thaistoscano no item 1, de 'Pontos a Considerar' desse relatório https://docs.google.com/document/d/1mVUm-M_T4lP0a46IrVesbD42fVwbBmXdUCbIX_i-NbY/edit sugeri ao Uirá que a palavra 'Espaços' se mantenha generalizada para o Mapa e 'Instituições', da aba 'Indicadores', seja modificada para 'Espaços de Saúde' (Issue #517, já conversado com você). Então o tópico dessa tarefa que fala para substituição de Espaços por Unidades, entra em conflito com isso. Ainda não cheguei a analisar essa parte da taxonomia do Mapa porque estou no fluxo de cadastro integrado. Quando eu chegar nessa parte lhe aviso.
