### ISSUE TITLE
Permitir vincular as seções de critérios de avaliação a perfis diferentes dentro de uma mesma oportunidade

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#460]
### Objetivo
Como administrador do mapa da Saúde
Quando crie uma oportunidade
Então devo ter a possibilidade de vincular seções de avaliação técnica à diferentes perfis dentro de uma mesma oportunidade

### Escopo
Deverá ser identificado junto à equipe do Hacklab uma possibilidade de vincular determinadas seções de avaliação técnica a diferentes perfis dentro de uma mesma oportunidade. Atualmente, o sistema do mapa , se inserido vários quadros de avaliação tecnica, não permite separar estes quadros para determinados perfis, pois ele considera todos os quadros para todos os perfis inseridos, e isso está impossibilitando lançar um edital com vários perfis dentro de uma mesma oportunidade.

### Critérios de Aceitação
- [ ] Permitir vincular as seções de critérios de avaliação a diferentes perfis dentro de uma mesma oportunidade

Observações

**Comment by vicmagpac** [comment]
Atividade iniciada na branch: https://github.com/EscolaDeSaudePublica/mapadasaude/tree/feature/n-perfis-n-secoes baseada na https://github.com/EscolaDeSaudePublica/mapadasaude/tree/feature/modelo-avaliacao-esp (merge)

Observações

- A atividade está sendo pareada em conjunto com o Rafael do hacklab, as implementações foram feitas dentro do plugin de avaliação técnica acordado com o Rafa, para que possa servir para outras instâncias.
- Os commits não estão vinculados a issue devido o fato de que começamos primeiro a implementação e em seguida a mesma foi priorizada pelo P.O do mapa da saúde
