### ISSUE TITLE
Permitir impressão de certificados a partir do Mapa

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#462]
### Objetivo
Como usuário candidato
Quando esteja participando de uma oportunidade dentro do Mapa
Então devo ter opção de receber e emitir um certificado pelo próprio Mapa

### Escopo
Deverá ser inserido dentro do mapa opção de um usuário participante de uma oportunidade, receber um certificado dentro do Mapa e poder imprimir.

### Critérios de Aceitação
- [ ] Criar selo referente ao evento para geração do certificado
- [ ] Permitir que o administrador da oportunidade vincule aos candidatos seus respectivos certificados através dos selos
- [ ] Permitir o candidato imprimir este certificado através do selo

Observações
Deverá passar pela análise do UX Design.

**Comment by vicmagpac** [comment]
Nova atualização de mapeamento de volumes:

1. Criar diretório na raiz local do projetos chamado "themes"
2. Criar diretório na raiz local do projetos chamado "plugins"
3. O tema saúde fica dentro de themes da raiz e não mais no core 
`mkdir themes` 
`mv src/protected/application/themes/Saude themes/` 
ao final da execução do comando o tema Saude deve sair do core e entrar na raiz que não está versionada.
4. Realizar mapeamento dentro do docker compose para mapear o volume para dentro do container 
`- ./themes/Saude:/var/www/html/protected/application/themes/Saude`
