### ISSUE TITLE
Rever texto do ID Saúde 

### ISSUE THREAD

**Issue by matheuscpl** [FeliciLab/mapadasaude#463]
## **Objetivo**

**Como** usuário do mapa
**Quero** fazer uma inscrição
**Para** participar de uma oportunidade

## **Contexto**
Atualmente no Mapa da Saúde não está de fácil compreensão que ao criar o cadastro no Mapa da Saúde o usuário vai cair no ID saúde e a função deste. Dessa forma, precisamos tornar claro esse processo. 

## **Escopo**

- [x] Criar textos do ID Saúde (página principal) e página de concessão de autorizações.

## **Critérios de Aceitação**
- [x] Criar texto de entrada no ID Saúde
**Dado que** Quero criar login no Mapa da saúde
**Quando** caio no ID Saúde
**então** tenho uma explicação consistente do que ele é e sua funcionalidade

![Screenshot_162.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/05287060-0aab-4fd1-9586-d5aab5097fcd)

**01** - 32 caracteres
**02** - 125 caracteres

- [x] Página de concessão de autorização
**Dado que** Fiz o cadastro no ID Saúde
**Quando** são solicitadas as autorizações/concessões necessárias
**então** tenho uma explicação consistente do que ele é e para que a permissão

![Screenshot_163.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/311fffeb-b860-43d9-ae78-e441f931318e)

**03** - 32 caracteres
**04** - 125 caracteres
**05** - 798 caracteres

# Observações

Protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=793%3A538

**Comment by RaniGub** [comment]
@matheuscpl você sabe falar se essa tarefa tem conexão com a #304 - Repensar o Fluxo de Cadastro?

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/463?planning-poker) with ZenHub @victorMagalhaesPacheco @FernandaNascimento26 @Junior-Shyko @pedrovitor074 @lucastandy

**Comment by thaistoscano** [comment]
@Clarisse1983 Fará a elaboração dos textos.

**Comment by RaniGub** [comment]
@matheuscpl editou o escopo e sugeriu onde o texto deveria estar.

**Comment by thaistoscano** [comment]
![image.png](https://images.zenhubusercontent.com/6140f6973ff8904a055e7b0e/a78ace06-499e-4e94-89a2-910a66d76052)

**Comment by thaistoscano** [comment]
![image.png](https://images.zenhubusercontent.com/6140f6973ff8904a055e7b0e/d9b4035d-8ed8-4617-930e-fbc19eba74f3)

**Comment by thaistoscano** [comment]
@RaniGub Avaliar previsão de caracters.

**Comment by RaniGub** [comment]
Oi @matheuscpl por favor, verifica a experiência adequada para as duas situações e dá uma projeção da quantidade de caractere para cada uma blz? Obg.

**Comment by matheuscpl** [comment]
@RaniGub Bom dia, adicionei a contagem de caracteres

**Comment by Junior-Shyko** [comment]
Aguardando os textos para add ao tema.

**Comment by Junior-Shyko** [comment]
![image.png](https://images.zenhubusercontent.com/61092b9464d7502ba0e520b9/f7b20362-380f-4b59-898a-1d47cfe9c089)

Esse texto ao cadastrar é o mesmo texto que aparece no login. Se tiver como ser um texto genérico para os dois momentos, seria ótimo.

**Comment by Junior-Shyko** [comment]
https://docs.google.com/document/d/1l2FVCBLlphCfdr3JEYKY51iQSdaGnvt_Q836T75DTcA/edit#heading=h.fh6100fgebjw

**Comment by uira** [comment]
@Junior-Shyko já  é!

**Comment by Junior-Shyko** [comment]
> @Junior-Shyko já é!

ok, já havia até iniciado com esse texto mesmo.

**Comment by Junior-Shyko** [comment]
Nessa mesma atividade vai ter o link para o TERMOS E USO do mapa? saberia me informar @uira , @thaistoscano , @matheuscpl ?

**Comment by Junior-Shyko** [comment]
PR realizado no repositório do ID Saúde: https://github.com/EscolaDeSaudePublica/IdentidadeUnicaDeSaude/pull/61
