### ISSUE TITLE
Diminuir o tempo do PCACHE na homologação e produção

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#464]
### Objetivo
Como usuário do Mapa da saúde
Quando esteja acessando o Mapa
Então devo ter acesso rápido de atualização das informações

### Escopo
Deverá ser diminuído o tempo de PCACHE para 10segundos, no ambiente de homologação e produção, para que quando o usuário acesse ou insira novas informações o tempo de resposta da atualização seja mais rápido.

### Critérios de Aceitação
- [x] Diminuir o tempo do PCACHE na homologação e produção

Observações

**Comment by vicmagpac** [comment]
Atividade realizada em homologação adicionando 5 segundos do PCACHE
