### ISSUE TITLE
Ajustar para quando título de uma fase for extenso não sobreponha ao botão de adicionar fase.

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#477]
### Objetivo

**Como** administrador de uma oportunidade no Mapa da Saúde
**Quando** insira o título de uma oportunidade extenso
**Então** não devo encontrá-lo sobrepondo ao botão de adicionar fase.

### Escopo

Atualmente, quando é inserido um título extenso para uma oportunidade, esse título está sobrepondo ao botão de Adicionar fase, estes campos deverão ser ajustados para que não sobreponham um ao outro.

### Critérios de Aceitação

- [x] Ajustar o layout do `componente` que contém o botão de adicionar nova fase para que ele não seja sobreposto por outros elementos contidos no _card_.
- [x] O botão deve permanecer no canto direito inferior. 

Observações
Deverá passar pela análise do UX Design.

**Comment by matheuscpl** [comment]
Revisão de UX: Tudo certo! :)

![Screenshot_96.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/e0957fd7-7e52-4fe7-9909-3b5baeb519da)
