### ISSUE TITLE
Atualizar o ambiente de desenvolvimento do Mapa da Saúde

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#491]
## **Objetivo**

**Como** Desenvolvedor do MapadaSaude  
**Quero** Configurar o meu ambiente de desenvolvimento
**Para** Habilitar o log de Hooks

## **Contexto**

- Em pareamento com a equipe do Hacklab, ocorreu a atualização em alguns arquivos do Mapa da Saúde para que fossem exibidos os logs dos Hooks, bem como fosse utilizada a configuração de ambiente desenvolvida pelo Hacklab (contida no diretório dev-scripts)

## **Escopo**

Os arquivos alterados foram:

- **docker-compose** do dev-scripts; 
- **entrypoint.sh** do compose (Neste, foi adicionado a segunda parte da verificação de atualização para que o db-updates só seja executado se houver uma mudança de versão do banco);
- no **config.local** foi habilitado o log dos hooks (isto para o caso de rodar o ambiente com o ```./start-dev.sh```

## **Fora de Escopo**
Para verificar as configurações aplicadas, após atualizar o ambiente de desenvolvimento, siga o passo a passo: 

- 1 - Entrar no diretório ```mapadasaude/dev-scripts``` e executar o comando: ```./start-dev.sh``` ;
2 - Após o mapa subir, devem aparecer os logs de todos os hooks do Mapa; 
3 - Caso deseje executar um hook específico, deve acessar novamente o arquivo **config.local**  e na linha que contém: `app.log.hook  => true`, deverá substituir o **true** pelo nome que remeta ao seu hook (exemplo: `'app.log.hook'          => 'claim'` , apresentará apenas os hooks que contém claim);

## **Critérios de Aceitação**

- [x] Logs de Hooks habilitados
**Dado que** aplique as alterações sugeridas nesta Issue
**Quando** executar (subr) o ambiente de desenvolvimento por meio do dev-scripits; 
**então** no terminal deve aparecer os logs dos Hooks

# Observações

ex: Prototipo

**Comment by fernandafnascmnt** [comment]
Essa Issue foi contemplada no PR #490

**Comment by fernandafnascmnt** [comment]
![Captura de tela de 2021-09-21 09-25-04](https://user-images.githubusercontent.com/44043740/134169902-8eac5c69-d507-4074-90ba-be0221fb3a87.png)
