### ISSUE TITLE
Alterar formatos e quantidade de anexos permitidos

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#492]
## **Objetivo**

**Como** usuário realizando inscrição
**Quero** anexar inúmeros arquivos de diferentes formatos
**Para** comprovar as pontuações de itens solicitados por meio do edital

## **Contexto**
Atualmente o Mapa aceita somente um arquivo por campo, bem como sugere em "zip". Deve ser alterado para que suporte diversos arquivos (pdf até 5 mega, jpeg, png, xls, ppt, vídeos até 300MB...)
-

## **Escopo**

Atualizar quantidade de campos e formatos aceitos. Se por exemplo possuo comprovação de experiência na área posso inserir inúmeras páginas da CLT para essa comprovação. Obs: É a solicitação do GTCesp que o participante não tenha que gerar PDF compilado, pois limitaria a participação de diversos agentes.

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Sejam criados inúmeros campos para cada comprovação (Mín 20 campos para cada comprovação)
- [ ] Sejam aceitos diversos formatos (pdf, jpeg, png, xls, ppt, vídeos até 300MB... )

**Dado que** Acesso a página de inscrição em uma oportunidade
**Quando** faço  o envio de inúmeros arquivos que comprovem a pontuação que possuo
**então** consigo comprová-la

# Observações

ex: Verificar quais outros formatos também são compatíveis e também seriam funcionais para download e análise da banca.

**Comment by vicmagpac** [comment]
Em conversa de análise com o Rafa do HACKLAB sobre permitir múltiplos uploads por campos não existem atualmente no mapas, ou seja a aplicação aceita um campo que pode ser usando zip ou pdf.

**Comment by thaistoscano** [comment]
Atividade foi inserida em nova proposta. Contemplada na issue https://app.zenhub.com/workspaces/mapa-da-sade---refinamento-610039a15670a0000e67211f/issues/escoladesaudepublica/mapadasaude/584
