### ISSUE TITLE
Corrigir bug da avaliação simplificada pelo avaliador

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#495]
## **Objetivo**

**Como** Avaliador de uma oportunidade no mapa da saúde
**Quero** aplicar as avaliações para as inscrições do tipo simplificada e documental
**Para** realizar a avaliação dos inscritos e prosseguir com o acompanhamento padrão da oportunidade

## **Contexto**

- Atualmente no momento de avaliação de uma oportunidade do tipo simplificada e documental por parte do avaliador, o sistema retorna um erro no momento de avaliar. Isso acontece pois foi adicionado um trecho de código de validação para o tipo de oportunidade de avaliação técnica, entretanto quando o tipo é simplificada ou documental, o mesmo quebra.

## **Escopo**

- [ ] Realizar avaliação das inscrições independentemente do tipo de avaliação na oportunidade, seja ela técnica, documental ou simplificada

## **Fora de Escopo**

- Não se aplica

## **Critérios de Aceitação**

- [ ] Realizar avaliação pelo avaliador para a fase do tipo simplificada, técnica ou documental
**Dado que** sou um avaliador e vou avaliar os inscritos de uma oportunidade
**Quando** realizo o preenchimento do formulário de avaliação
**então** clico no botão de finalizar, o sistema deve seguir o fluxo padrão de avaliação

# Observações

O problema acontece devido ao código:

````php
$cfg = $registration->getEvaluationMethodConfiguration();
// //LOOP PARA PERCORRER TODOS OS CAMPOS PARA FAZER A COMPARAÇÃO COM A NOTA MAXIMA PERMITIDA
 foreach($cfg->criteria as $indice => $cri){
     $key = $cri->id;
     //COMPARAÇÃO DE VALOR DIGITA É MAIOR QUE O VALOR MAXIMO PERMITADO
     if(isset($this->postData['data']["{$key}"]) && $this->postData['data']["{$key}"] > $cri->max) {
         return $this->json(['message' => "O valor do campo ".$cri->title." é maior que a pontuação máxima permitida", 'status' => 'error'], 403);
     }
}
```

dentro de Registration.php

**Comment by vicmagpac** [comment]
Baseado na conversa com o Rafa do Hacklab, o ideal é adicionar a validação a partir dos hooks.

**Comment by vicmagpac** [comment]
Avaliação do tipo documental não funciona na nossa versão.
