### ISSUE TITLE
Gerar PDF com ficha de inscrição preenchida

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#496]
## **Objetivo**

**Como** usuário/agente do mapa 
**Quero** ao término da inscrição ou em qualquer outro momento resgatar do site a ficha de inscrição  
**Para** comprovação da inscrição, bem como para entrega da documentação no momento que assume a vaga.

## **Contexto**
Gerar PDF com a ficha de inscrição contendo campos de data e assinatura, com modelo similar ao que o SACS possuía. Atualmente há um botão para imprimir ficha de inscrição, mas é impressa a página que é visualizada pelo usuário e não a ficha formatada. 

## **Escopo**

Usuário possa imprimir sua ficha de inscrição após inscrito em uma oportunidade.

- [x] Corrigir a opção de endereço do AGENTE RESPONSÁVEL

## **Critérios de Aceitação**

- [x] Ficha de inscrição gerada após inscrição em modelo parecido com o anteriormente emitido pelo SACS (contendo campos da data da inscrição e campo para assinatura).

**Dado que** Tenha participado de uma oportunidade
**Quando** finalizo minha inscrição
**então** posso realizar a impressão da ficha da inscrição

## Observação
Protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1041%3A750

Rodapé da página: [https://app.zenhub.com/files/319384032/e15351f7-2601-4948-b25b-54a7f87ac1cd/download](https://app.zenhub.com/files/319384032/e15351f7-2601-4948-b25b-54a7f87ac1cd/download)

**Comment by thaistoscano** [comment]
[https://app.zenhub.com/files/319384032/ed381a4b-c600-4908-ba28-ac01c3eaad29/download](https://app.zenhub.com/files/319384032/ed381a4b-c600-4908-ba28-ac01c3eaad29/download)

**Comment by thaistoscano** [comment]
[https://app.zenhub.com/files/319384032/ad4d2d31-95f2-4c34-b45a-8b864e1c0a27/download](https://app.zenhub.com/files/319384032/ad4d2d31-95f2-4c34-b45a-8b864e1c0a27/download)

**Comment by thaistoscano** [comment]
Geração atual do mapa
[https://app.zenhub.com/files/319384032/7bc66db3-f90e-41a5-83ec-a1d636af525a/download](https://app.zenhub.com/files/319384032/7bc66db3-f90e-41a5-83ec-a1d636af525a/download)

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/496?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by Junior-Shyko** [comment]
Criado folha de estilho e rota para minhas inscrições:  [Commit](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/4158f92f37eabfda33616cc547535fa4ad0f2a6c)

**Comment by Junior-Shyko** [comment]
Add os dados da oportunidade: [Commit](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/07a3ee7d8e9222c1cf097b68e02b60c4506a0481) no repositório do Plugin

**Comment by Junior-Shyko** [comment]
Atualização com toda estrutura do plugin: [commit](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/b451ea4f49009eb6b5ae879562154ba03e1df714)

**Comment by Junior-Shyko** [comment]
Adicionado Footer: [Commit](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/a0feee120aaf7068cf154d712ce9c17fcb5aa3ea)

**Comment by vicmagpac** [comment]
Atividade implementada e adicionada em produção, atendendo o cuidar melhor. Entretanto é necessário implementar melhorias para atender a todos os tipos diferentes de configurações e campos das oportunidades.

**Comment by Junior-Shyko** [comment]
Algum cenário especifico? alguma suspeita de campos para testar?
De qualquer forma vou criar uma oportunidade com todos os campos do form build

**Comment by vicmagpac** [comment]
> Algum cenário especifico? alguma suspeita de campos para testar? De qualquer forma vou criar uma oportunidade com todos os campos do form build

@Junior-Shyko acredito que testando uma oportunidade com todos os tipos de campos possíveis no form builder do mapas, com e sem obrigatoriedade.

**Comment by Junior-Shyko** [comment]
![image](https://user-images.githubusercontent.com/7341117/143073918-0376d484-f421-4059-8d2b-ff56181b48bb.png)

- [ ] Correção da opção

**Comment by Junior-Shyko** [comment]
Atualização em:

- [x] Mascará CPF do form build (que não seja do agente resp. ou col.);
- [x] Formatar a data do form buiild (que não seja do agente resp. ou col.);
- [x] Lista de links
- [ ] Mascará telefone do form buiild (que não seja do agente resp. ou col.);
- [x] Formatar múltiplas escolhas (checkboes) da mesma forma que é **lista de nomes**
- [x] Área de atuação do Agente;
- [ ] Load enquanto a proposta é enviada
- [x] As Informações do espaço não estão vindo. (se necessário corrigir)
- [ ] Adicionar validação de link em LISTA DE LINKS

**Comment by Junior-Shyko** [comment]
[Commit ](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/96c9a1d668af702c22ad61dcfbbacbe3a7dd9e47 )com atualização nos campos de CPF, DATA, LISTA DE LINKS

**Comment by Junior-Shyko** [comment]
[Commit ](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/35f61082295cf49448679efbb62fe2e30beeb475) com atualização para exibição dos campos e os valores do form build, ag. responsável e ag. coletivo.

**Comment by thaistoscano** [comment]
https://docs.google.com/document/d/1Vsr0hT0s-X58VMRyIGvNMwv9VIddcCT9XfQ01ayvGvY/edit
Verificar documento, após refinamento passaremos a contar como critérios.

**Comment by Junior-Shyko** [comment]
> https://docs.google.com/document/d/1Vsr0hT0s-X58VMRyIGvNMwv9VIddcCT9XfQ01ayvGvY/edit Verificar documento, após refinamento passaremos a contar como critérios.

Add categorias, add condições para ag. resp. e refatorado função. [Commit] (https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/4f4780a0cd8bc078d2d5034944a033ccff0cf244)

**Comment by Junior-Shyko** [comment]
> > https://docs.google.com/document/d/1Vsr0hT0s-X58VMRyIGvNMwv9VIddcCT9XfQ01ayvGvY/edit Verificar documento, após refinamento passaremos a contar como critérios.
> 
> Add categorias, add condições para ag. resp. e refatorado função. [Commit] ([EscolaDeSaudePublica/plugin-PDFReport@4f4780a](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/4f4780a0cd8bc078d2d5034944a033ccff0cf244))

[Commit] (https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/fa4c1ee8ae90a9ddd52e7644e0691dc88620808c)

**Comment by Junior-Shyko** [comment]
[Commit ](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/d073462a7161d14943d2e9082fdb893eca39de5f) - Ocultando e mostrando campos com dependência.

**Comment by Junior-Shyko** [comment]
Refatorado agente: CPF, RG E ENDEREÇO. [Commit] (https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/e9567eb2d8a6eefec22efb5b7ccad20a76803cc1)

**Comment by Junior-Shyko** [comment]
[Commit ] (https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/5fdadf3ce5bf133a90053813fb0a19a93b19d5a1)

**Comment by Junior-Shyko** [comment]
Ordenação de campos e arquivos. [Commit] (https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/911a0d24c5f44160a4b516b5c63da14100d8d65a)

**Comment by Junior-Shyko** [comment]
Campos e arquivos ordenados devidamente no PDF. [Commit] (https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commits/feature/atualiza-campos)

**Comment by Junior-Shyko** [comment]
Refatoração para múltiplos arquivos. [Commit ](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/b1a60ea8bb22a61e271bdecb1d904619e72c8925)

**Comment by thaistoscano** [comment]
Pronto para produção.

**Comment by vicmagpac** [comment]
@Junior-Shyko os campos de anexos devem aparecer referente a categoria selecionada pelo inscrito.

**Comment by Junior-Shyko** [comment]
Mostrar seção ou campos apenas os que são pertinente a inscrição do candidato. Atualmente está mostrando todos.

**Comment by Junior-Shyko** [comment]
[Commit](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/5ecc3756a86f3de5909ac3501c499b7d6e14c843)
