### ISSUE TITLE
Possuir validação para verificar se não há outro cadastro com a mesma numeração de CPF

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#498]
## **Objetivo**

**Como** agente do mapa da saúde
**Quero** que haja validação de CPF no cadastro do agente
**Para** não haver duplicação de agentes com o mesmo CPF 

## **Contexto**
Atualmente no mapa há validação se o CPF está correto, mas aceita repetir CPF já cadastrado.

## **Escopo**

- [x] Necessário a cada cadastro buscar na base do mapa se já há cadastro com numeração igual de CPF.

## **Critérios de Aceitação**

- [x] Ao criar novo cadastro não permitir com CPF presente na base de dados
**Dado que** O agente faça um cadastro no mapa
**Quando** quer criar novo cadastro
**então** não será permitido com CPF já existente

- [x] Ao inserir CPF existente, exibir feedback ao usuário
**Dado que** O usuário crie ou edite um agente
**Quando** insira CPF já existente
**então** exibe um alerta de feedback com a seguinte mensagem "Já existe um cadastro vinculado a este CPF! Verifique se você possui outra conta no Mapa da Saúde."

- [x] Inserir máscara de CPF/CNPJ no input da modal de criação de agentes.

![Screenshot_151.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/90dbba9e-f714-4dd2-a7de-a06f0dbd51a1)

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/498?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
Aguardar a atualização da nova versão do Mapa.

**Comment by vicmagpac** [comment]
@jeff-doliveira1 alterei o comportamento do retorno do documento do keycloak para o mapa adicionando a mascara.
Segue o PR já aceito e na develop, inclusive na homologação: https://github.com/EscolaDeSaudePublica/mapadasaude/pull/718/files
