### ISSUE TITLE
Corrigir bug nos critérios das seções de avaliação técnica

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#506]
## **Objetivo**

**Como** Criador de projeto
**Quero** manter os critérios que criei em avaliação técnica na seção anterior
**Para** que preserve a informação que coloquei anteriormente

## **Contexto**
- Ao criar uma oportunidade o mapa está sobrepondo as informações da seção anterior.

## **Escopo**

- [ ] Corrigir o bug que altera as categorias criadas

## **Critérios de Aceitação**

- [ ] Preservação das informações preenchidas sem sobreposição pela seção anterior

**Dado que** Estou criando uma oportunidade
**Quando** mudo de seção 
**então** permanecem as categorias criadas

**Comment by vicmagpac** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Dev-60f894f541f910001066bfd9/issues/EscolaDeSaudePublica/mapadasaude/506?planning-poker) with ZenHub @FernandaNascimento26 @lucastandy @pedrovitor074

**Comment by thaistoscano** [comment]
Não foi possível mapear o erro.
