### ISSUE TITLE
Não permitir alteração na categoria (perfil) ao passar para fases seguintes

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#509]
## **Objetivo**

**Como** administrador de uma oportunidade
**Quero** que o inscrito não consiga mudar seu perfil/área de atuação 
**Para** que não hajam alterações após inscrição

## **Contexto**
Atualmente no Mapa é possível, após a inscrição, ao passar para as fases seguintes (ex: habilitação de currículo e plano de trabalho) alterar seu perfil escolhido.
-

## **Escopo**

- [ ] Bloquear alteração de perfil nas fases seguintes

## **Critérios de Aceitação**

- [ ] Não permitir que o usuário realize alterações no seu perfil após inscrição 

**Dado que** o usuário faça sua inscrição
**Quando** passa para as fases seguintes
**então**  não conseguirá alterar o perfil/área que está inscrito.

- [ ] Exibir feedback ao usuário 

**Dado que** o usuário esteja participando de uma inscrição
**Quando** tenta alterar seu perfil profissional
**então**  é bloqueado e recebe o alerta "Não é possível alterar o perfil profissional de uma inscrição em andamento"

Protótipo:
![Screenshot_155.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/2a20fba5-a554-490c-8cfb-70a65fa25eb4)

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/509?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
Aguardar a atualização da nova versão do Mapa.

**Comment by thaistoscano** [comment]
@RaniGub acredito que não é mais possível fazer essa alteração.

**Comment by RaniGub** [comment]
Ok @thaistoscano. Achei a sugestão adequada. Vou considerar como concluída pra gente.
