### ISSUE TITLE
Retirar a aba "inscrições" da edição de um projeto

### ISSUE THREAD

**Issue by matheuscpl** [FeliciLab/mapadasaude#512]
## **Objetivo**
**Como** administrador de um projeto no mapa
**Quero** que a aba "inscrições" não seja exibida no modo de edição
**Para** não haver um campo que não é possível editar

## **Contexto**
Para que o usuário não precisasse entrar em todos os subprojetos para visualizar as oportunidades daquele Projeto, foi criada uma aba chamada "Inscrição" na página inicial do projeto, porém esta página não possui nada a ser editado.

## **Escopo**

- Deverá ser retirada a aba "Inscrições" quando um projeto estiver em modo de edição.

## **Critérios de Aceitação**
- [x] **Remover aba Inscrições do modo de edição de um Projeto**
**Dado que** sou um administrador de um projeto
**Quando** vou editar um projeto
**então** não visualizo a aba "inscrições"

# Observações
Avaliar se ainda estará gerando problemas nos DETALHES do projeto

Previsão de tela após a conclusão da tarefa de dev:
![PROJETO2.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/4e61eabe-d26d-4b01-83a1-379f0ccfa9f6)

**Comment by RaniGub** [comment]
@matheuscpl você pode indicar o link do Figma para essa tarefa?

**Comment by matheuscpl** [comment]
Não há necessidade de protótipação.

**Comment by thaistoscano** [comment]
@RaniGub Para revisão

**Comment by luannaalves** [comment]
validado na homologação.

**Comment by luannaalves** [comment]
Validado na produção.
