### ISSUE TITLE
Remover configurações de data do projeto

### ISSUE THREAD

**Issue by matheuscpl** [FeliciLab/mapadasaude#513]
## **Objetivo**

**Como** administrador de um projeto no mapa
**Quero** que as definições de "data início" e "data fim" sejam retiradas
**Para** que as datas sejam definidas apenas nas oportunidades

## **Contexto**
Ao criar um projeto no Mapa da Saúde não há a necessidade dos campos de  Data Inicial, Data Final e Hora Final para o Projeto Pai, devendo aparecer estas informações apenas para as oportunidades.

## **Escopo**

-  No menu Meus Projetos, na aba de Detalhes, deverá ser removido os campos **Data inicial , Data final e Hora final**, quando estiver criando ou editando um projeto

## **Critérios de Aceitação**

- [x] **Remover os campos Data inicial , Data final e Hora final na aba Detalhes, na criação de um projeto**
**Dado que** sou um administrador do projeto
**Quando** vou criar um projeto
**então** não visualizo os campos de "data inicio" e "data fim"

- [x] **Remover os campos Data inicial , Data final e Hora final na aba Detalhes, na edição de um projeto**
**Dado que** sou um administrador do projeto
**Quando** vou editar um projeto
**então** não visualizo os campos de "data inicio" e "data fim"

## Observações
Previsão de tela após a conclusão da atividade de dev:
![projeto.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/99644e0b-ca1c-4e2b-8649-84b866239fcd)

**Comment by RaniGub** [comment]
@matheuscpl você pode indicar o link do Figma para essa tarefa?

**Comment by matheuscpl** [comment]
Não há necessidade de prototipação

**Comment by luannaalves** [comment]
Validado na homologação.

**Comment by luannaalves** [comment]
Validado na produção.
