### ISSUE TITLE
Incluir pop-up/alert para o botão "Salvar" na página de inscrição

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#514]
## **Objetivo**

**Como** Como inscrito em uma oportunidade no mapa da saúde
**Quero** realizar minha inscrição e salvá-la
**Para** melhorar a usabilidade em uma oportunidade na página de inscrição

## **Contexto**
O pop-up/alert para o botão "Salvar" na página de inscrição serve para o usuário ter certeza que quer salvar a inscrição e que essa ação é definitiva. Essa informação já consta na página, mas deverá vir em formato de pop-up para maior alerta ao candidato.

## **Escopo**

- [ ] Inserir pop-up para o usuário que está se inscrevendo em uma oportunidade

## **Critérios de Aceitação**

- [ ] Criar pop-up/alert para quando o usuário clicar em salvar a inscrição. Mostrando que essa ação é definitiva e sem alteração posterior.

## **Observação**
Protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscrições?node-id=365%3A293

**Comment by thaistoscano** [comment]
@matheuscpl Por favor, priorizar essa issue para a próxima sprint.

**Comment by RaniGub** [comment]
Em conversa com a @thaistoscano foi definido que a issue parassará por um refinamento.

**Comment by RaniGub** [comment]
@thaistoscano bom dia, aguardando refinamento dessa issue com o @matheuscpl

**Comment by thaistoscano** [comment]
@Clarisse1983 Para análise das narrativas do figma
 https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscrições?node-id=365%3A293

**Comment by ClarisCaval** [comment]
Sugestões:
Caixa de envio: Após o envio, as informações não poderão ser editadas. Se deseja continuar, é só enviar.
Salvar para depois: Ao clicar, suas informações ficarão salvas para envio posterior. Clique se é isso que deseja fazer.

Mas eu sinceramente curti as mensagens que estão lá, não achei confusas. Vejam se essa proposta atende. ;)

**Comment by thaistoscano** [comment]
Implentação realizada em outro formato, de acordo com a issue: https://app.zenhub.com/workspaces/mapa-da-sade---dev-60f894f541f910001066bfd9/issues/escoladesaudepublica/mapadasaude/591
