### ISSUE TITLE
Resolver bug (no ambiente de homologação) que não atribui oportunidade para avaliador

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#515]
## **Objetivo**

**Como** Administrador de uma oportunidade
**Quero** atribuir um avaliador 
**Para** avaliar os participantes inscritos em uma oportunidade

## **Contexto**

Atualmente o ambiente de homologação está com bug e não atribui certas oportunidades ao avaliadores escolhidos.
-
## **Critérios de Aceitação**

- [ ] Corrigir bug que avaliador selecionado em uma oportunidade não está recebendo os inscritos para avaliar
  

# Observações

ex: Pode ser verificado pela oportunidade que criei no ambiente de homologação - (NOVO) Edital 23/2021- onde atribuí o avaliador 1 para avaliar as oportunidades, mas ele não as visualiza.

**Comment by vicmagpac** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Dev-60f894f541f910001066bfd9/issues/EscolaDeSaudePublica/mapadasaude/515?planning-poker) with ZenHub @FernandaNascimento26 @pedrovitor074 @lucastandy

**Comment by fernandafnascmnt** [comment]
O titulo da Issue não condiz com o problema: a oportunidade é atribuida ao avaliador porém este não visualiza a lista de inscritos na aba avaliações conforme print:

![Captura de tela de 2021-10-13 15-20-34.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/2cfcaa26-bd7d-45f2-a15e-6f992f51f5c7)

**Comment by fernandafnascmnt** [comment]
No ambiente de produção o problema não persiste, conforme exibido na imagem:

![Captura de tela de 2021-10-13 15-22-04.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/e13348b5-0fe8-40c9-a87c-6e492fcb6494)

**Comment by fernandafnascmnt** [comment]
[{"number":"on-773193943","id":773193943,"category":"","status":1,"consolidatedResult":"0","owner":{"id":609,"name":"Thais Sales Barreto Toscano","singleUrl":"https:\/\/mapa.sus.ce.gov.br\/agente\/609\/"},"singleUrl":"https:\/\/mapa.sus.ce.gov.br\/inscricao\/773193943\/","evaluationResultString":""},{"number":"on-1043800501","id":1043800501,"category":"","status":1,"consolidatedResult":"0","owner":{"id":348,"name":"FERNANDA FERREIRA DO NASCIMENTO","singleUrl":"https:\/\/mapa.sus.ce.gov.br\/agente\/348\/"},"singleUrl":"https:\/\/mapa.sus.ce.gov.br\/inscricao\/1043800501\/","evaluationResultString":""},{"number":"on-1997869125","id":1997869125,"category":"","status":1,"consolidatedResult":"0","owner":{"id":330,"name":"Fernanda Nascimento","singleUrl":"https:\/\/mapa.sus.ce.gov.br\/agente\/330\/"},"singleUrl":"https:\/\/mapa.sus.ce.gov.br\/inscricao\/1997869125\/","evaluationResultString":""}]

Requisição na produçao

![Captura de tela de 2021-10-13 15-55-34.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/dbc5b687-98ed-4dff-a301-6c7580559428)


https://mapa.sus.ce.gov.br/api/opportunity/findRegistrations/?@files=(zipArchive):url&@limit=50&@opportunity=68&@page=1&@select=id,singleUrl,category,status,owner.%7Bid,name,singleUrl%7D,consolidatedResult,evaluationResultString,&status=GT(-1)

**Comment by fernandafnascmnt** [comment]
Conforme levantado, este problema foi replicado no ambiente local com o backup do banco que está atualmente em homologação.

**Comment by vicmagpac** [comment]
@FernandaNascimento26 baseado na análise que estamos fazendo, verificamos que a view "evaluations" da versão que estamos usando em homologação e em produção está bugada.

O ajuste foi realizado no dia 06/04/2021 pelo hacklab no commit https://github.com/mapasculturais/mapasculturais/commit/a22e54d137e990c8096f61332c7c8d7d233ee8ab#diff-1e0f74088a5838fc46529d2988bc6040c401e1e784bd776afc806a0614e8d46f

Segue o código da view correta: 

```sql
CREATE VIEW evaluations AS (
                SELECT 
                    registration_id,
                    registration_sent_timestamp,
                    registration_number,
                    registration_category,
                    registration_agent_id,
                    opportunity_id,
                    valuer_user_id,
                    valuer_agent_id,
                    max(evaluation_id) AS evaluation_id,
                    max(evaluation_result) AS evaluation_result,
                    max(evaluation_status) AS evaluation_status
                FROM (
                    SELECT 
                        r.id AS registration_id, 
                        r.sent_timestamp AS registration_sent_timestamp,
                        r.number AS registration_number, 
                        r.category AS registration_category, 
                        r.agent_id AS registration_agent_id, 
                        re.user_id AS valuer_user_id, 
                        u.profile_id AS valuer_agent_id, 
                        r.opportunity_id,
                        re.id AS evaluation_id,
                        re.result AS evaluation_result,
                        re.status AS evaluation_status
                    FROM registration r 
                        JOIN registration_evaluation re 
                            ON re.registration_id = r.id 
                        JOIN usr u 
                            ON u.id = re.user_id
                        where 
                            r.status > 0
                    UNION
                    SELECT 
                        r2.id AS registration_id, 
                        r2.sent_timestamp AS registration_sent_timestamp,
                        r2.number AS registration_number, 
                        r2.category AS registration_category,
                        r2.agent_id AS registration_agent_id, 
                        p2.user_id AS valuer_user_id, 
                        u2.profile_id AS valuer_agent_id, 
                        r2.opportunity_id,
                        NULL AS evaluation_id,
                        NULL AS evaluation_result,
                        NULL AS evaluation_status
                    FROM registration r2 
                        JOIN pcache p2 
                            ON r2.id = p2.object_id
                        JOIN usr u2 
                            ON u2.id = p2.user_id
                        JOIN evaluation_method_configuration emc
                            ON emc.opportunity_id = r2.opportunity_id
                        WHERE 
                            p2.object_type = 'MapasCulturais\Entities\Registration' AND 
                            p2.action = 'evaluate' AND
                            r2.status > 0 AND
                            p2.user_id IN (
                                SELECT user_id FROM agent WHERE id in (
                                    SELECT agent_id 
                                    FROM agent_relation 
                                    WHERE 
                                        object_type = 'MapasCulturais\Entities\EvaluationMethodConfiguration' AND 
                                        object_id = emc.id
                                )
                            ) 
                ) AS evaluations_view 
                GROUP BY
                    registration_id,
                    registration_sent_timestamp,
                    registration_number,
                    registration_category,
                    registration_agent_id,
                    valuer_user_id,
                    valuer_agent_id,
                    opportunity_id
            )
````

Fiz a atualização no ambiente de homologação e as avaliações para os avaliadores responsáveis funcionou bem, tanto para avaliações simplificadas e técnica.

**Comment by fernandafnascmnt** [comment]
Realizei os testes localmente seguindo os passos indicados no comentário acima:

removi a visualização bugada (evaluations) e criei uma nova conforme SQL acima e de fato funcionou corretamente. A lista dos inscritos nas oportunidades ficaram visíveis para os avaliadores.
