### ISSUE TITLE
Cerimônias

### ISSUE THREAD

**Issue by vicmagpac** [FeliciLab/mapadasaude#52]
Planning: Todas segundas: 11:00h

**Comment by rafaelmassuncao** [comment]
**Redefinições em 01/02/2021**

- **Daily:** Segunda a sexta-feira, 08h30
- **Planning:** Quinzenal, iniciando dia 01/02/2021, iniciando 08h30 às 11h
- **Apresentação Gerencial semanal:** Terças-feiras, 15h
