### ISSUE TITLE
Aceitar envio de vídeos até 300mb

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#525]
## **Objetivo**

**Como** inscrito em uma oportunidade
**Quero** enviar vídeos de até 300mb
**Para** participar de editais que exijam essa aplicação

## **Contexto**
Atualmente o mapa não aceita o envio de vídeo de 300mb. Será necessário ajustar a aplicação para essa recepção.

## **Critérios de Aceitação**

- [ ] Adaptar a aplicação para aceitar vídeos de até 300mb.
**Dado que**  estou inscrita em uma oportunidade
**Quando**  vou comprovar um critério de uma oportunidade
**então** posso comprová-lo por meio de vídeos, conforme orientações do edital.

# Observações

ex: Prototipo

**Comment by vicmagpac** [comment]
@thaistoscano atualização realizada em homologação.
Precisamos realizar os testes no ambiente com upload de 300mb.

**Comment by uira** [comment]
@victorMagalhaesPacheco @andreqlp viu aqui?

**Comment by Andreqlp** [comment]
a @thaistoscano informou que só seria aplicada essa configuração dos 300 mb de anexo no ambiente de produção, os planos mudaram?

**Comment by vicmagpac** [comment]
Atualização para aceitar novas variáveis de configurações: https://github.com/EscolaDeSaudePublica/mapadasaude/commit/53fc8370f867e9bfc1dee5e375cb1bcbd34f37f3
