### ISSUE TITLE
Desempate seguindo a ordem dos critérios

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#530]
## **Objetivo**

**Como** gestor de uma oportunidade
**Quero** realizar o desempate pelo sistema
**Para** realizar a classificação correta conforme o edital

## **Contexto**
Demanda apresentada em virtude do edital do concurso do programa Cuidar Melhor. Cumprimento do item: 7.7 Em caso de empate, serão utilizados os critérios elencados no subitem 7.3. A melhor colocação será dada para a iniciativa que obtiver a maior nota no critério inovação. Se o empate permanecer, segue-se para a maior nota nos critérios seguindo em ordem do item “a” ao item “e”
-

## **Escopo**

- [x] Realizar o desempate conforme as regras do edital seguindo uma série de critérios pedidos pelo edital.

## **Critérios de Aceitação**

- [x] Criar módulo de desempate que atenda as regras do edital do Cuidar Melhor e de outros que desempatem de acordo com os critérios. 
- [x] Vincular essa avaliação ao módulo que atenderá essa avaliação (possivelmente novo módulo de homologação)

# Observações

ex: Prototipo

**Comment by thaistoscano** [comment]
Versão 1 - Edital 
https://docs.google.com/document/d/13akheV6emzwnl3bBZV5V44ik6pKAhlIA83UDE3s4cCM/edit

**Comment by Andreqlp** [comment]
Imagino que a proposta do programa Cuidar Melhor seja o modelo padrão de desempate do Mapas no módulo de avaliação técnica. Assim, considera-se a mesma ordem dos critérios de avaliação como a ordem do desempate. Por exemplo, se tenho um avaliação com os seguintes critérios:

Critério A
Critério B
Critério C

Se houver empate na nota geral de dois candidatos, o sistema iria colocar como primeiro o que tiver maior nota no critério A, casa haja empate novamente iria para o critério B e assim por diante.

ps: precisa checar se isso já não está implementado no mapas.

Futuramente seria preciso mapear outros cenários de desempate para criar um módulo com outras opções.

**Comment by thaistoscano** [comment]
@victorMagalhaesPacheco @Junior-Shyko Verificar com o hacklab se já existe essa função "padrão".

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/530?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by matheuscpl** [comment]
Após análise de UX foi visto que não há necessidade de protótipo, esta issue define apenas a regra de negócio do desempate

**Comment by thaistoscano** [comment]
[https://app.zenhub.com/files/319384032/e333ae75-0d24-4257-8d99-1d3b744cf0a5/download](https://app.zenhub.com/files/319384032/e333ae75-0d24-4257-8d99-1d3b744cf0a5/download)

**Comment by pedrovitor074** [comment]
Enviado para produção, junto a correção de relatório para oportunidades do tipo homologação.
