### ISSUE TITLE
Habilitação de recursos (Para o módulo de homologação)

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#531]
## **Objetivo**

**Como** usuário do mapa
**Quero** solicitar recurso
**Para** questionar algum critério votado pela banca

## **Contexto**
Em virtude do edital do Concurso Cuidar Melhor será necessário criar novo módulo de homologação no mapa. E para esse ser habilitado os recursos ao candidato.

## **Critérios de Aceitação**

- [ ] Possibilitar que o candidato recorra aos itens também vinculados ao novo módulo de homologação.

# Observações

ex: Prototipo

**Comment by Andreqlp** [comment]
Queria entender pq vincular o recurso ao módulo de avaliação, ao invés de fazer uma solução genéria que possa servir para qualquer módulo.

**Comment by thaistoscano** [comment]
Não foi necessário realizar essa implementação. Recursos já testados no módulo.
