### ISSUE TITLE
Criar relatório com resultado parcial e final de uma oportunidade

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#532]
## **Objetivo**

**Como** usuário do mapa
**Quero** visualizar os resultados  
**Para** conferir os selecionados

## **Contexto**
Em virtude do Concurso Cuidar Melhor é necessário gerar relatórios parciais e finais de uma oportunidade.
-

## **Critérios de Aceitação**

- [x] Criação de relatório parcial para uma oportunidade
- [x] Criação de relatório final para uma oportunidade
- [x] Exibir resultados por categorias
- [x] Incluir para todas as avaliações (inclusive homologação que está sendo desenvolvido)

# Observações

ex: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=932%3A865

**Comment by thaistoscano** [comment]
@matheuscpl Ajustar o figma para fases separadas

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/532?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by Junior-Shyko** [comment]
O que vai diferenciar o relatório parcial para o relatório Final?
Ex: 

- O Parcial terá as notas e o final somente a status?

- O Parcial tem todos candidatos e o definitivo tem somente os aprovados?

**Comment by thaistoscano** [comment]
@matheuscpl Para análise do comentário acima. E elaboração de figmas separados de acordo com o tipo de avaliação.

**Comment by Junior-Shyko** [comment]
Atualização do commit: https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commits/feature/criar-relatorio-oportunidade

**Comment by pedrovitor074** [comment]
@thaistoscano conversando com a @helenhilario  e o @Junior-Shyko , vimos que não é preciso colocar a nota de cada seção da avaliação preliminar,  somente a nota preliminar ( no relatório  ) e disponibilizar a nota de cada seção somente para o inscrito em seu painel.

**Comment by Junior-Shyko** [comment]
Add funcao dentro da Entidade Pdf.php [Commit](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/18b1e715c9b320c85adbf01bd29e232ed4221672)
