### ISSUE TITLE
Incluir opção N/A (não se aplica) aos critérios de avaliação (técnica)

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#533]
## **Objetivo**

**Como** avaliador de uma oportunidade
**Quero* poder definir que um critério não se aplica
**Para** que não seja contabilizado na média

## **Contexto**
O avaliador precisa ter a opção não se aplica para cada um dos critérios de avaliação. Ao marcar essa opção a nota do critério não é contabilizada.

Cumprimento do item: 7.5 Será atribuída a classificação N/A (não se aplica), quando o critério de seleção não estiver diretamente relacionado à própria natureza da iniciativa. Neste caso, o critério será excluído do cálculo da média e da pontuação final da iniciativa.

## **Critérios de Aceitação**

- [ ] Habilitação da opção não se aplica (N/A) quando o critério de seleção não estiver diretamente relacionado à própria natureza da iniciativa
- [ ] Possibilitar que ao ser vinculado esse critério não seja computado no cálculo da nota

![padrão.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/76d881e8-a720-44ad-b31a-e54ec31a1f87)

# Observações

ex: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1294%3A1402

**Comment by thaistoscano** [comment]
@matheuscpl Alterar para que se não haja nota, possua o critério de não se aplica (vinculado à avaliação técnica).

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/533?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
[https://app.zenhub.com/files/319384032/a65f6c09-4767-4677-a26f-219633594ac4/download](https://app.zenhub.com/files/319384032/a65f6c09-4767-4677-a26f-219633594ac4/download)

**Comment by vicmagpac** [comment]
Observações:

@pedrovitor074 
O pesos estão permitindo notas acima do permitido e definido para o critério. Necessário realizar ajustes na validação .
![image](https://user-images.githubusercontent.com/3487411/146548119-496f4f41-1cab-4694-8017-e5a52a6022d8.png)

**Comment by vicmagpac** [comment]
Observações:

A notas das avaliações devem ter 2 casas decimais. Por exemplo: 91.42.
![image](https://user-images.githubusercontent.com/3487411/146549650-32525d90-1fe1-4b8a-82ef-a36b230c864b.png)

**Comment by vicmagpac** [comment]
> Observações:
> 
> @pedrovitor074 O pesos estão permitindo notas acima do permitido e definido para o critério. Necessário realizar ajustes na validação . ![image](https://user-images.githubusercontent.com/3487411/146548119-496f4f41-1cab-4694-8017-e5a52a6022d8.png)

A validação dos critérios acontecem através de hooks dentro do tema. Foi adicionado mais uma condição agora para a 'technicalna' e avalidação funcionou bem.

**Comment by vicmagpac** [comment]
> Observações:
> 
> A notas das avaliações devem ter 2 casas decimais. Por exemplo: 91.42. ![image](https://user-images.githubusercontent.com/3487411/146549650-32525d90-1fe1-4b8a-82ef-a36b230c864b.png)

Foi realizado o tratamento dentro do plugin para adicionar casas decimais de no máximo 2, seguindo o padrão do mapas.
