### ISSUE TITLE
Proposta de Home Mapa da Saúde

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#537]
## **Objetivo**

**Como** designer  
**Quero** propor nova interface para Home do Mapa da Saúde
**Para** possibilitar uma melhor Experiência para pessoa usuária

## **Contexto**

Devido alguns problemas de usabilidade levantados no Mapa da Saúde, é importante que seja proposta uma nova experiência para quem acessa a plataforma.

## **Escopo**
- [ ] Propor nova interface para Home do Mapa da Saúde considerando princípios de ergonomia e usabilidade

## Observações
Proposta: https://www.figma.com/file/tOEvx2bxwuGQ1YCfgohfHF/Estudos-Mapa?node-id=810%3A343

**Comment by RaniGub** [comment]
@thaistoscano verificar prioridade.

**Comment by RaniGub** [comment]
@matheuscpl vamos trabalhar na perspectiva de apresentar essa proposta e a dos indicadores entre a conclusão dos cards priorizados para as sprints. Vou destacar um tópipo dos indicadores que conseguimos alinhar na próxima daily. @thaistoscano fiz o alinhamento com Uirá sobre Home e indicadores.

**Comment by uira** [comment]
@RaniGub E tirar o Eventos do Menu, né? ;)

**Comment by RaniGub** [comment]
@uira @victorMagalhaesPacheco vamos conversar sobre a proposta e viabilidade.

**Comment by RaniGub** [comment]
Dia 15/12/21 foi realizado alinhamento com Uirá para algumas definições. Pela tarde, conversei com @matheuscpl sobre uma nova proposta com base nesse protótipo em baixa https://www.figma.com/file/CNJ0jcDcBwpcpbWbfBaIlb/Mapa-Digital?node-id=0%3A1
Acordamos pare refinar a partir da base para evitar retrabalhos. Uma proposta em baixa foi solicitada e tem projeção para revisão por pares em 20/12/2021.

**Comment by RaniGub** [comment]
Dia 23/12/21 o @matheuscpl apresentou o conceito inicial após primeiro refinamento. Alguns pontos foram propostos para uma nova apresentação na primeira semana de Janeiro/2022.

**Comment by thaistoscano** [comment]
Será contemplada no redesign @uira ? Fechamos essa atividade?
