### ISSUE TITLE
Módulo homologação - Tela para a criação de uma oportunidade

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#539]
## **Objetivo**

Como gestor de uma oportunidade
Quero selecionar uma modelo de avaliação que permita configurar vários critérios de avaliação para serem validados.
Para aceitação de uma inscrição que deve passar para um próxima etapa de avaliação.

Como avaliador de uma oportunidade
Quero avaliar as inscrições como de acordo com os critérios do edital
Para finalizar minhas avaliações.

## **Contexto**
O edital CONCURSO MUNICÍPIO INOVADOR DO PROGRAMA CUIDAR MELHOR DA SAÚDE NO CEARÁ prevê uma etapa de homologada das inscrições após verificação do cumprimento dos requisitos seguintes requisitos:

Duração do vídeo de até 3 minutos.
A prática está de acordo com as temáticas apresentadas no edital.
Contar com, no mínimo, 4 (quatro) meses de implantações completadas até a data de início das inscrições.

## **Critérios de Aceitação**

- [ ] tela para a criação de uma oportunidade
**Dado que** sou o gestor e estou criando uma oportunidade  
**Quando** clico no botão de criar oportunidade
**então** posso selecionar a opção "Avaliação de homologação"

![qw.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/5a968fe6-d68e-45f9-bf3f-1581d4c08497)

# Observações

ex: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=922%3A566

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/539?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by matheuscpl** [comment]
Protótipo adicionado

**Comment by matheuscpl** [comment]
Protótipo adicionado
