### ISSUE TITLE
Módulo Homologação - Tela para visualizar as inscrições

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#541]
## **Objetivo**

Como gestor de uma oportunidade
Quero selecionar uma modelo de avaliação que permita configurar vários critérios de avaliação para serem validados.
Para aceitação de uma inscrição que deve passar para um próxima etapa de avaliação.

Como avaliador de uma oportunidade
Quero avaliar as inscrições como de acordo com os critérios do edital
Para finalizar minhas avaliações.

## **Contexto**

O edital CONCURSO MUNICÍPIO INOVADOR DO PROGRAMA CUIDAR MELHOR DA SAÚDE NO CEARÁ prevê uma etapa de homologada das inscrições após verificação do cumprimento dos requisitos seguintes requisitos:

Duração do vídeo de até 3 minutos.
A prática está de acordo com as temáticas apresentadas no edital.
Contar com, no mínimo, 4 (quatro) meses de implantações completadas até a data de início das inscrições.

- [ ] tela para visualizar as inscrições
**Dado que** sou o avaliador e consultando a lista de projetos que devo avaliar
**Quando** entre na aba avaliações dentro de uma oportunidade
**então** posso visualizar todos os projetos que devo avaliar com a indicação daqueles e avaliei e com qual status ele foi avaliado.

# Observações

ex: _Deve seguir o padrão de tela atual existente para a aba avaliações dentro de uma oportunidade._

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/541?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by matheuscpl** [comment]
Protótipo adicionado
