### ISSUE TITLE
Módulo de Homologação - Tela para realizar a avaliação

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#542]
## **Objetivo**

Como gestor de uma oportunidade
Quero selecionar uma modelo de avaliação que permita configurar vários critérios de avaliação para serem validados.
Para aceitação de uma inscrição que deve passar para um próxima etapa de avaliação.

Como avaliador de uma oportunidade
Quero avaliar as inscrições como de acordo com os critérios do edital
Para finalizar minhas avaliações.

## **Contexto**

O edital CONCURSO MUNICÍPIO INOVADOR DO PROGRAMA CUIDAR MELHOR DA SAÚDE NO CEARÁ prevê uma etapa de homologada das inscrições após verificação do cumprimento dos requisitos seguintes requisitos:

Duração do vídeo de até 3 minutos.
A prática está de acordo com as temáticas apresentadas no edital.
Contar com, no mínimo, 4 (quatro) meses de implantações completadas até a data de início das inscrições.

## **Critérios de Aceitação**

- [ ] tela para realizar a avaliação
**Dado que** sou o avaliador e estou analisando uma inscrição 
**Quando** abro uma inscrição para avaliar
**então** posso visualizar os critérios de avaliação e, para cada item de forma obrigatória, selecionar uma das opções: válido, inválido ou não se aplica. Além disso posso escrever outras informações no campo justificativa / observações. 

![qwer.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/9deddb94-8485-40a8-9aa9-0c5b709b5b23)

# Observações

ex: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=922%3A566

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/542?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by matheuscpl** [comment]
Protótipo adicionado
