### ISSUE TITLE
Módulo de Homologação - Arquivo com a lista das avaliações

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#543]
## **Objetivo**

Como gestor de uma oportunidade
Quero selecionar uma modelo de avaliação que permita configurar vários critérios de avaliação para serem validados.
Para aceitação de uma inscrição que deve passar para um próxima etapa de avaliação.

Como avaliador de uma oportunidade
Quero avaliar as inscrições como de acordo com os critérios do edital
Para finalizar minhas avaliações.

## **Contexto**
O edital CONCURSO MUNICÍPIO INOVADOR DO PROGRAMA CUIDAR MELHOR DA SAÚDE NO CEARÁ prevê uma etapa de homologada das inscrições após verificação do cumprimento dos requisitos seguintes requisitos:

Duração do vídeo de até 3 minutos.
A prática está de acordo com as temáticas apresentadas no edital.
Contar com, no mínimo, 4 (quatro) meses de implantações completadas até a data de início das inscrições.

## **Critérios de Aceitação**

- [ ] arquivo com a lista das avaliações
**Dado que** sou o gestor e quero baixar o resultado detalhado das avaliações  
**Quando** clico no botão baixar lista de avaliações
**então** posso acessar o resultado detalhado para gerar o resultado ou o parecer da avaliação.

# Observações

ex: _Deve seguir o padrão de lista de avaliações existente para a aba avaliações dentro de uma oportunidade._

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/543?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
![image.png](https://images.zenhubusercontent.com/6140f6973ff8904a055e7b0e/541729df-bac8-44b1-9aad-16dd1ebec311)

**Comment by matheuscpl** [comment]
Sem necessidade de protótipo
