### ISSUE TITLE
Retirada da entrada dos dados no CNES no gráfico de novos agentes

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#544]
## **Objetivo**

**Como** usuário do mapa
**Quero** ter a visão dos novos cadastros diretos no mapa 
**Para** não visualizar os dados de outros bancos

## **Contexto**
Atualmente na aba de indicadores no gráfico de cadastro de novos agentes por semana visualiza-se uma discrepância devido a migração de dados do CNES.

## **Critérios de Aceitação**

- [ ] Retirar do gráfico de cadastro dos novos profissionais os dados migrados de outras plataformas (ex: CNES).

# Observações

ex: Prototipo

**Comment by vicmagpac** [comment]
Atividade atualizada em produção.
