### ISSUE TITLE
Melhorias para a declaração (certificado) gerado pelo Mapa

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#545]
## **Objetivo**

**Como** usuário do mapa
**Quero** uma declaração 
**Para** comprovação de participação em um evento

## **Contexto**
Atualmente o mapa emite certificados do tipo declaração para eventos por meio do selo. Então é necessário configurar esse modelo para que seja emitido em PDF.
-

## **Critérios de Aceitação**
- [ ] Inclusão de uma ou mais assinaturas digitalizadas no corpo do texto da declaração. 
- [ ] Link de validação da declaração.
- [ ] Emissão da declaração do participante formatada em modelo PDF para download.
- [ ] Permitir que possa não ser adicionado assinatura
- [ ] Permitir remover caso queira retirar as assinaturas
- [ ] Utilizar Nome Completo para gerar a declaração 

![A4 - 3.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/bb702987-ec52-456d-808a-633ad37560be)

# Observações

Protótipo adição de assinatura e envio de declaração: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1186%3A3305

Protótipo novo certificado: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1185%3A3178

**Comment by thaistoscano** [comment]
@helenhilario Para esse último item "Envio a declaração por e-mail ao usuário após o evento, se ele estiver validado pelo avaliador" como está sendo feita a validação atualmente?

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/545?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by fernandafnascmnt** [comment]
@matheuscpl poderia, por favor, gerar uma imagem deste exemplo de certificado para que eu possa inserir para o participante veja como modelo? O texto do corpo pode ser padrão ou lerem ipsum. Obrigada!!

**Comment by matheuscpl** [comment]
@FernandaNascimento26 Add a imagem

**Comment by fernandafnascmnt** [comment]
[Inclusão do carregamento de imagem e campo de assinatura](https://github.com/EscolaDeSaudePublica/plugin-SealCertified/pull/2)

**Comment by fernandafnascmnt** [comment]
@matheuscpl , poderia por favor, me fornecer a imagem do rodapé? 

![Captura de tela de 2021-12-01 10-54-03.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/6af66a09-9bd5-4f3e-bd6e-77d649eb20c3)

**Comment by matheuscpl** [comment]
[rodapé.zip](https://github.com/EscolaDeSaudePublica/mapadasaude/files/7634754/rodape.zip)
@FernandaNascimento26

**Comment by matheuscpl** [comment]
[rodapé (2).zip](https://github.com/EscolaDeSaudePublica/mapadasaude/files/7634793/rodape.2.zip)
Agora sim! rs

**Comment by fernandafnascmnt** [comment]
[https://app.zenhub.com/files/319384032/df665e5a-f33b-4f6c-9627-db11eb90f58b/download](https://app.zenhub.com/files/319384032/df665e5a-f33b-4f6c-9627-db11eb90f58b/download)

**Comment by fernandafnascmnt** [comment]
No link acima é possível baixar alguns PDfs gerados após alterações de melhoria

**Comment by fernandafnascmnt** [comment]
Alterações solicitadas estão contidas no plugin [SealCertified](https://github.com/EscolaDeSaudePublica/plugin-SealCertified), no pull Request: [#545 adicionando imagem e campo de assinatura](https://github.com/EscolaDeSaudePublica/plugin-SealCertified/tree/feature/melhoria-selos)

Aguardando aprovação d@ QA

**Comment by vicmagpac** [comment]
Atividade bloqueada aguardando a autorização e validação do setor responsável.

**Comment by RaniGub** [comment]
@matheuscpl os documentos que contém a assinatura da ESP deverão passar por um alinhamento com a Ascom/ESP para validação (ascom@esp.ce.gov.br). Irei parear com você sobre o assunto, já aproveito para deixar o modelo que deverá ser usado como base.[https://app.zenhub.com/files/319384032/734f71b7-a0ed-4662-867a-38be8d6406a4/download]

**Comment by RaniGub** [comment]
@matheuscpl acabamos de ter atualização sobre a tarefa. Essa vai continuar como está. A @thaistoscano irá criar uma nova Issue para que seja proposto o modelo padrão para validação com a ASCOM/ESP.

**Comment by fernandafnascmnt** [comment]
Passou pelo Review QA E Disponível para code Review em : https://github.com/EscolaDeSaudePublica/plugin-SealCertified/pull/2
