### ISSUE TITLE
Indicadores do Mapa | Página da seção dos Indicadores

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#546]
## **Objetivo**

**Como** designer  
**Quero** criar uma página home para indicadores
**Para** proporcionar uma melhor experiência para pessoa usuária

## **Contexto**

Antes de uma análise detalhada sobre apresentação dos indicadores ser realizada, devemos propor uma solução para página da seção.

## **Escopo UX**
- [x] Criar home para seção de indicadores

## **Escopo PubliciLAB**
- [ ] Criar textos para indicadores 'Espaços de Saúde' e 'Profissionais'

## Observações
Link de referência https://integrasus.saude.ce.gov.br/

Proposta: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=461%3A305

**Comment by RaniGub** [comment]
A seção de indicadores está passando por uma reestruturação pelo time da Ciência de Dados. Logo seja concluída, esta tarefa passará pela validação.

**Comment by thaistoscano** [comment]
Os indicadores estão ocultos no momento.
