### ISSUE TITLE
Ocultar opção 'Eventos' do Menu Principal

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#547]
## **Objetivo**

**Como** desenvolvedor
**Quero** ocultar a opção 'Eventos' do menu principal
**Para** não possibilitar que a pessoa usuária acesse uma seção sem informações

## **Contexto**

No cenário atual, a opção de Eventos não deveria ter destaque no menu principal do Mapa da Saúde.

## **Escopo UX**
- [ ] Ocultar opção 'Eventos' do menu principal

## **Escopo DEV**
- [ ] Ocultar opção 'Eventos' do menu principal

## **Critérios de Aceitação**
- [ ] Ocultar 'Eventos' do Menu Principal  
**Dado que** acesso o Mapa da Saúde  
**Quando** visualizo o menu principal  
**então** não vejo a opção 'Eventos'

- [ ] Ocultar a aba "agenda" em todas as entidades 
**Dado que** acesso o Mapa da Saúde  
**Quando** visualizo a oportunidade/espaço/agente/projeto
**então** vejo uma agenda sem funcionalidade

## Observações
Figma:

**Comment by thaistoscano** [comment]
Operação realizada por meio da issue https://app.zenhub.com/workspaces/mapa-da-sade---dev-60f894f541f910001066bfd9/issues/escoladesaudepublica/saude/271.
