### ISSUE TITLE
Criar obrigatoriedade para as categorias (opções)

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#566]
## **Objetivo**

**Como** dono de uma oportunidade
**Quero** ter a opção de marcar como obrigatória a opção de uma categoria
**Para** que o inscrito não deixe em branco

## **Contexto**
Atualmente as categorias (opções) podem não ser preenchidas, o que não pode ocorrer na maioria dos certames.
-

## **Critérios de Aceitação**

- [ ] Permitir que as categorias de uma oportunidade possam ser obrigatórias

# Observações

ex: Prototipo

**Comment by vicmagpac** [comment]
@pedrovitor074 esse é um PR no core pra adicionar hooks nas validações: https://github.com/EscolaDeSaudePublica/mapadasaude/pull/586

Esse é o PR para adicionar validação https://github.com/EscolaDeSaudePublica/Saude/pull/285 na categoria da oportunidade no momento da criação.

**Comment by pedrovitor074** [comment]
Foi adicionado a verificação no front end para mostrar que o campo categoria é obrigatório no momento da inscrição, e na criação de oportunidade também.
