### ISSUE TITLE
Instalação do Mapas (local)

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#57]
Repositório: [clique aqui](https://github.com/govce/mapasculturais)
Instalação: [clique aqui](http://docs.mapasculturais.org/mc_deploy/)

- [x] Softwares requeridos
- [ ] Clonando o repositório
- [ ] Banco de dados
- [ ] Configurações de instalação
- [ ] Concluindo
- [ ] Configurando serviço de cron
- [ ] API de CEP
- [ ] Super admin
- [ ] Autenticação

**Comment by thaistoscano** [comment]
Card sem contexto. Em reunião com a equipe foi decidido pela exclusão.
