### ISSUE TITLE
Envio de múltiplos arquivos por critério em uma oportunidade

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#583]
## **Objetivo**

**Como** pessoa usuária do Mapa da Saúde  
**Quero** dispor de uma opção para upload de vários anexos por critério/item em uma oportunidade
**Para** conseguir enviar (fazer upload) em mais de um arquivo por critério/item de uma oportunidade

## **Contexto**
Em função do Edital 26/2021, é preciso que esse ponto seja trabalhado para que a pessoa usuária consiga enviar mais de um anexo por critério/item para pontuação

## **Escopo UX**
- [ ] Criar uma experiência para envio de múltiplos arquivos por critério em uma oportunidade

## **Escopo DEV**
- [ ] Avaliar a aplicação da sugestão de experiência na oportunidade
- [ ] Aplicar a proposta

## **Critérios de Aceitação**
- [ ] Envio de múltiplos arquivos em uma oportunidade 
 
**Dado que** a pessoa usuária clique no botão 'Enviar' no critério/item de uma oportunidade  
**Quando** ela anexa o primeiro arquivo  
**então** a pessoa usuária deve conseguir continuar enviando outros arquivos que ache relevante para pontuação no critério/item 

## Observações
https://mapadasaude.dev.org.br/oportunidade/337/

**Comment by RaniGub** [comment]
@victorMagalhaesPacheco A ideia é deixar um único campo para a pessoa ir selecionando de um em um os arquivos e abaixo um campo que mostre os arquivos que já foram upados com a opção de excluir. É possível criar a experiência nessa direção?

**Comment by RaniGub** [comment]
Escopo da tarefa editado.

**Comment by RaniGub** [comment]
Escopo da tarefa editado.

**Comment by luannaalves** [comment]
Já implementado.
