### ISSUE TITLE
Criar a possibilidade de múltiplos anexos para um campo da oportunidade

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#584]
## **Objetivo**

**Como** Usuário de uma oportunidade  
**Quero** anexar múltiplos anexos
**Para** comprovar as pontuações do edital

## **Contexto**
Atualmente no mapa para cada anexo é necessário um novo campo a ser inserido pelo dono da oportunidade. A ideia é que somente com um campo inserido seja possível que o usuário coloque a quantidade de anexos que desejar.
-

## **Critérios de Aceitação**

- [ ] Possibilitar o usuário inserir vários anexos em um só campo.

# Observações

ex: Prototipo

**Comment by vicmagpac** [comment]
Atividade com impacto no core do mapas e no tema.
Branch feature do tema: https://github.com/EscolaDeSaudePublica/Saude/tree/feature/multiple-upload

**Comment by vicmagpac** [comment]
Ao ser atualizado no ambiente é necessário executar o ./db-update para atualizar as migrations.

**Comment by vicmagpac** [comment]
> Ao ser atualizado no ambiente é necessário executar o ./db-update para atualizar as migrations.

Necessário realizar a limpeza no DoctrineProxies `cd DoctrineProxies &&  rm -R *` e seguida reiniciar a stack do container.

**Comment by vicmagpac** [comment]
Atividade vinculada a issue: https://github.com/EscolaDeSaudePublica/mapadasaude/issues/593
