### ISSUE TITLE
Pop-up de confirmação de envio de inscrição | Edital 26/2021

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#591]
## **Objetivo**

**Como** pessoa candidata no edital 26/2021  
**Quero** visualizar uma mensagem de confirmação ao enviar uma inscrição
**Para** reforçar a necessidade da revisão dos dados do formulário pela pessoa usuária antes do envio da inscrição

## **Contexto**
Em função do Edital 26/2021, é preciso sanar alguns pontos de usabilidade para melhorar a experiência da pessoa candidata.

## **Escopo UX**
- [x] Criar experiência para exibição da mensagem ao clicar no botão 'Enviar Inscrição' na oportunidade. Ex. da mensagem: Você conferiu os seus dados? Ao confirmar, essa ação não poderá ser desfeita e você não conseguirá editar os dados. Você poderá verificar o status de sua inscrição em Meu Perfil>Minhas Inscrições

## **Escopo DEV**
- [ ] Analisar e aplicar a proposta

## **Critérios de Aceitação**
- [ ] Mensagem de confirmação de envio de inscrição 
 
**Dado que** a pessoa usuária clique no botão 'Enviar Inscrição' na oportunidade do Edital 26/2021
**Quando** aguarda a confirmação de envio 
**então** a pessoa visualiza o pop-up com a mensagem sugerida pelo UX para prosseguir ou parar

## Observações
https://mapadasaude.dev.org.br/projeto/77/
Figma: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1536%3A1260

**Comment by RaniGub** [comment]
Exemplo de mensagem modificado para: Você conferiu os seus dados e anexos? Ao enviar sua inscrição, essa ação não poderá ser desfeita. Você poderá conferir a qualquer momento sua inscrição em Meu Perfil>Minhas Inscrições.

**Comment by RaniGub** [comment]
Experiência revisada e inserida no Escopo.

**Comment by RaniGub** [comment]
No Figma a mensagem ficou: Você conferiu os seus dados? Ao confirmar, essa ação não poderá ser desfeita e você não conseguirá editar os dados. Você poderá verificar o status de sua inscrição em Meu Perfil>Minhas Inscrições

**Comment by uira** [comment]
Fiz uma proposta alternativa no figma, se puderem dar uma olhada e refinada.

Mas acho que vale melhorar a UxWriting da parada

**Comment by RaniGub** [comment]
Laranja mudado para o de referência do logo do Mapa #F26822. Pop-Up definido e refinado com a @thaistoscano. Figma com sugestão atualizado.
