### ISSUE TITLE
Modificar contraste de cor do botão "Reivindicar Propriedade"

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#592]
## **Objetivo**

**Como** designer
**Quero** propor a visualização do botão "Reivindicar Propriedade" com menos constraste
**Para** não entrar em conflito com a importância dos demais botões da tela

## **Contexto**
Em função do Edital 26/2021, é preciso sanar alguns pontos de usabilidade para melhorar a experiência da pessoa candidata.

## **Escopo UX**
- [x] Propor readequação de contraste de cor do botão "Reivindicar Propriedade" de uma oportunidade publicada

## **Escopo DEV**
- [ ] Analisar e aplicar a proposta

## **Critérios de Aceitação**
- [ ] Contraste de cor do botão "Reivindicar Propriedade"
 
**Dado que** a pessoa usuária esteja em uma página de oportunidade ou espaço
**Quando** visualizar o botão "Reivindicar Propriedade"
**então** ela não deduza que o botão tem tanta importância informacional dentro do contexto apresentado

## Observações
https://mapadasaude.dev.org.br/projeto/77/
Figma: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1542%3A1274

**Comment by RaniGub** [comment]
Experiência revisada. Figma inserido no Escopo.

**Comment by uira** [comment]
Fiz uma sugestão diferente no figma, Importante revisar e definir

**Comment by RaniGub** [comment]
@uira eu achei apagado, sei que sua intenção é passar desapercebido. Mas então faz sentido a opção ser "visível"? Precisamos pensar que se a pessoa deve saber que a opção existe, então ela deve estar acessível. Segui o padrão cromático proposto em outros botões.

**Comment by RaniGub** [comment]
@thaistoscano foi definido por Uirá que a versão que será usada é a sugerida por ele (a mais clara).

**Comment by RaniGub** [comment]
Label: #D9D9D9
Borda: #D9D9D9
Fundo: #FFFFFF
