### ISSUE TITLE
Modificar a hierarquia visual do ícone 'Meu Perfil' no menu principal

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#594]
## **Objetivo**

**Como** pessoa candidata no edital 26/2021  
**Quero** visualizar com facilidade o acesso ao 'Meu Perfil'
**Para** deduzir que minhas inscrições estejam disponíveis nessa opção

## **Contexto**
Em função do Edital 26/2021, é preciso sanar alguns pontos de usabilidade para melhorar a experiência da pessoa candidata.

## **Escopo UX**
- [x] Apresentar o ícone do 'Meu Perfil' no mesmo grau de hierarquia visual dos demais ícones do menu principal e adicionar a Tag "Meu Perfil", seguindo o padrão dos demais ícones.
- [x] Alterar a Tag da Opção "Meu Perfil" no menu de opções do usuário, para "Meus dados"

## **Escopo DEV**
- [ ] Analisar e aplicar a proposta
- [ ] Alterar a Tag da Opção "Meu Perfil" no menu de opções do usuário, para "Meus dados"

## **Critérios de Aceitação**
- [ ] Ícone 'Meu Perfil' do menu principal
 
**Dado que** a pessoa usuária tenha visualização clara do ícone 'Meu Perfil'
**Quando** ela clica no ícone 'Meu Perfil'
**então** ela consegue ter acesso às inscrições realizadas

- [ ] Alterar a Tag da Opção "Meu Perfil" nas opções da pessoa usuária, para "Meus dados"
 
**Dado que** a pessoa usuária faz login no Mapa da Saúde
**Quando** ela clica no ícone 'Meu Perfil'
**então** ela consegue ter acesso à mudança seus dados clicando em "Meus Dados"

## Observações
https://mapadasaude.dev.org.br/projeto/77/
Figma da inclusão da Tag Meu Perfil: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1546%3A1273
Figma da troca de Tag para Meus Dados: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1663%3A1290

**Comment by RaniGub** [comment]
Experiência revisada. Figma inserido no Escopo.

**Comment by RaniGub** [comment]
@FernandaNascimento26 Escopo atualizado. Figma da sugestão 2 adicionado.

**Comment by thaistoscano** [comment]
Pronto para produção.
