### ISSUE TITLE
Formatar Data

### ISSUE THREAD

**Issue by Junior-Shyko** [FeliciLab/mapadasaude#6]
Formatar a data de nascimento/Fundação na página de inscrição do candidato
![Captura de tela de 2020-07-13 10-17-07](https://user-images.githubusercontent.com/7341117/87308782-1dd74b80-c4f2-11ea-9cb5-65f708d05531.png)

**Comment by thaistoscano** [comment]
Já foi realizada essa alteração. Issue: https://github.com/EscolaDeSaudePublica/Saude/issues/66
