### ISSUE TITLE
Criar limitação de inscrições por projetos 

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#600]
## **Objetivo**

**Como** Dono de uma oportunidade
**Quero** criar um bloqueio por projetos
**Para** que eu possa limitar além das oportunidades

## **Contexto**
Atualmente somente existe bloqueio de inscrições por oportunidade, porém além de oportunidade é necessário que haja bloqueio por projeto. (Ex: Permissão para se inscrever em 2 oportunidade/perfis de um edital).
-

## **Critérios de Aceitação**

- [ ] Criar limitação de inscrições também em um projeto  
- [ ] Utilizar a mesma lógica da limitação das oportunidades (que pode ser mutável depois )

**Dado que** realizo duas inscrições em oportunidade diferentes
**Quando** faço a terceira
**então** resulta em um bloqueio, pois essa é regra do edital.

**Comment by vicmagpac** [comment]
Atividade sendo implementada no repositório e na branch https://github.com/EscolaDeSaudePublica/saude/tree/feature/limite-inscricoes-projetos

**Comment by vicmagpac** [comment]
Baseado no alinhamento e seguindo padrão do mapas as inscrições começam a contar a partir do rascunho, ou seja, cada rascunho é uma inscrição (core mapas culturais). A implementação que está sendo realizada para os projetos está seguindo a mesma lógica estrutural do mapas de contabilizar rascunho como inscrição. Em conversa com @thaistoscano verificou-se a necessidade de um alinhamento mais refinado para entender se a funcionalidade passa a contar a partir do rascunho(padrão) ou pendente.
