### ISSUE TITLE
Revisão do texto do e-mail de cadastro em oportunidade

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#601]
## **Objetivo**

**Como** dono de uma oportunidade
**Quero** quero melhorias no e-mail de confirmação de inscrição
**Para** que fique mais claro e instrutivo

## **Contexto**
Modificação na proposta atual enviada pelo Mapa. Melhorias serão adicionadas como sugestão nos comentários.

## **Critérios de Aceitação**

- [ ] Melhoria do texto de recebimento de inscrição do candidato

# Observações

ex: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1709%3A1303

**Comment by thaistoscano** [comment]
Olá!

Confirmamos sua inscrição na Oportunidade: Novo Teste - Edital 26/2021 - Área de Atuação I: Design de Experiência / Interface do Usuário.

Nome do Candidato: Clarisse Castro Cavalcante
Número de inscrição: #on-854357654

Acompanhe novidades sobre sua inscrição em nossa plataforma.

Obrigado!

Mapa da Saúde

https://mapa.sus.ce.gov.br (link que vá para a página de acompanhamento do candidato)

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/601?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
Isseu contemplada na 601.
https://app.zenhub.com/workspaces/mapa-da-sade---dev-60f894f541f910001066bfd9/issues/escoladesaudepublica/mapadasaude/601

**Comment by fernandafnascmnt** [comment]
**Teste com mensagem padrão que já vem na criação da Oportunidade:**
![Captura de tela de 2022-01-14 10-59-32.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/c6072d0c-3537-484e-9781-8701fa320161)

![Captura de tela de 2022-01-14 10-55-44.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/3a153312-17af-43fd-935d-6a2f887e2a10)

**Teste com texto personalizado**
![Captura de tela de 2022-01-14 10-56-24.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/d0486a98-a8c4-4fc0-ba67-423746e0a686)


**Teste retirando o texto padrão**

![Captura de tela de 2022-01-14 10-56-11.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/6607ddef-ba9b-44ff-8bcc-ca26a499b243)

**Comment by fernandafnascmnt** [comment]
**Teste com o campo de texto de mensagem vazio**

![Captura de tela de 2022-01-14 10-14-22.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/aa0c8fe3-3c69-4018-a9d9-7ea37d3e656e)
