### ISSUE TITLE
Criar novo modelo de declaração - Padrão ESP 

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#604]
## **Objetivo**

**Como** dono de uma oportunidade
**Quero** gerar novo modelo de declaração em padrão ESP
**Para** certificar uma oportunidade

## **Contexto**
Criar novo modelo de declaração a ser emitido para o mapa. Deverá ser nomeado de "Declaração - Padrão ESP"
-

## **Critérios de Aceitação**

- [ ] Criar novo modelo de declaração de acordo com modelos ESP

# Observações

ex: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1375%3A1445

Rodapé: [https://app.zenhub.com/files/319384032/056f6441-cc47-4a0b-8b0d-caea97a4ddd8/download](https://app.zenhub.com/files/319384032/056f6441-cc47-4a0b-8b0d-caea97a4ddd8/download)

Logos do cabeçalho: [https://app.zenhub.com/files/319384032/84f0ec1c-6da3-4e5a-b930-0ab26076ab30/download](https://app.zenhub.com/files/319384032/84f0ec1c-6da3-4e5a-b930-0ab26076ab30/download)

**Comment by thaistoscano** [comment]
Modelo fornecido pela ASCOM
[https://app.zenhub.com/files/319384032/3063dc21-b605-4c88-86b3-4c7cf384f0c2/download](https://app.zenhub.com/files/319384032/3063dc21-b605-4c88-86b3-4c7cf384f0c2/download)

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/604?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
@matheuscpl Voltar para o texto anterior, está substituído pelo do Cuidar Melhor.

**Comment by fernandafnascmnt** [comment]
@matheuscpl poderia fornecer essa imagem do rodapé?

**Comment by fernandafnascmnt** [comment]
@matheuscpl poderia fornecer a logo da escola em boa qualidade?

**Comment by Junior-Shyko** [comment]
1. Add na url o id do layout criptografado.
2. Os layouts deve ser criado com o mesmo nome que está na tabela term campo term
3. Controlador dentro do plugin para gerar as rotas.
4. Add uma rota no botão imprimir do candidato (_sealCertified/gerarSelo/id_relacao/layout/id_layout_)

**Comment by Junior-Shyko** [comment]
[Commit ](https://github.com/EscolaDeSaudePublica/plugin-SealCertified/commit/4b04d86dd18c99143077eb85ec19797970cea6ec) do plugin

**Comment by Junior-Shyko** [comment]
Criado as views e gerando layout pelo controlador.[ Commit](https://github.com/EscolaDeSaudePublica/plugin-SealCertified/commit/d49f358bd080141c062379661b0f03d02b2dce6b)

**Comment by Junior-Shyko** [comment]
[Commit](https://github.com/EscolaDeSaudePublica/plugin-SealCertified/commit/0475dabf740b10c217d0357a9166bc03b33ff506) com atualização do plugin.

Precisa adicionar 
```
$this->applyTemplateHook('selo-layout','begin');
$this->applyTemplateHook('selo-layout','end'); 
```
Dentro do arquivo _seal-model--content.php_ em layouts/parts.
Avaliar PR para o repositório do MapasCulturais.

**Comment by Junior-Shyko** [comment]
Update - [Commit](https://github.com/EscolaDeSaudePublica/plugin-SealCertified/commit/54c920dfb908f929f2023c7bfa21d66991cb4550)

**Comment by Junior-Shyko** [comment]
Update - [Commit](https://github.com/EscolaDeSaudePublica/plugin-SealCertified/commit/12e921bcea048310f5c5f308527c4afa893a3976)

**Comment by fernandafnascmnt** [comment]
@Wanderley97 , algumas considerações para geração de declaração por meio do selo

Para gerar uma declaração por meio do selo, é necessário que selecionado o modelo, disponível na aba **Modelos** (atualmente só temos o modelo **Declaração ESP)

Também é necessário selecionar o **Layout** disponível na mesma aba (atualmente temos o **Certificado Padrão da ESP** e o **Certificado Padrão do Cuidar Melhor**)

Selecionadas estas opções ele exibirá um preview com o modelo selecionado. 

Caso as duas informações não sejam selecionadas, o certificado não será gerado.

**Comment by fernandafnascmnt** [comment]
![Screenshot from 2022-01-05 14-00-16.png](https://images.zenhubusercontent.com/6107f7497cd3e401e98eca0e/2be3d1e0-f3f8-4078-bdb9-8e13e646e0be)

**Comment by fernandafnascmnt** [comment]
Modelo de formatação ideal para OFICINA DE COLETA DE DADOS
PARA A IMPLANTAÇÃO DA VIGILÂNCIA DOS FATORES DE
RISCO E PROTEÇÃO PARA AS DOENÇAS CRÔNICAS NÃO
TRANSMISSÍVEIS (DCNT)
[https://app.zenhub.com/files/319384032/dd6a24b9-c170-4444-b431-e27d19668fc3/download](https://app.zenhub.com/files/319384032/dd6a24b9-c170-4444-b431-e27d19668fc3/download)

**Comment by pedrovitor074** [comment]
Update - Correção de problema quando o usuário não estava logado no sistema.  - [Commit](https://github.com/EscolaDeSaudePublica/plugin-SealCertified/commit/e0fb5a3de6e8f63af974cf8548c368c82d80e038)
