### ISSUE TITLE
Melhorias na interface do IDSaúde

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#605]
## **Objetivo**

**Como** gestor
**Quero** realizar melhorias
**Para** o acesso do usuário

## **Contexto**
Melhorias na interface do IDSaúde. Realizar as retiradas e mudança de posição do Saiba Mais. Seguem prints nos comentários.
-

## **Critérios de Aceitação**

- [ ] Retirar os itens gerenciamento de acesso e identidade / idsaúde. 
- [ ] Mudança no local do botão Saiba Mais (2 locais).
- [ ] Realizar mudança na nomenclatura Sobrenome para Sobrenome completo.

# Observações

ex: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1758%3A1304

**Comment by thaistoscano** [comment]
![photo4972502544928581934.jpg](https://images.zenhubusercontent.com/6140f6973ff8904a055e7b0e/23808b06-3ca5-4101-80cf-d68097d5ff85)

**Comment by thaistoscano** [comment]
Alterar Sobrenome para Sobrenome completo
![image.png](https://images.zenhubusercontent.com/6140f6973ff8904a055e7b0e/3ade48b7-10e7-4a2a-acfd-a3f4138e0387)

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/605?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
Usar como base as figuras inseridas, pois o figma não está atualizado.

**Comment by fernandafnascmnt** [comment]
Atividade realizada no Repositório do IDSaude [PR da atividade](https://github.com/EscolaDeSaudePublica/IdentidadeUnicaDeSaude/pull/62)

**Comment by fernandafnascmnt** [comment]
Atividade já se encontra em produção devido a falta de alinhamento entre homologação e produção por parte do IDSaúde. As alterações podem ser verificadas em: 
[Página de login do Mapa da Saúde](https://id.sus.ce.gov.br/auth/realms/saude/protocol/openid-connect/auth?client_id=mapadasaudeproducao&redirect_uri=https%3A%2F%2Fmapa.sus.ce.gov.br%2Fautenticacao%2Fkeycloak%2Foauth2callback&response_type=code&scope=profile+email)

[Página de Cadastro do Mapa da Saúde](https://id.sus.ce.gov.br/auth/realms/saude/login-actions/registration?client_id=mapadasaudeproducao&tab_id=jtcI4Qurgdo)

Lembrando que as alterações não seguiram o protótipo e sim, os prints, conforme orientação da @thaistoscano
