### ISSUE TITLE
Unificar campo do Nome/Sobrenome para Nome Completo no IDSaúde

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#606]
## **Objetivo**
**Como** gestor do Mapa da saúde
**Quero** realizar melhorias
**Para** o acesso do usuário

## **Contexto**
Atualmente, quando o usuário acessa a página de login através do ID Saúde, para o campo de preenchimento do nome existem dois campos (Nome e Sobrenome), os quais devem ser unificados em um único campo.

## **Escopo DEV**
- Unificar os campos nome/sobrenome na tela inicial de login do ID Saúde
- Deverá ser implementado conforme protótipo apresentado pelo DesignLab.

## **Critérios de Aceitação**
- [x] **Unificar campos nome/sobrenome**
**Dado que** o usuário
**Quando** acesse a página de login do ID Saúde
**Então** identifique um único campo para preenchimento do nome

# Observações
![Frame 2.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/753837ad-37b7-4a00-8308-5c77253e3697)

Ver protótipo a seguir: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=1740%3A1661

**Comment by fernandafnascmnt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Dev-60f894f541f910001066bfd9/issues/EscolaDeSaudePublica/mapadasaude/606?planning-poker) with ZenHub @Junior-Shyko @pedrovitor074

**Comment by luannaalves** [comment]
validado na homologação.

**Comment by luannaalves** [comment]
validado na produção.
