### ISSUE TITLE
Modificar lógica da contagem de inscrições por projeto

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#607]
## **Objetivo**

**Como** administrador da oportunidade
**Quero** modificar a lógica contagem
**Para** que os rascunhos não contem no limite do projeto

## **Contexto**
Está implementado a contagem por projetos, porém ele leva em consideração também os rascunhos. Deve ser alterada a lógica dos rascunhos (SOMENTE NA CONTAGEM DOS PROJETOS). Dentro de cada oportunidade deve continuar sendo contado da maneira que está atualmente.
-

- [ ] Não contar rascunhos na limitação dos projetos

# Observações

ex: Prototipo

**Comment by matheuscpl** [comment]
Não há necessidade de protótipo

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/607?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco
