### ISSUE TITLE
Corrigir bug que não permite "Salvar para depois"

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#610]
## **Objetivo**

**Como** usuário 
**Quero** salvar uma inscrição para depois
**Para** não perder minhas informações preenchidas

## **Contexto**
Como usuária do mapa quero salvar minha inscrição que está incompleta, porém o sistema não permite pelos campos serem obrigatórios, porém o intuito de salvar como rascunho é salvar de forma incompleta para depois.
-

## **Critérios de Aceitação**

- [ ] Corrigir bug que não permite salvar para depois uma inscrição incompleta  

# Observações

ex: Prototipo

**Comment by matheuscpl** [comment]
Não há necessidade de protótipo

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/610?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco
