### ISSUE TITLE
Melhorar visualização do botão "Imprimir Ficha de Inscrição"

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#614]
## **Objetivo**

**Como** usuário do mapa
**Quero** visualizar com mais facilidade o botão de imprimir minha ficha de inscrição
**Para** guardar esse arquivo

## **Contexto**
Foi solicitado pelo GTCESP melhoria na localização do botão imprimir ficha de inscrição para que o candidato o localize com maior facilidade.
-

## **Critérios de Aceitação**
- [ ] Inclusão do botão também na parte superior da página
- [ ] Inclusão do botão na tabela de inscrições na página da oportunidade

# Observações

Protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2380%3A3200

**Comment by thaistoscano** [comment]
@RaniGub Esse atividade ficou sem o figma, mas foi realizada com base nele. Você pode localizar e inserir aqui?

**Comment by RaniGub** [comment]
Bom dia Thaís, por gentileza, fale com o @pauloamoreira

**Comment by pauloamoreira** [comment]
.board da tarefa criado: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2380%3A3200

**Comment by RaniGub** [comment]
Análise de UX:
- Foi modificada a visualização do botão 'Imprimir em PDF' no Comprovante de Inscrição;
- A pessoa terá acesso à impressão do Comprovante quando clicar em 'Ver comprovante' na tela de Informações de Oportunidade.
- Figma atualizado.

**Comment by pauloamoreira** [comment]
@luannaalves atualizei o layout do botão "Imprimir", de modo a atender os padrões do Mapa.
