### ISSUE TITLE
Selos: adicionar interface gráfica

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#62]

**Comment by vicmagpac** [comment]
Ferramenta já possui interface gráfico para o usuário saasSuperAdmin.
![Captura de tela de 2020-12-14 14-57-54](https://user-images.githubusercontent.com/3487411/102117208-cf213b00-3e1c-11eb-8836-287fe94d86fc.png)
![Captura de tela de 2020-12-14 14-57-46](https://user-images.githubusercontent.com/3487411/102117212-cfb9d180-3e1c-11eb-8bba-dec58fb4d5d2.png)
