### ISSUE TITLE
Substituir Concessão OAuth 

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#620]
## **Objetivo**

**Como** gestor  
**Quero** usar uma linguagem que a pessoa usuária possa entender com facilidade
**Para** não gerar dúvidas ou inseguranças no que ela está fazendo/aceitando

## **Contexto**

Durante os testes notamos que ao cadastrar-se no IdSaúde, algumas pessoas sentiram-se inseguras em aceitar ou não a Concessão OAuth por não saber o que estavam aceitando, é necessário substituir o termo Concessão OAuth por “Concessão de Acesso a dados”, com uma frase que explique que o aceite é obrigatório e que os dados só serão utilizados como controle de acesso ao Mapa. 

## **Escopo UX
- [ ] Substituir o termo OAuth por “Concessão de Acesso a dados” no protótipo
- [ ] Incluir solução com frase que explique a obrigatoriedade no aceite 

## **Critérios de Aceitação**

- [ ] Aplicar solução no local indicado
- [ ] **Dado que** a pessoa usuária faz a inscrição em uma oportunidade
**Quando** ela tiver que aceitar os termos de concessão de dados
**então** ela saberá o que está aceitando e qual a finalidade da ação

## Observações
Foi verificado que essa solução foi implementada no ambiente de produção, mas ela precisa estar presente também na homologação devido aos testes de usabilidade.

**Comment by thaistoscano** [comment]
@RaniGub @MayaraMonte Se colocarmos em homologação a versão da produção resolveria?

**Comment by Junior-Shyko** [comment]
Lembrando que o termo Concessão OAuth só aparece no servidor de homologação que o mesmo está diferente do servidor de produção.

**Comment by Junior-Shyko** [comment]
### Servidor de Homologação
![image](https://user-images.githubusercontent.com/7341117/148767651-f29edb19-409b-4900-adf5-02d4ecfd4225.png)

**Comment by Junior-Shyko** [comment]
### Servidor de Produção
![image](https://user-images.githubusercontent.com/7341117/148767759-4d6a7dd8-d09b-4812-8770-c11c7695f3b1.png)

**Comment by Junior-Shyko** [comment]
Issue contemplada em Sprint
[Link da Issue](https://github.com/EscolaDeSaudePublica/mapadasaude/issues/463)

**Comment by RaniGub** [comment]
> @RaniGub @MayaraMonte Se colocarmos em homologação a versão da produção resolveria?

Olá Thaís, sim, acabei de fazer um teste na produção e ela poderia ser aplicada no ambiente de homologação, no escopo da tarefa faltou essa observação, irei criar. Precisamos que os dois ambientes estejam com as mesmas soluções implementadas devido aos testes.

**Comment by thaistoscano** [comment]
Dessa forma, não há necessidade de protótipo.

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/620?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
Ficou definido que contemplará somente o que está na issue. Visto que trazer a versão que está na produção para a homologação demandaria bem mais que uma issue.

**Comment by thaistoscano** [comment]
Atividade executada somente em homologação. Em produção já consta a versão mais atualizada.
