### ISSUE TITLE
Mensagem para informar mudança de página

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#621]
## **Objetivo**

**Como** gestor  
**Quero** melhorar a experiência de redirecionamento de páginas durante a inscrição
**Para** evitar que a pessoa usuária fique sem entender o que está acontecendo caso saia da página de inscrição por acidente

## **Contexto**

Durante os testes ao clicar sem querer no nome do agente responsável a pessoa é direcionada para outra página e não recebe aviso de que está deixando o ambiente de inscrição. É preciso que qualquer clique que seja dado no ambiente de inscrição e que leve a pessoa a deixar o ambiente, seja informado para que a pessoa saiba o que está acontecendo e possa cancelar a ação se desejar. 

(Sugestão: Mostrar uma mensagem: "Você está saindo da seção de inscrição. Você pode continuar sua inscrição pelo menu Minhas Inscrições depois. Tem certeza disso?" - Se a pessoa clicar em 'Sim' a inscrição deve ser salva para posterior edição.)

## **Escopo UX
- [x] Propor a visualização de mensagem no momento do redirecionamento
- [x] Incluir solução no protótipo  

## **Escopo DEV
- Deverá ser inserida uma notificação de aviso ao candidato informando que este está deixando a sessão de inscrição antes de tê-la concluído.
- A notificação deverá surgir vinculada a qualquer link da página que não faça parte da jornada de inscrição do candidato.
- A notificação deverá ser executada conforme protótipo realizado pela equipe do DesignLab.

## **Critérios de Aceitação**

- [x] **Inserir notificação de mudança de página no processo de inscrição**
**Dado que** a pessoa usuária clica em algum link que não faça parte da jornada de inscrição
**Quando** quando ela for ser redirecionada para outra página
**então** ela recebe uma notificação informando que ela está saindo do ambiente de inscrição e perguntando se ela deseja ou não prosseguir com a ação.

## Observações
Ver protótipo a seguir: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/?node-id=2041%3A1569

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/?node-id=2041%3A1569

**Comment by RaniGub** [comment]
Protótipo validado.

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/621?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by fernandafnascmnt** [comment]
Favor rever protótipo do Figma. @MayaraMonte @RaniGub

**Comment by fernandafnascmnt** [comment]
Esta mensagem atual deverá ser reavaliada quando migrar para a nova versão porque na nova versão tem um timeout de  auto save e não mais salva no momento que o usuário sai do campo.

**Comment by RaniGub** [comment]
Pareado com a @FernandaNascimento26

**Comment by luannaalves** [comment]
Validado na homologação.

**Comment by luannaalves** [comment]
Validado na produção.
