### ISSUE TITLE
 Indicação visual dos campos pendentes quando enviar a inscrição 

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#622]
## **Objetivo**

**Como** gestor  
**Quero** melhorar a indicação visual de pendências de documentos ou informações obrigatórias 
**Para** que a pessoa consiga identificar com a facilidade o que está faltando para finalizar a inscrição

## **Contexto**

No momento do teste quando a pessoa clicou em 'Enviar inscrição' apareceu um pop-up de erro (sem nada escrito). Levou um tempo até a pessoa perceber que havia deixado de anexar o arquivo do 'Plano de Trabalho', pois não havia nenhum indicador visual que essa era a pendência.
É necessário fazer uma indicação visual dos campos pendentes ao clicar em 'Enviar inscrição' e mostrar a mensagem dessa pendência no pop-up que surge, caso o mesmo permaneça.

## **Escopo UX
- [x] Avaliar qual a melhor maneira de indicar as pendências no momento da inscrição
- [x] Incluir solução no protótipo 

## **Escopo DEV
- Quando o usuário, candidato em uma oportunidade, for finalizar sua inscrição, caso haja alguma pendência de preenchimento de algum campo/documentação deverá aparecer uma notificação informando essa pendência e ainda especificando quais os campos estão pendentes de preenchimento.
- Para campos digitados com formato inválido ou quando o campo não tiver opção de uma máscara de formatação, também deverá aparecer uma notificação informando quais os campos devem ter o preenchimento revisto.
- Tais notificações devem seguir modelo apresentado pela equipe do DesignLab

## **Critérios de Aceitação**

- [x] Inserir notificação de campos pendentes quando usuário finalizar inscrição
**Dado que** a pessoa usuária esquece de preencher algum campo obrigatório ou incluir algum documento 
**Quando** ela for finalizar a inscrição
**então** ela recebe uma notificação informando que existem campos pendentes, e quais são esses campos 

- [x] Inserir notificação de campos com formato inválido quando usuário finalizar inscrição
**Dado que** a pessoa usuária haja preenchido algum campo com formatação inválida
**Quando** ela for finalizar a inscrição
**então** ela recebe uma notificação informando que existem campos pendentes, e quais são esses campos 

## Observações
Ver protótipo a seguir:
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/?node-id=2089%3A1695

- **Inserir bloqueio na finalização da edição para preenchimento dos campos obrigatórios**

- **Incluir validação na notificação de preenchimento dos campos de Agente responsável e Agente coletivo**

**Comment by RaniGub** [comment]
@MayaraMonte fiz um teste de inscrição e achei adequado a indicação do campo obrigatório. No entanto um aviso com as indicações das pendência deve ser de fato revisto.

Indicação de campo atual:
![Captura de Tela 2022-01-21 às 13.58.21.png](https://images.zenhubusercontent.com/6100319d73e73a075fefd717/0e603441-e862-4ac1-8aae-eb00529573f6)

Pop-up atual:
![Captura de Tela 2022-01-21 às 14.00.07.png](https://images.zenhubusercontent.com/6100319d73e73a075fefd717/45741595-b195-4c24-8e4a-7007d043a33d)

**Comment by RaniGub** [comment]
Protótipo adicionado.

**Comment by Junior-Shyko** [comment]
![Captura de tela de 2022-02-03 16-31-04.png](https://images.zenhubusercontent.com/61092b9464d7502ba0e520b9/6f5303aa-364c-49f9-9750-383793379ca9)

Atualmente pelo form build da aplicação ter campos que são dinâmicos e não possui validação, um pop-up com indicação de formato incorreto ficaria inviável.
Como por exemplo na imagem eu coloquei um campo de texto simples com a indicação que é data, nesse caso não teria como validar uma data. Pois é um campo que aceita qualquer caracteres.
Precisamos de alguma outra indicação. @RaniGub @pauloamoreira

**Comment by RaniGub** [comment]
@pauloamoreira por gentileza, dê uma olhada com o Junim.

**Comment by fernandafnascmnt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Dev-60f894f541f910001066bfd9/issues/EscolaDeSaudePublica/mapadasaude/622?planning-poker) with ZenHub @Junior-Shyko @pedrovitor074

**Comment by Junior-Shyko** [comment]
[Commit](https://github.com/EscolaDeSaudePublica/Saude/commit/7b0526a71d780c5abfbd3a7358f8006c71097a41)

**Comment by Junior-Shyko** [comment]
Atualização no [commit](https://github.com/EscolaDeSaudePublica/plugin-EditarInscricao/commit/47f3657983ab5a21e68e3f17f7847d726cb449c2)

**Comment by luannaalves** [comment]
Necessário validação com @RaniGub

**Comment by luannaalves** [comment]
Validado na homologação.

**Comment by luannaalves** [comment]
Validado na produção.
