### ISSUE TITLE
Revisar aviso de "Inscrição enviada"

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#623]
## **Objetivo**

**Como** gestor  
**Quero** melhorar a mensagem de confirmação de inscrição 
**Para** que a pessoa usuária possa ter a certeza que finalizou a inscrição com sucesso

## **Contexto**

Durante o teste identificamos uma dificuldade na visualização do aviso de confirmação de inscrição pois o mesmo possui uma relação de contraste muito baixa entre tipografia e plano de fundo, além do corpo excessivamente pequeno. Ainda entra em conflito com o título 'Formulário de Inscrição' que vem logo abaixo em uma hierarquia visual de nível maior. 

Além de ajustar esse aviso, verificar a possibilidade de incluir junto a essas informações que a pessoa pode ter acesso à inscrição pelo Menu 'Meu Perfil>Minhas Inscrições'.

## **Escopo UX
- [x] Revisar aviso de confirmação e ajustar para melhorar a visibilidade 
- [x] Ajustar hierarquia visual das informações
- [x] Incluir soluções no protótipo

## **Escopo DEV
- [ ] 

## **Critérios de Aceitação**

- [x] Aplicar solução no local indicado
- [x] **Dado que** a pessoa usuária faz a inscrição em uma oportunidade
**Quando** ela finaliza a inscrição
**então** ela recebe uma notificação visível de que a inscrição foi realizada com sucesso e que ela pode ter acesso à inscrição pelo Menu 'Meu Perfil>Minhas Inscrições'.

## Observações
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/?node-id=1999%3A1389

**Comment by thaistoscano** [comment]
@RaniGub coloca o print, por favor.

**Comment by RaniGub** [comment]
![Captura de Tela 2022-01-12 às 09 31 00](https://user-images.githubusercontent.com/79097920/149140822-7e03dbbd-08f3-4442-97df-27ca6a53ae15.png)

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/?node-id=1999%3A1389

**Comment by RaniGub** [comment]
Protótipo validado.

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/623?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco
