### ISSUE TITLE
Modificar tag do botão 'Baixar planilha'

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#624]
## **Objetivo**

**Como** gestor  
**Quero** ajustar um erro na função do botão "baixar" 
**Para** que a pessoa consiga baixar o item correto

## **Contexto**

Durante o teste a pessoa clicou no botão 'Visualizar Portfólio' e foi encaminhada para uma planilha do excel que difere do arquivo que havia sido feito o upload. Aparecendo o nome 'Baixar Planilha' ao invés de 'Baixar Arquivo'. O arquivo baixado de fato é uma planilha sem conexão com a inscrição.

## **Escopo UX
- [ ] Modificar tag do botão 'Baixar planilha' para 'Baixar arquivo'

## **Escopo DEV
- [ ] Vincular o arquivo enviado pela pessoa ao botão 'Baixar arquivo'

## **Critérios de Aceitação**

- [ ] Aplicar solução no local indicado
- [ ] **Dado que** a pessoa quer baixar o arquivo que anexou no momento da inscrição
**Quando** ela clicar em "baixar arquivo"
**então** ela deve conseguir baixar o arquivo escolhido

**Comment by RaniGub** [comment]
![Captura de Tela 2022-01-12 às 09 34 19](https://user-images.githubusercontent.com/79097920/149141244-df420feb-9ef7-498e-bc0e-d7542b76ea53.png)

**Comment by RaniGub** [comment]
Essa opção aparece quando você finaliza uma inscrição e clica no botão 'Visualizar Portfólio'

**Comment by RaniGub** [comment]
O @pauloamoreira levantou a possibilidade desse botão ser um legado do Mapa da Cultura, quando se clica para ver o Portfólio a pessoa deveria ser encaminhada para vídeos e a galeria do Artista. @thaistoscano você pode parear com ele essa tarefa? É preciso entender melhor o contexto. 
Atualmente o botão 'Visualizar Portfólio' aparece no comprovante de inscrição mesmo sem a oportunidade requerer que um Portfólio seja anexado. Em situações que não há necessidade, o botão deve ficar oculto. Caso contrário, deveria baixar um arquivo diretamente sem a necessidade de apresentação do pop-up.
