### ISSUE TITLE
Solução com explicação para as opções de gênero

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#626]
## **Objetivo**

**Como** gestor  
**Quero** fornecer informações mais claras sobre opções de gênero 
**Para** para que não haja dúvidas no momento da inscrição 

## **Contexto**
Durante os testes houveram hesitações no momento de informar qual era a sua opção entre as Opções de Gênero, provavelmente porque alguns termos ainda não são de domínio público ou de uso cotidiano. É necessário criar uma solução com explicação para cada uma das opções

## **Escopo UX
- [ ] Analisar a melhor forma de adicionar essa explicação no protótipo 
- [ ] Verificar explicação textual com a Clarisse

## **Escopo DEV
- [ ] 

## **Critérios de Aceitação**

- [ ] Aplicar solução no local indicado
- [ ] **Dado que** a pessoa usuária faz a inscrição em uma oportunidade
**Quando** ela vai preencher a opção de gênero 
**então** ela deve ter uma informação clara do significado das opções disponíveis para não gerar dúvidas 

## Observações
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/?node-id=2041%3A1597

**Comment by RaniGub** [comment]
É importante que a @Clarisse1983 participe dessa solução. A sugestão é um ícone para infos ao lado do campo/título (modal) com as informações. @matheuscpl deve avaliar.

**Comment by ClarisCaval** [comment]
Gente, tinha uma tarefa bem parecida no board do Mapa da Saúde, e fiz essa proposta de textos, com possibilidade de desdobrar para um 'Saiba mais':
https://docs.google.com/document/d/1U_GUrBsm99hzjbp-W2z5bjDbUqKl776LYX7RFL6AeQc/edit

**Comment by RaniGub** [comment]
Protótipo validado.

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/626?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by fernandafnascmnt** [comment]
Observação: Em todos os locais os quais o campo de gênero for adicionado, deve haver esta explicação. Uma oportunidade pode ou não conter este campo, já que ele é personalizável.
