### ISSUE TITLE
Criar botão que possibilite alterar inscrições

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#629]
## **Objetivo**

**Como** pessoa usuária  
**Quero** editar minha inscrição
**Para** substituir/corrigir alguma informação

## **Contexto**
Atualmente no Mapa quando a inscrição é enviada não é possível alterar, sem que ela seja passada pra rascunho. A ideia é que seja criado um botão que, uma vez que o edital esteja aberto seja possível você alterar sua inscrição sem que seja passada para rascunho. Considerando que o design não sabe das limitações do Mapa, foi sugerido a combinação de 4 possíveis cenários, com suas respectivas experiências para serem analisados. O fluxo servirá também para evolução de cada cenário com o passar do tempo.

## **Escopo UX
- [x] Propor fluxo da experiência
- [x] Propor telas da experiência

## **Escopo DEV
- Analisar qual o caminho mais adequado a ser seguido com base nas limitações do mapa
- Implementar as janelas pou-up de notificações conforme figma

## **Critérios de Aceitação**

- [x] Analisar qual o caminho mais adequado a ser seguido e implementar a solução
**Dado que** os Devs analisem o cenário de limitações do Mapa
**Quando** eles visualizam o fluxo dos cenários possíveis
**então** tomam uma decisão qual de caminho a ser implementado mais adequado

- [x] Inserir botão de edição para inscrição
**Dado que** a pessoa queria editar sua inscrição no período em que a oportunidade esteja aberta
**Quando** ela clica em 'Editar inscrição' na tela de informações da oportunidade
**então** é possível alterar suas informações

- [x] Botão de Finalizar Edição
**Dado que** o candidato 
**Quando** clique no botão para editar a inscrição  
**Então** ao final já deverá aparecer o botão de FINALIZAR EDIÇÃO 

- [x] Botão de Finalizar Inscrição
**Dado que** o candidato 
**Quando** quando conclua sua inscrição  
**Então** ao final já deverá aparecer o botão de FINALIZAR INSCRIÇÃO

- [x] Configurar Avaliador
**Dado que** o administrador da oportunidade
**Quando** iniciar a criação da oportunidade ao optar por permitir edição de inscrição
**Então** o sistema só permitirá definir a comissão de avaliação após o término do período de inscrições

- [x] Exibir notificações pou-up conforme figma
**Dado que** o usuário candidato em uma oportunidade
**Quando** utilize os botões de edição/finalização de sua inscrição
**Então** o sistema apresente notificações pou-up de confirmação para suas ações

## Observações
Devs, como não sabemos o real cenário e limitações do Mapa, sugerimos a combinação de 4 possíveis cenários para serem analisados com suas respectivas telas. O fluxo servirá também para evolução de cada cenário com o passar do tempo.

Fluxo:
![Captura de Tela 2022-01-17 às 09 42 19](https://user-images.githubusercontent.com/79097920/149771439-4ab17ce8-afc5-486a-8ec0-6f85e9dd5f94.png)

Figma:
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=1987%3A1466

**Comment by pauloamoreira** [comment]
@thaistoscano boards com as indicações de aplicação da funcionalidade de 'Edição da Inscrição' (durante o período de inscrição) estão disponíveis nas observações desta tarefa.

**Comment by RaniGub** [comment]
Solução em análise.

**Comment by RaniGub** [comment]
@thaistoscano a tarefa desencadeia experiências em outras telas. Criei um fluxo para o cenário de edição de oportunidade com inscrição já realizada. É preciso editar o escopo. Talvez você veja necessidade de desdobrar essa tarefa em mais de uma. 
![Captura de Tela 2022-01-13 às 00 35 11](https://user-images.githubusercontent.com/79097920/149261748-e2e7e89a-66be-4c08-9b27-7d2c50ac5352.png)

**Comment by RaniGub** [comment]
@pauloamoreira trouxe novas informações após pareamento com a @thaistoscano. Com base nisso foram acrescentadas condicionais no Fluxo para situações onde a oportunidade permitir mais de uma inscrição na mesma categoria/perfil. 

Thaís apontou que a situação ideal é o substituição/edição dos dados de uma inscrição já enviada aconteça automaticamente no momento da edição pela pessoa, sem a necessidade da pessoa clicar no botão 'enviar inscrição', sem produzir um novo rascunho ou gerar um novo número de inscrição. Faremos um novo caminho para a situação caso o time de desenvolvimento conclua que isso não é possível ou não será aplicado agora. 

Adicionamos grupos de experiência que podem ser atendidos em tarefas diferentes, mas uma complementa a outra em algum nível.

Paulo irá atualizar as telas.

**Comment by RaniGub** [comment]
Atualização: Vamos dividir a experiência por issues, cada uma terá seu fluxo com telas. Vamos começar editando o escopo dessa para atender a demanda específica solicitada.

**Comment by RaniGub** [comment]
Protótipo validado.

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/629?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by thaistoscano** [comment]
Add pontuação 40, pois os devs não conseguem votar mais que 21.

**Comment by Junior-Shyko** [comment]
Eu tive que diminuir o tamanho do numero da inscrição por conta do layout mobile.![Captura de tela de 2022-01-18 13-24-54.png](https://images.zenhubusercontent.com/61092b9464d7502ba0e520b9/c4b20b0d-f6e9-4ff9-9a31-bd122cd9be68)

**Comment by RaniGub** [comment]
@Junior-Shyko me deparei com uma tarefa que fez eu retornar e revisar um ponto nessa. Vi que foi utilizado no protótipo um layout antigo que não possibilitava a adição do botão editar inscrições devido ao espaço.

Atualizei o protótipo com uma tela do ambiente de produção que possibilita a exibição do botão. Deixei um marcador vermelho para você visualizar a adição no fluxo e tela.
![Captura de Tela 2022-01-20 às 14 08 38](https://user-images.githubusercontent.com/79097920/150388210-55663bc8-b54d-4800-a479-e17895e83dbe.png)
![Captura de Tela 2022-01-20 às 14 08 53](https://user-images.githubusercontent.com/79097920/150388252-1f50839b-01fd-4774-91d6-c0b7ca516d2b.png)

**Comment by RaniGub** [comment]
Ah, estão atualizadas no protótipo. Se precisar de algo me chame.

**Comment by Junior-Shyko** [comment]
![Captura de tela de 2022-01-21 15-04-30.png](https://images.zenhubusercontent.com/61092b9464d7502ba0e520b9/035aaf56-406d-48a6-8240-b06ab77c25b1)

**Comment by Junior-Shyko** [comment]
![Captura de tela de 2022-01-21 15-04-47.png](https://images.zenhubusercontent.com/61092b9464d7502ba0e520b9/cfd3b8c9-f72f-4a07-9ab5-a04e83ed412c)

**Comment by Junior-Shyko** [comment]
@RaniGub essa mensagem aparece após da o click em Finalizar Inscrição, mas como agora vai ter a opção de editar os dados, então esse aviso precisa de um Update.

![Captura de tela de 2022-01-24 11-01-20.png](https://images.zenhubusercontent.com/61092b9464d7502ba0e520b9/192eecbe-4663-44c0-8ead-2d6fc2df670c)

**Comment by pauloamoreira** [comment]
@Junior-Shyko há um novo layout disponível para esse pop up neste board: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2378%3A3185

**Comment by pauloamoreira** [comment]
![final_inscrição](https://user-images.githubusercontent.com/79201419/150849206-2b4f7da8-c70d-4fe8-8be9-d0851e409de0.jpg)

**Comment by Junior-Shyko** [comment]
Tarefa necessita da criação de um plugin e já inciado no link a baixo.
https://github.com/EscolaDeSaudePublica/plugin-EditarInscricao

**Comment by RaniGub** [comment]
@Junior-Shyko ainda é possível atualizar a mensagem do pop-up? Conversando com o Paulo chegamos a esse consenso.
![Captura de Tela 2022-01-28 às 10 42 07](https://user-images.githubusercontent.com/79097920/151557025-274f3671-271e-40d2-be32-3695c97d34ba.png)

**Comment by Junior-Shyko** [comment]
Iniciado no plugin a criação do botão de editar a inscrição pelo candidato.
Commit: https://github.com/EscolaDeSaudePublica/plugin-EditarInscricao/commit/abcb1932e63983c2bcc91c694ec2330f17ef3862

**Comment by Junior-Shyko** [comment]
Atualização:
https://github.com/EscolaDeSaudePublica/plugin-EditarInscricao/commit/c8041ec5dbded59a3223d5d3e648b6e7fe728008

**Comment by Junior-Shyko** [comment]
Revisto com o @pauloamoreira 

- Remover bo botão EDITAR INSCRIÇÃO a classe registration-fieldset

- Ajustar layout para mobile em todas as versões

- Ajusta o layout do botão imprimir PDF para como está no [figma](https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2380%3A3200)

- Colocar editar ao lado do IMPRIMIR EM PDF no rodapé do comprovante de inscrição

**Comment by Junior-Shyko** [comment]
Atualização no plugin dessa atividade. [Link](https://github.com/EscolaDeSaudePublica/plugin-EditarInscricao/commit/13306572034244140ecc38b070063e362ab78bcf)

**Comment by Junior-Shyko** [comment]
- Atualizado plugin de edição de inscrição nesse [commit](https://github.com/EscolaDeSaudePublica/plugin-EditarInscricao/commit/27fecf1590627a18aa44017ecc0cbd589e6e89fc)
- Atualizado plugin PDFRepor nesse [commit](https://github.com/EscolaDeSaudePublica/plugin-PDFReport/commit/20c9c069df7874d71d044fdd8dd42b511edb384e)

**Comment by luannaalves** [comment]
@uira sugerimos realizar validação institucional dessa atividade na homologação.

**Comment by luannaalves** [comment]
@helenhilario gostaria de fazer essa validação na homologação?

**Comment by luannaalves** [comment]
Validado na produção.
