### ISSUE TITLE
Revisar experiência de resgate de uma inscrição de oportunidade no rascunho

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#630]
## **Objetivo**

**Como** gestor do Mapa
**Quero** ajustar a experiência numa oportunidade no rascunho
**Para** a pessoa conseguir editar e enviar de forma mais intuitiva

## **Contexto**

Após a reabertura da inscrição em uma oportunidade, a pessoa conseguirá resgatar sua inscrição do rascunho.

## **Escopo UX
- [x] Sugerir proposta de modificação nas telas onde a pessoa tem acesso à edição da inscrição em uma oportunidade.

## **Escopo DEV
- Inserir botão Editar inscrição no Menu Minhas Inscrições, aba de Rascunhos 
- No Menu principal de uma oportunidade, na tabela Minhas Inscrições deverá aparecer o indicativo de inscrição em rascunho e o botão para Editar inscrição, conforme protótipo.
- Quando o usuário iniciar a inscrição, e na oportunidade só seja possível inscrever-se uma única vez, então o campo para fazer inscrição na tela de informações da oportunidade, deverá ser ocultado. E quando possa inscrever-se mais de uma deverá ficar visível.
- Caso o candidato possa se inscrever mais de uma vez na mesma categoria de uma oportunidade, então antes do usuário ser encaminhado para uma nova inscrição, ele deverá concluir a inscrição em rascunho anterior, sendo apresentada umas mensagem pop-up.
- Ajustar link Acessar Inscrição para forma de botão, a ser inserido ao lado do botão Editar Inscrição
- Na tela de informações da oportunidade, tabela de minhas inscrições, deverá ser renomeado o botão de Editar e enviar para Editar Inscrição.
- Na tela de informações da oportunidade, tabela de minhas inscrições, deverá ser inserido o botão Ver comprovante ao lado do botão Editar Inscrição, o qual deverá levar ao comprovante de inscrição.
- Verificar situação da tabela Minhas inscrições para o Mobile.
- Deverá ser implementado conforme protótipo apresentado pelo DesignLab.

## **Critérios de Aceitação**

- [x] **Inserir Botão Editar inscrição, no menu Minhas Inscrições, aba de Rascunhos** 
**Dado que** a pessoa queria continuar sua inscrição incompleta
**Quando** ela clicar em "Editar inscrição", na página de rascunho
**então** ela acessa a tela de edição do formulário

- [x] **Informação de inscrição em rascunho**
**Dado que** a pessoa não tenha concluído a inscrição em uma oportunidade
**Quando** entre na tela de informações da oportunidade
**então** visualiza um indicativo de inscrição em rascunho e o botão para editar a inscrição

- [x] **Ocultar campo para fazer inscrição após usuário já ter realizado (em casos que só possa inscrever-se uma única vez na oportunidade)**
**Dado que** em uma oportunidade o usuário só possa inscrever uma única vez 
**Quando** ele realizar sua inscrição
**então** o campo para fazer inscrição deverá ser ocultado

- [x] **Completar inscrição em rascunho antes de criar uma nova inscrição na mesma categoria de uma oportunidade**
**Dado que** a pessoa tenha uma inscrição em rascunho numa categoria de oportunidade que aceita mais de uma inscrição na mesma categoria
**Quando** ela clicar em "Fazer inscrição"
**então** visualizar o pop-up para conclusão do rascunho anterior

- [x] **Renomear botão Editar e enviar para Editar inscrição**
**Dado que** a pessoa na tela de informações da oportunidade
**Quando** visualize a tabela de minhas inscrições
**então** encontre o botão de nome Editar Inscrição.

- [x] **Inserir botão Ver comprovante**
**Dado que** a pessoa na tela de informações da oportunidade
**Quando** visualize a tabela de minhas inscrições
**então** encontre o botão Ver comprovante, para visualizar o comprovante de inscrição.

- [x] **Ajustar link Acessar Inscrição para forma de botão.**
**Dado que** a pessoa esteja na página de Minhas Inscrições
**Quando** acesse a aba de Rascunho
**então** encontre o botão Acessar Inscrição, ao lado do botão Editar Inscrição.

## Observações
Ver protótipo a seguir:
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2036%3A1783

Ver quadros A e B da tela de informações da oportunidade:
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=1987%3A1466

**Comment by RaniGub** [comment]
![Captura de Tela 2022-01-13 às 01 02 41](https://user-images.githubusercontent.com/79097920/149263848-5fb136be-0068-4888-9c9c-915385d5f5ab.png)

**Comment by RaniGub** [comment]
Escopo revisado, protótipo adicionado.

**Comment by Junior-Shyko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Dev-60f894f541f910001066bfd9/issues/EscolaDeSaudePublica/mapadasaude/630?planning-poker) with ZenHub @pedrovitor074 @victorMagalhaesPacheco @FernandaNascimento26

**Comment by luannaalves** [comment]
validado na homologação.

**Comment by luannaalves** [comment]
@helenhilario atividade para validação institucional.

**Comment by luannaalves** [comment]
Validado na produção.
