### ISSUE TITLE
Sincronizar campos de opções presentes no menu 'Meu Perfil' e Menu lateral esquerdo

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#631]
## **Objetivo**

**Como** desenvolvedor  
**Quero** fazer com que as opções presentes nos menus sejam as mesmas
**Para** para não confundir as pessoas

## **Contexto**
Foi observado que as opções de menu disponíveis no menu 'Meu Perfil' e menu lateral esquerdo (quando é acessada uma seção) divergem no Mapa da Saúde.

## **Escopo UX
- [x] Apontar o local e propor a solução

## **Escopo DEV
- [ ] Sintonizar as opções disponíveis nos dois menus

## **Critérios de Aceitação**

- [ ] Sincronizar as opções disponíveis nos dois menus
**Dado que** a pessoa acesse uma seção do Mapa pelo menu 'Meu Perfil'
**Quando** ela visualizar o menu lateral esquerdo da seção
**então** ela vai entender que se trata das mesmas opções do menu 'Meu Perfil'

## Observações
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2152%3A3957

**Comment by RaniGub** [comment]
Figma adicionado.

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/631?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by pedrovitor074** [comment]
@RaniGub Conversando com os meninos na daily hoje, vimos que já seria interessante atualizar os ícones que estão repetidos ( Oportunidades, Inscrições e Recursos ), pode disponibilizar esses ícones?

**Comment by RaniGub** [comment]
@pedrovitor074 pode parear comigo?

**Comment by RaniGub** [comment]
Sair:
https://fontawesome.com/v4.7/icon/sign-out

Minhas inscrições:
https://fontawesome.com/v4.7/icon/pencil-square-o

Meus recursos:
https://fontawesome.com/v4.7/icon/exchange

Minhas oportunidades:
https://fontawesome.com/v4.7/icon/sticky-note-o

Obs.: Nas opções não encontrei algo que representasse legal os Meus Recursos. Vamos colocar o sugerido dando a ideia de que alguém interpôs algo e aguarda retorno do pedido. Com o tempo a gente vê se saiu algum ícone melhor na lista.
