### ISSUE TITLE
Rever apresentação de elementos em Minhas inscrições

### ISSUE THREAD

**Issue by RaniGub** [FeliciLab/mapadasaude#634]
## **Objetivo**

**Como** pessoa usuária
**Quero** ter uma melhor experiência na visualização das informações em minha inscrições
**Para** conseguir visualizar as informações de maneira mais clara

## **Contexto**

Após modificações sugeridas na tarefa #629 com a possibilidade de edição de inscrições, é importante dispor dos mesmos elementos, mesmos comportamentos de condicionais e mesma identidade na seção 'Minhas inscrições', para proporcionar familiaridade a pessoa nas ações disponíveis para execução.

## **Escopo UX
- [x] Rever apresentação para acessar opções disponíveis no protótipo

## **Escopo DEV
- [ ] Rever apresentação e disposição dos botão de 'Minhas inscrições'
- [ ] Implementar indicativo de recurso se disponível ou não, considerando o período

## **Critérios de Aceitação**

- [ ] Rever apresentação e disposição dos botão de 'Minhas inscrições'
**Dado que** a pessoa acesse 'Minhas inscrições'
**Quando** visualizar a seção
**então** ela terá a mesma experiência visual proposta no protótipo

- [ ] Implementar indicativo de recurso se disponível ou não, considerando o período
**Dado que** a pessoa não tenha sido selecionada numa oportunidade
**Quando** ela visualiza a oportunidade em 'Minhas inscrições'
**então** consegue ver informações acerca da disponibilidade de recurso e data limite

## Observações
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2175%3A3519

**Comment by RaniGub** [comment]
Protótipo adicionado.

**Comment by luannaalves** [comment]
Atividades já contempladas pela issue #633
