### ISSUE TITLE
Melhorar experiência da página 'agenda'

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#635]
## **Objetivo**

**Como** persona  
**Quero** ter acesso a agenda da oportunidade de maneira rápida 
**Para** conseguir visualizar de maneira rápida os prazos estipulados para a oportunidade 

## **Contexto**

- Dentro da oportunidade existe uma aba para 'agenda' o que não fica claro é se o conteúdo que deveria aparecer ali se trata da agenda com os prazos da oportunidade ou alguma outra coisa, isso acaba confundindo a pessoa usuária que vai identifica a aba como um atalho para ter acesso rápido as informações de prazo sem precisar abrir todo o edital. 

## **Escopo UX**

- [x] Pensar na melhor forma de exibir a agenda da oportunidade na aba 'agenda'

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** acesso a oportunidade 
**Quando** vou até a aba 'agenda'
**então** encontro os prazos estipulados para determinada oportunidade

# Observações

**Comment by MayaraMonte** [comment]
![image](https://user-images.githubusercontent.com/67759144/149823154-ef386cb2-a670-40fa-9c8f-1eb65bfc2e69.png)

**Comment by RaniGub** [comment]
Rever o escopo de Agenda.

**Comment by RaniGub** [comment]
A aba "Agenda" é vinculada ao relacionamento que um Evento tem a um Projeto. Para que as informações da aba "Agenda" apareçam no Projeto em questão, é necessário que os eventos sejam cadastrados no Projeto. Atualmente a edição de Eventos no Mapa está desabilitada, então não é necessário que a aba "Agenda" seja apresentada para pessoa usuária.

Análise UX:
Ocultar aba "Agenda" das oportunidades.

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/635?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by fernandafnascmnt** [comment]
@RaniGub @MayaraMonte - No texto da atividade, vocês cirtam o aparecimento da agenda em uma oportunidade... Porém o print é da página do **Projeto** 26... Só para confirmar, seria da página do projeto, que é a página que exibe a aba inscrições onde a mesma exibe todas as oportunidade abertas para aquele projeto?

**Comment by fernandafnascmnt** [comment]
Outra dúvida: Haja visto o texto acima, escrito pelo @Rani, _"Atualmente a edição de Eventos no Mapa está desabilitada, então não é necessário que a aba "Agenda" seja apresentada para pessoa usuária."_... Retiro a aba agenda apenas no projeto ou nos demais locais (agente, espaço, por exemplo)?

**Comment by RaniGub** [comment]
@FernandaNascimento26 acho que não é necessário que a aba "Agenda" apareça mais em nenhum lugar, por enquanto. Pelo que entendi do Uirá num papo em out/2021 na V1 da AI, ela só puxa informações de Eventos que estão inseridos em Projetos. Então é preciso que tenha um Agente responsável pelo cadastro do Evento que consequentemente precisaria acontecer em um Espaço. Então as entidades funcionariam somente como um Filtro de visualização mesmo:
Se Agente: Vejo a Agenda de um Evento que vai acontecer em um Espaço cadastrada por aquele Agente.
Se Espaço: Vejo a Agenda de um Evento cadastrada por um Agente naquele Espaço.
Se Evento: Vejo Agenda com informações dos Eventos, como Espaço que irá acontecer e Agente responsável pelo cadastro.

**Comment by RaniGub** [comment]
Info atualizada: Out/2021

**Comment by luannaalves** [comment]
Validado na homologação.

**Comment by luannaalves** [comment]
Validado na produção.
