### ISSUE TITLE
Analisar a necessidade do botão 'baixar planilha' na agenda da oportunidade

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#636]
## **Objetivo**

**Como** gestor
**Quero** entender qual a funcionalidade do botão 'baixar planilha'
**Para** me certificar de que ele está funcionando corretamente

## **Contexto**

- Na agenda da oportunidade existe um botão chamado 'baixar planilha', quando clicamos no botão ele baixa uma planilha em branco.

## **Escopo**

- [ ] Analisar funcionalidade do botão

## **Fora de Escopo**

- 

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** o botão está disponível na página 
**Quando** clico no botão 
**então** ele funciona de forma correta baixando o arquivo correspondente aquela página

# Observações

**Comment by MayaraMonte** [comment]
![image](https://user-images.githubusercontent.com/67759144/149824555-9420b9d6-828d-41f3-a96a-16d997eebf9c.png)

**Comment by MayaraMonte** [comment]
![image](https://user-images.githubusercontent.com/67759144/149824627-d0e3a958-9426-471a-b82a-1e5f5cc56b76.png)

**Comment by RaniGub** [comment]
O botão deixará de ser acessado após a ocultação da aba "Agenda" da tarefa #635
