### ISSUE TITLE
Alterar e-mail de envio da confirmação de inscrição

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#641]
## **Objetivo**

**Como** administrador do mapa
**Quero** configurar e-mail não responda
**Para** não receber e-mails com assuntos que digam respeito a cada oportunidade

## **Contexto**
Atualmente os candidatos retornam ao e-mail do Mapa de confirmação de inscrição com dúvidas sobre os eventos, e a equipe do Mapa não possui as respostas. O usuário deve entrar em contato diretamente com os organizadores e não com o e-mail de confirmação da inscrição emitido pelo sistema. Desse modo, propõe-se alterá-lo.

-Inserir o seguinte texto para e-mail automático do não responda:

Este é um e-mail automático, gentileza não responder. Para dúvidas sobre sua inscrição verifique os contatos na oportunidade na qual se inscreveu. Para dúvidas sobre o uso da plataforma Mapa da Saúde, estamos à disposição no e-mail [mapa@sus.ce.gov.br.](mailto:mapa@sus.ce.gov.br.)

## **Critérios de Aceitação**

- [x] Mudar o e-mail de envio (naoresponda.mapa@sus.ce.gov.br)
- [x] Configurar mensagem automática de retorno 
- [x] Realizar contato com a infra para a aplicação

# Observações

ex: Prototipo

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/641?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by fernandafnascmnt** [comment]
@Clarisse1983 , Bom dia! 
Poderia me dar um auxílio com o texto para esta atividade? 

Creio que talvez seria válido adicionar uma mensagem ao template atual da mensagem de confirmação, informando que aquele email é automático.

**Comment by ClarisCaval** [comment]
Oi Nanda! Estou com uma dúvida: será um email geral para toda e qualquer situação automática?
Pq se puder ser específica para as questões desse edital, seria legal usar a oportunidade para reforçar qual o canal certo. Tipo assim: Este é um email automático, gentileza não responder. Para dúvidas sobre sua inscrição, entre em contato com edital26@esp.ce.gov.br.
Mas se for geral, para tudo, sugiro  "Este é um email automático, gentileza não responder. Dúvidas sobre o Mapa, entre em contato com [email de suporte do Mapa]".

**Comment by RaniGub** [comment]
Acho a ideia da @Clarisse1983 bem pertinente. Cla a gente pode sugerir um modelo padrão e a informação mudar a cada edital. Não sei se é possível criar um campo no momento da criação da oportunidade para que a pessoa insira o e-mail de referência para dúvidas @FernandaNascimento26 ai o e-mail puxar esse campo.

**Comment by thaistoscano** [comment]
@Clarisse1983 Será para todas as oportunidades, sejam da ESP ou externas, então não temos um e-mail "geral" para esse tipo de suporte (o dono na oportunidade que deve disponibilizar o contato). Eu pensei em algo do tipo... "Este é um email automático, gentileza não responder. Para dúvidas sobre sua inscrição verifique os contatos na oportunidade que está inscrito..."

**Comment by ClarisCaval** [comment]
Tendi @thaistoscano. Quando falei em suporte, foi no sentido mais geral mesmo, porque imagino que as pessoas tenham pelo menos dois tipos de dúvidas que já podemos presumir: sobre a oportunidade e sobre a plataforma em si. Assim, seria legal fazer uma orientação básica. Tipo:
 "Este é um email automático, gentileza não responder. Para dúvidas sobre sua inscrição verifique os contatos na oportunidade na qual se inscreveu. Para dúvidas sobre o uso da plataforma Mapa da Saúde, estamos á disposição no email [tal]."

**Comment by thaistoscano** [comment]
mapa@sus.ce.gov.br

**Comment by RaniGub** [comment]
> Acho a ideia da @Clarisse1983 bem pertinente. Cla a gente pode sugerir um modelo padrão e a informação mudar a cada edital. Não sei se é possível criar um campo no momento da criação da oportunidade para que a pessoa insira o e-mail de referência para dúvidas @FernandaNascimento26 ai o e-mail puxar esse campo.
@thaistoscano e essa sugestão que dei? Seria possível pelo desenvolvimento @Junior-Shyko ?

**Comment by pedrovitor074** [comment]
Aguardando somente a liberação do e-mail por parte da infra.

**Comment by vicmagpac** [comment]
Necessário ser adicionado a nova variável de ambiente no docker compose:  `- MAILER_STREAMOPTIONS_DISABLED_VERIFYPEER=true`

**Comment by luannaalves** [comment]
![image](https://user-images.githubusercontent.com/74267308/153589765-eeb30d83-76d0-44cd-ae67-a2abbfec65ae.png)
Validado na homologação. @victorMagalhaesPacheco necessidade apenas de corrigir a crase do a, na frase ...à disposição no e-mail.

**Comment by luannaalves** [comment]
Este é um e-mail automático, gentileza não responder. Para dúvidas sobre sua inscrição verifique os contatos na oportunidade na qual se inscreveu. Para dúvidas sobre o uso da plataforma Mapa da Saúde, estamos à disposição no e-mail [mapa@sus.ce.gov.br.](mailto:mapa@sus.ce.gov.br.)

**Comment by vicmagpac** [comment]
@luannaalves atualização realizada com sucesso.

**Comment by luannaalves** [comment]
validado na produção.
