### ISSUE TITLE
Aplicar selos via banco de dados para eventos específicos

### ISSUE THREAD

**Issue by thaistoscano** [FeliciLab/mapadasaude#642]
## **Objetivo**

**Como** administrador do Mapa da Saúde
**Quero** aplicar selos diretamente no banco
**Para** certificar oportunidades

## **Contexto**
Em virtude da necessidade de realizar certificações para as oficinas do CEVIG de forma rápida, deve-se aplicá-los por meio do banco. Evento: https://mapa.sus.ce.gov.br/projeto/18/
-

## **Critérios de Aceitação**

- [x] aplicar selos para cada uma das oportunidades do projeto acima
-  [ ] Verificar se não houve quebra/alterações de dados

# Observações

ex: Prototipo

**Comment by thaistoscano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Refinamento-610039a15670a0000e67211f/issues/EscolaDeSaudePublica/mapadasaude/642?planning-poker) with ZenHub @FernandaNascimento26 @Junior-Shyko @lucastandy @pedrovitor074 @victorMagalhaesPacheco

**Comment by Junior-Shyko** [comment]
Qual seria o selo especificamente? @helenhilario @luannaalves @thaistoscano

**Comment by Junior-Shyko** [comment]
Em conversa com o @Wanderley97 , foi percebido que os selos estão sendo aplicados normalmente.
Não havendo necessidade de alterar nada no banco de dados.
