### ISSUE TITLE
Solução de navegação nas páginas de uma oportunidade

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#653]
## **Objetivo**

**Como** designer
**Quero** melhorar a experiência de navegação entre as páginas de uma oportunidade   
**Para** evitar que a pessoa usuária fique perdida ao tentar retornar ou avançar na navegação das  páginas de uma oportunidade.

## **Contexto**
- A pessoa usuária, ao acessar a página de uma oportunidade, clica no botão "Fazer Inscrição" e é levada para o formulário de inscrição da oportunidade, mas nesse formulário não há link de retorno, além do retorno no próprio navegador (que conduz à pagina com status da oportunidade, não para a página anterior), gerando a possibilidade de erro, pois a pessoa usuária pode se perder. 

- Acima do banner da oportunidade há um texto com o nome da Oportunidade (ou Projeto Pai) que é um link para a página principal da oportunidade, mas, além disso não ficar claro para a usuária, na visão desktop da página do formulário de inscrição este texto/link não está visível (na visão mobile desta página o texto com link é visível). 

- É necessário criar uma solução de navegação pelas páginas da oportunidade, de modo a garantir que a pessoa usuária possa fluir na experiências entre as páginas, sem o risco de se perder.

## **Escopo UX**
- [x] Pensar em uma solução que possibilite que a usuária consiga percorrer as páginas de uma oportunidade de maneira fácil e intuitiva.

## **Escopo DEV**
- [x] implementar a solução indicada no protótipo.

## **Critérios de Aceitação**
- [] Garantir a plena navegação pelas páginas da oportunidade  
**Dado que** a pessoa usuária
**Quando** acessa as páginas de uma oportunidade 
**então** pode percorrer as páginas, retornando ou avançando, de forma fácil e intuitiva, sem se perder.

# Observações
Protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2964%3A3363

**Comment by RaniGub** [comment]
@pauloamoreira @MayaraMonte quando algum de vocês pegar essa tarefa eu penso que a melhor opção para isso é um Breadcrumb acima do banner do Projeto/Oportunidade. Se encontrarem uma opção mais adequada a gente vai conversando.

**Comment by pauloamoreira** [comment]
escopo e nome da tarefa atualizados a partir de refinamento com @luannaalves.

**Comment by RaniGub** [comment]
Paulo vamos conversar sobre essa tarefa.

**Comment by caldy94** [comment]
https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2964%3A3363

**Comment by RaniGub** [comment]
@pauloamoreira pfv alinhe essa tarefa com a @caldy94, pontos:
- Se vcs concluirem que o botão voltar deve ser inserido no corpo da oportunidade, acho que a linha das abas deve ser preservada;
- Atualizar as telas com base nas tarefas anteriores que já foram implementadas, como o botão imprimir na tela do comprovante de inscrição e o título do comprovante;
- Evitar solução de abas sobrepostas na mesma tela.

**Comment by caldy94** [comment]
Olá @RaniGub, vi seu comentário e fiz algumas correções e observações, dê uma olhada: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2964%3A3363

**Comment by caldy94** [comment]
Ps: Há um bug no comprovante de inscrição. Na parte superior, o título fica ocultado pelo banner 

![bug-01](https://user-images.githubusercontent.com/101121073/159047460-f838ff31-030b-4f44-a1a8-1121714e00d5.png)

**Comment by caldy94** [comment]
Protótipo atualizado. Tarefa finalizada.
