### ISSUE TITLE
Melhorar a experiência de criação de nova senha. 

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#654]
## **Objetivo**

**Como** designer  
**Quero** melhorar a experiência da pessoa usuária ao criar uma nova senha
**Para** evitar que a usuária se sinta perdida ao criar uma nova senha     

## **Contexto**
A pessoa precisa compreender a jornada para alteração de senha no Id Saúde.

## **Escopo UX**
- [x] Pensar em uma solução que possibilite que a usuária consiga trocar a senha de forma segura e intuitiva, sempre tornando possível que a usuária seja direcionada para a home do  Mapa já acessando com a nova senha.
- [x] Inserir solução no protótipo 

## **Escopo DEV**
**Quando o usuário estiver logado:**
- Implementar notificação de recebimento de e-mail para alteração de senha
- Enviar e-mail com mensagem automática de redefinição de senha
- Inserir campo e informativo para nova senha
- Redirecionar para home do mapa após redefinição de senha

**Quando o usuário não estiver logado:**
- Ao trocar a senha por uma nova, ele deverá ser direcionado para home do mapa e apresentado uma notificação que já está logado.

- Implementar conforme protótipo disponibilizado pelo DesignLab.

## **Critérios de Aceitação**
- [ ] **Implementar e-mail de alteração de senha**
**Dado que** quero alterar a senha do meu Id Saúde  
**Quando** clico em 'Esqueci a Senha', na página de login do Id Saúde
**então** recebo um email de confirmação, realizo a alteração e sou direcionada à página inicial do Mapa, sendo informada que estou logada e que minha senha foi alterada.

- [ ] **Redirecionar para home do Mapa quando usuário trocar senha**
**Quando** estiver logada, 
**então** em Meu Perfil > Painel de Controle, clico em 'Trocar a Senha', realizo a alteração e sou direcionada à página inicial do Mapa, sendo informada que estou logada e que minha senha foi alterada, recebo um email informando que a senha foi alterada.

# Observações
Ver protótipo a seguir: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2917%3A3433

**Comment by pauloamoreira** [comment]
.protótipo da solução produzido. aguardando validação de @RaniGub.

**Comment by RaniGub** [comment]
Necessita refinamento com a @luannaalves

**Comment by pauloamoreira** [comment]
nome da tarefa e escopo revisados a partir de refinamento realizado com @luannaalves em 01/03.

**Comment by RaniGub** [comment]
Protótipo validado.

P.S.:
@luannaalves @pauloamoreira o que você acha de criar uma tarefa para atender ao cenário da pessoa não saber o id (e-mail) e nem a senha? A solução seria permitir a inserção do CPF para que um cadastro duplicado não seja criado.

**Comment by RaniGub** [comment]
@pauloamoreira modificar o escopo.

**Comment by pauloamoreira** [comment]
Escopo atualizado
