### ISSUE TITLE
Botão Acessar Inscrição

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#656]
### Objetivo
**Como** usuário não inscrito
**Quero** ao visualizar a lista de oportunidades
**Então** encontrar disponível o botão com nome mais informações 

### Contexto
Atualmente o botão de nome Acessar inscrição está sendo apresentado ao usuário mesmo antes dele ter efetuado alguma inscrição, e a nomenclatura dá a entender que o usuário irá acessar uma inscrição. Portanto quando visualizar uma oportunidade a qual ainda não se inscreveu ele deverá visualizar o botão com o nome Mais informações (o mesmo continuará direcionando para a tela principal da oportunidade). Após o usuário realizar sua inscrição é que o botão deverá aparecer com o nome de Acessar inscrição.

### Escopo UX
 - [x] Verificação para apresentação do botão Acessar inscrição

### Escopo DEV
 - Apresentar ao usuário botão de nome Mais informações, quando este não tiver realizado nenhuma inscrição na oportunidade
 - Apresentar o botão com nome Acessar inscrição, quando o usuário já tiver realizado inscrição na oportunidade.
 - Verificar protótipo apresentado pelo DesignLab.
 
### Critérios de Aceitação
- [x] **Apresentar ao usuário botão de nome Mais informações**
**Dado** que o usuário 
**Quando** não tenha realizada nenhuma inscrição
**Então** ele irá visualizar o botão mais informações, para acessar a página principal da oportunidade.

- [x] **Apresentar ao usuário botão de nome Acessar Inscrição**
**Dado** que o usuário 
**Quando** já tenha realizada inscrição
**Então** ele irá visualizar o botão Acessar Inscrição, para acessar a página principal da oportunidade.

### Observações
Protótipo atualizado: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/?node-id=2801%3A3253

**Comment by RaniGub** [comment]
Sugestão de experiência adicionado com fluxo de condição.

**Comment by luannaalves** [comment]
Será atendido pela issue #647

**Comment by luannaalves** [comment]
Implementado por meio da issue #647.
