### ISSUE TITLE
Implementar migração do CPF atributo do Username no ID Saúde

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#658]
## **Objetivo**

**Como** usuário do ID Saúde  
**Quero** acessar o ID Saúde com autenticação realizada pelo CPF ou e-mail
**Para** acessar os recursos internos da minha conta no mapa da saúde

## **Contexto**

Atualmente o ID Saúde a forma de autenticação está sendo feita apenas pelo e-mail, não havendo campo para preenchimento do CPF. Este é inserido nos campos de atributos do usuário dentro do Mapa da saúde, o que permite o mesmo internamente ser inserido ou não, ser duplicado ou inexistente. Para resolver o problema é necessário garantir consistência do usuário internamente, utilizando o CPF ao realizar cadastro e login.

## **Escopo**

- [ ] Migrar CPF atributos do usuário para USERNAME

## **Critérios de Aceitação**

- [ ] Migrar CPF atributos do usuário para USERNAME  
**Dado que** acesso todos os usuários  cadastrados no IDSaúde
**Quando** acesso cada atributo CPF do usuário  
**então** realizo a atualização do registro cpf -> username (único)

# Observações

Issue similar à implementada para o ISUS, verificar em: 
https://github.com/EscolaDeSaudePublica/idsaude-api/issues/4

**Comment by luannaalves** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Dev-60f894f541f910001066bfd9/issues/EscolaDeSaudePublica/mapadasaude/658?planning-poker) with ZenHub @Junior-Shyko @pedrovitor074 @victorMagalhaesPacheco

**Comment by vicmagpac** [comment]
Em alinhamento com o time de desenvolvimento @Junior-Shyko e @luannaalves verificou-se a necessidade de realizar a migração dos usuário que tem cadastro com CPF atributo. (iSUS)

**Comment by luannaalves** [comment]
Issue migrada para board ID Saúde.
