### ISSUE TITLE
Desabilitar acesso ao ID Saúde pelo Facebook - Produção

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#662]
## **Objetivo**

**Como** gestor do ID Saúde  
**Quero** corrigir bug na produção
**Para** que os usuários possam acessar o ID Saúde por meio do Facebook

## **Contexto**
Atualmente está ocorrendo um bug na produção, onde o usuário não está conseguindo acessar o Id Saúde por meio do Facebook, o qual deverá ser corrigido.

## **Escopo**
- Corrigir bug na produção para acesso ao ID Saúde por meio do facebook

## **Critérios de Aceitação**
- [x] Desabilitar a opção de login por meio do facebook
**Dado** que o usuário
**Quando**  acesse o ID Saúde
**então** não apareça a opção de login pelo facebook

# Observações
Será necessário desativar o acesso pelo ID Saúde por meio do Facebook, devido o Facebook solicitar que seja apresentada uma política de privacidade por parte do ID Saúde aos usuários, a qual hoje não contempla.

**Comment by luannaalves** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Dev-60f894f541f910001066bfd9/issues/EscolaDeSaudePublica/mapadasaude/662?planning-poker) with ZenHub @Junior-Shyko @pedrovitor074 @victorMagalhaesPacheco

**Comment by pedrovitor074** [comment]
Após uma conversa com  o @victorMagalhaesPacheco , visto que não temos politica de privacidade, o facebook removeu o nosso aplicativo, e não temos maiis a opção de recorrer, então a solução por hora foi remover o login com facebook.
![image.png](https://images.zenhubusercontent.com/615edf64b26e72ab14315242/d5b1ec4a-aec2-422f-b403-6d2287cd7f9a)

![image.png](https://images.zenhubusercontent.com/615edf64b26e72ab14315242/08ed3450-5ada-45c9-b0fa-a8a95442969b)

**Comment by luannaalves** [comment]
Validado na produção.

**Comment by daianeabreu** [comment]
Olá! @victorMagalhaesPacheco  segue a versão anterior que temos do Termo de Uso do ID Saúde
https://docs.google.com/document/d/1ifYPIuUqROMQyMgwUEUaQHu-5-mgLUdEvYjg7Tg_GfM/edit#heading=h.xd1gqyruw92b
