### ISSUE TITLE
Possibilitar que a usuária entre em contato, através da página da oportunidade, para esclarecer dúvidas com o gestor da oportunidade

### ISSUE THREAD

**Issue by pauloamoreira** [FeliciLab/mapadasaude#674]
## **Objetivo**

**Como** gestor  
**Quero** criar um ambiente de contato da oportunidade  
**Para** que a usuária possa tirar dúvidas na página de informações da oportunidade 

## **Contexto**
- Como complemento a tarefa #651 , é necessário tornar possível que a pessoa usuária possa enviar uma mensagem ao gestor da Oportunidade, através da página da oportunidade para esclarecer uma dúvida.

## **Escopo UX**
- [x] Pensar na melhor maneira de incluir a opção de ‘contato’ na página de informações da oportunidade 
- [x] Desenvolver tela da solução 

## **Escopo DEV**
- [ ] escopo 1

# Observações
Protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=2856%3A3286

**Comment by pauloamoreira** [comment]
.protótipo finalizado.

**Comment by RaniGub** [comment]
Tarefa finalizada, qualquer dúvida falar comigo.

**Comment by luannaalves** [comment]
Será atendida pela issue #651
