### ISSUE TITLE
Atualização nova versão Mapa da saúde

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#685]
## **Objetivo**

**Como** desenvolvedor do mapa da saúde  
**Quero** fazer a atualização da nova versão do Mapa da saúde
**Para** melhorar a experiência do usuário e da plataforma.

## **Contexto**
Será necessário realizar a atualização para nova versão do mapa na homologação e posteriormente realizar verificação da versão para identificar se houve perdas ou quebras de funcionalidades.

## **Escopo**

- Realizar atualização para nova versão do mapa na homologação.
- Realizar verificação na nova versão.

## **Critérios de Aceitação**

- [ ] Realizar atualização para nova versão do mapa na homologação. 
- [ ] Realizar verificação na nova versão.

## Observações

Relatar os problemas encontrados após verificação.

## Ajustes realizados nos testes

- [x] Atualização pra versão mais recentes dos submódulos (resolver os conflitos) 
- [x] Ocultar o home opportunities da home
- [x] limite de inscrições por projeto não aparecem mais
- [x] Ajustar css dos recursos na oportunidade (create)
- [x] Relatório premilinar e relatório definivo não estão gerando (motivo tipo do parâmetro passado, espera um objeto do tipo Registration entretanto é passado o objeto array - linha 102 do arquivo technical-category)
- [x] Datas na oportunidade não estão seguindo o css da versão de produção exemplo:
Produção:
![image](https://user-images.githubusercontent.com/3487411/157102110-9707d96d-56f6-4bf7-a434-3677da0db519.png)
Novo ambiente:
![image](https://user-images.githubusercontent.com/3487411/157102191-ba925e86-657e-4541-89d5-447d69403d54.png)
- [x] Refatorar categorias vinculadas as sections com apenas 1 categoria (Alterar em todo o fluxo e sections com categorias e verificar os calculos)(464d7b76883b1f3f1362e3d66edc82234e5afdb4) 
- [x] trocar o nome do hook para seal ( atualmente está selo); 2576ff8910222c9f35ca28263ae55284bf28cb36 @victorMagalhaesPacheco 
- [x] Adicionar stream options send mail e924824ecad8ce2b06f8bfe0c2fd98f0b7be2a0b @victorMagalhaesPacheco 
- [x] Adicionar botão para imprimir as inscrições dd6fe8bda9625880293759f00d4d440ae6c55288 @pedrovitor074 
- [x] Correção de remoção de múltiplos arquivos, e refazer na nova versão
840c02b74b3a694cbf04813ad5b9d6b1f24bd644
- [x] Atualizar css da lista de oportunidades na página de projetos
- [x] Atualizar OpauthKeycloak para atender a versão que está executando em produção (redirecionar pra ultima página de acesso antes de autenticar)

**Comment by luannaalves** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mapa-da-Sade---Dev-60f894f541f910001066bfd9/issues/EscolaDeSaudePublica/mapadasaude/685?planning-poker) with ZenHub @pedrovitor074 @victorMagalhaesPacheco

**Comment by vicmagpac** [comment]
Realizamos a instalação da nova versão do mapas v5.1.26 no ambiente de teste https://mapadasaude51.dev.org.br

**Comment by vicmagpac** [comment]
Arquitetura atual no ambiente novo de homologação:  ![Atual.png](https://images.zenhubusercontent.com/60a700715abeb69728eb42ba/d8992543-a078-4454-a497-64bf2286b26c)
