### ISSUE TITLE
Definir a forma correta de se referenciar a plataforma

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/mapadasaude#701]
## **Objetivo**
**Como** gestor  
**Quero** definir a forma correta de se referenciar a plataforma
**Para** que haja uma conexão semântica e relação de pertencimento com os trabalhadores da saúde.

## **Contexto**
- Em 'Sobre o Mapa da Saúde' e em 'Como usar', o nome da plataforma está no plural (Mapas da Saúde). Na url e assinatura está escrito no singular. É preciso definir a forma correta de se referenciar à plataforma.

## **Escopo UX**
-  SEM NECESSIDADE DE UX 

## **Escopo DEV**
- [ ] escopo

## **Critérios de Aceitação**
- [] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

# Observações
![image](https://user-images.githubusercontent.com/67759144/158340447-cd3a0e51-a3b2-4793-b5dc-8589bcaf5cd0.png)

**Comment by luannaalves** [comment]
Será atendida pela issue #670
