### ISSUE TITLE
Realização de Testes e Correções na nova versão mapa da saúde

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#703]
### Objetivo
**Como** gestor do Mapa
**Quero** que seja realizada uma bateria de testes na nova versão do Mapa da saúde em homologação
**Para** sanar quaisquer bugs/perdas que tenham ocorrido.

### Contexto
Com a implementação de nova versão do Mapa da saúde em homologação, ambiente https://novomapadasaude.dev.org.br, será necessário realizar uma força tarefa para realização dos testes na plataforma, testes esse que envolvam todas as funcionalidades dentro do Mapa da saúde.

### Escopo
Realizar testes nos seguintes ambientes:
**(Inserir nome da pessoa que irá trabalhar ao lado do tópico)**

- [x] Home do Mapa - Pedro
- [x] Entidade Agentes  - Pedro
- [x] Entidade Espaços - Luanna
- [x] Painel de Controle (Menus suspenso, lateral e de entrada) - Pedro
- [x] Entidade Inscrições: - Luanna
           Criação de Projeto
           Criação de Oportunidades
- [x] Entidade Inscrições: - Luanna, Victor
            Inscrição em uma oportunidade em diversas fases
            Recursos
- [x] Entidade Inscrições: 
            Avaliações
            Resultados

### Critérios de Aceitação

- [x] Teste realizados na Home do Mapa
- [x] Teste realizados na Entidade Agentes 
- [x] Teste realizados na Entidade Espaços
- [x] Teste realizados na Painel de Controle (Menus suspenso, lateral e de entrada)
- [x] Teste realizados na Entidade Inscrições: 
         
### Observações
Pontuar observações de bug/correções no seguinte documento: 
https://docs.google.com/document/d/1e2VSZQh4kQoEyfHmE-A_aO252cA_s68394Fd5egqjI0/edit

 - [x] Remoção da aba de agentes ( Print abaixo );
 - [x]  Aba Agenda nos agentes:
 - [x] Remover aba de denuncia e contato;
 - [x] Adicionar botão para criar oportunidades na tela dos agentes;
 - [x] Bug na hora de imprimir certificado de agente;
 - [x] Bug na exibição das oportunidades;
 - [x] VISUALIZAÇÃO DOS ESPAÇOS - MODO LISTA
 - [x] EXPORTAR DADOS DOS ESPAÇOS
 - [x] NÃO ESTÁ SALVANDO O TIPO DE ESPAÇO
 - [x] REMOVER A ABA AGENDA DE MEUS PROJETOS
 - [x] Atualização dos nomes das opções no menu lateral e remover algumas opções como indicadores e meus apps.
 - [x] DEVERIA SER INFORMADO QUE É NECESSÁRIO INSERIR O HTTPS.:// NO CAMPO DE URL, POIS SERÁ MUITO DIFÍCIL O USUÁRIO COMUM DESCOBRIR ISSO
 - [x] OPORTUNIDADES CRIADAS SEM ESTAR VINCULADAS A UM PROJETO CONTINUAM NÃO APARECENDO NO MENU DE INSCRIÇÕES
 - [x] NA CRIAÇÃO DE UMA OPORTUNIDADE, SE VOCÊ SELECIONAR O PROJETO E CLICAR EM OUTRO CAMPO DE PREENCHIMENTO, ELE NÃO SALVA O PROJETO. SOMENTE SALVA SE FOR A ÚLTIMA AÇÃO ANTES DE ADICIONAR A OPORTUNIDADE.
 - [x] ESTÁ APRESENTANDO UM BUG NA JANELA QUANDO SE ESTÁ CRIANDO INICIALMENTE A OPORTUNIDADE
 - [x] NÃO ESTÁ APARECENDO A IMAGEM DO SELO. E A CAIXINHA OCULTA DO NOME DO SELO FICA SOBREPONDO O BOTÃO DE EXCLUIR SELO, AI VOCÊ NÃO CONSEGUE CLICAR PRA EXCLUIR.
 - [x] NÃO CONSTA NA NOVA VERSÃO O BOTÃO DE PUBLICAR, APENAS SALVAR. E AO SALVAR JÁ ESTÁ APARECENDO PARA O USUÁRIO.
 - [x] QUANDO IMPORTA UM FORMULÁRIO ELE DIRECIONA PARA PÁGINA PRINCIPAL, DEVERIA PERMANECER NA MESMA PÁGINA.
 - [x] REMOVER CAMPO DE EXEQUIBILIDADE DA INSCRIÇÃO. JÁ HAVIA SIDO REMOVIDO NA VERSÃO ANTERIOR
 - [x] FOI PERDIDA A FUNCIONALIDADE DE ANEXAR MÚLTIPLOS ARQUIVOS AO ADICIONAR O CAMPO ANEXO
 - [x] NA INSCRIÇÃO MESMO NO MOMENTO DO ENVIO DE INSCRIÇÃO O SISTEMA MOSTRA UMA MENSAGEM DE SUCESSO DEPOIS UMA MENSAGEM DE ERRO, EM SEGUIDA REDIRECIONA PARA A PÁGINA DO INSCRITO

**Comment by pedrovitor074** [comment]
## Duvidas
1 - Remoção da aba de agentes ( Print abaixo );
![image](https://user-images.githubusercontent.com/38664500/158416212-4c49f4ce-3e33-4b1a-a30e-8186d6fec9d4.png)
2 - Aba Agenda nos agentes:
![image](https://user-images.githubusercontent.com/38664500/158416449-70b6ad58-5cf8-4514-96ad-cd116ba6c35f.png)
3 - Manter botao de denunciar e contato que há na nova versão ?
![image](https://user-images.githubusercontent.com/38664500/158416590-902d7ba8-29fc-4901-a0ac-d3bc4dee8586.png)
4 - Bug na hora de imprimir o certificado de um agente:
![image](https://user-images.githubusercontent.com/38664500/158416758-0f16eca8-b862-469d-be27-fd80fcacad61.png)
5  -  Atualização dos nomes das opções no menu  lateral e remover algumas opções como indicadores e meus apps
![image](https://user-images.githubusercontent.com/38664500/158417018-e5237ad9-040e-4114-a209-4dcacf87f176.png)

**Comment by vicmagpac** [comment]
Atualização do core para a versão https://github.com/mapasculturais/mapasculturais/releases/tag/v5.2.2

**Comment by vicmagpac** [comment]
> Atualização do core para a versão https://github.com/mapasculturais/mapasculturais/releases/tag/v5.2.2

Commit merge: https://github.com/EscolaDeSaudePublica/mapadasaude/commit/3c91b056daa18d507dab3ce954482d2a880d0ca0

**Comment by vicmagpac** [comment]
Envio de email no novo ambiente atualizado com sucesso.
Exemplo: 
![Captura de tela de 2022-04-22 12-20-55.png](https://images.zenhubusercontent.com/60a700715abeb69728eb42ba/079b157c-74f3-47bc-9229-1d4411fa52ac)

**Comment by vicmagpac** [comment]
Iniciando testes com public-files da produção local.

**Comment by vicmagpac** [comment]
Na nova versão do mapas com nova funcionalidade seguindo os padrões do LGPD foi implementado um novo módulo de consentimento de aceite de termos de uso e aceite de política de privacidade. 

Termos de uso:
![image](https://user-images.githubusercontent.com/3487411/165542891-7cca103d-7be9-4ff9-b40f-e1535ec4abee.png)

Política de privacidade:
![image](https://user-images.githubusercontent.com/3487411/165543140-44ed0c34-c042-4c16-b72f-6b0430e58006.png)

Versão 5.2.2

**Comment by vicmagpac** [comment]
Retornamos o pareamento com o Rafa do hacklab.

Encaminhamentos:

- Adicionar core via submodule no baseproject
- Aguardar o merge para o SealRelation referente aos modificadores de acesso na Entity SealRelation 'isExpired' -> protected para public

Novas funcionalidades ara a versão 5.3.0

- Termos de uso e política de privacidade ao se autenticar na ferramenta baseado na LGPD
- Mudança na estrutura dos dados do agente (dados pessoas privados)

**Comment by vicmagpac** [comment]
Ambiente atualizado para a versão mais recente do mapas culturais: mapa version https://github.com/mapasculturais/mapasculturais/releases/tag/v5.2.7

**Comment by vicmagpac** [comment]
No teste realizado foi verificado que o SealCertifield não está funcionando na nova versão:

- Mudanças de hooks

**Comment by vicmagpac** [comment]
No teste realizado foi verificado que o SealCertifield não está funcionando na nova versão:

- Mudanças de hooks

**Comment by vicmagpac** [comment]
> No teste realizado foi verificado que o SealCertifield não está funcionando na nova versão:
> 
> * Mudanças de hooks

Em alinhamento com o Rafa do hacklab, foi informado que esse problema foi resolvido na versão 5.3.0 no seguinte commit https://github.com/mapasculturais/mapasculturais/commit/f735003c0ae2fd93d24d67132541a805504f5ff7

**Comment by vicmagpac** [comment]
Na nova versão do mapas foi adicionado as politicas afirmativas, ou seja, é possível adicionar notas extras na avaliação técnica para campos especificados na oportunidade. 

Por exemplo: Se na inscrição o participante informar que é servidor público o mesmo pode receber uma nota adicional a mais.

Segue o exemplo das configurações das avaliações:
![Captura de tela de 2022-05-11 11-47-15](https://user-images.githubusercontent.com/3487411/167879104-088857db-0da6-45c6-be37-be598882571b.png)
