### ISSUE TITLE
Ajustar logomarcas na Home do Mapa

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#705]
## **Objetivo**
**Como** gestor do Mapa
**Quando** acesse a Home
**Então** quero visualizar as logomarcas padronizadas e de boa qualidade

## **Contexto**
Atualmente as logomarcas da ESP e do Mapa da Saúde, na Home do Mapa, estão com tamanhos distintos e com má qualidade de resolução, devendo portanto serem ajustadas.

## **Escopo**
- Ajustar logomarcas na Home do Mapa.

## **Critérios de Aceitação**
- [ ] **Ajustar logomarcas na Home do Mapa**
**Dado que** o usuário
**Quando** acesse a Home do Mapa
**Então** visualize as logomarcas padronizadas e com boa resolução.

# Observações

Link das logos em melhor resolução :
Logo da ESP-> https://drive.google.com/file/d/1e_f1-9WPxg1cSfOQvJtUuOYQrbavuv31/view?usp=sharing
Logo do Mapa da saúde-> https://drive.google.com/file/d/1aNs9TIRryOUQsIy4QNnuX7gK7ZoeiRyM/view?usp=sharing
Logo do Mapa da saúde com texto preto -> https://drive.google.com/file/d/1bLFTkwvipWti-SMcxBmCp1BV23ds8qkn/view?usp=sharing

Link das logos em SVG:
[https://app.zenhub.com/files/319384032/d9fddeb7-8a79-43e2-a0d8-70a76d2ce4f8/download](https://app.zenhub.com/files/319384032/d9fddeb7-8a79-43e2-a0d8-70a76d2ce4f8/download)

**Comment by andersondantas81** [comment]
A barra de título tem o fundo branco, com isso a imagem com a letra branca não fica visível. Segue imagem em anexo.


![image](https://user-images.githubusercontent.com/4249888/180453357-e865a95b-8339-46ef-92e9-7925677bb49c.png)

**Comment by JesseOliveiraUFC** [comment]
A logo da ESP (canto direito superior) está fora de alinhamento com os itens da navbar.
