### ISSUE TITLE
Alterar tipo de avaliação na submissão de trabalhos do I Fórum SMAPS

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#711]
### Objetivo
**Como** usuário do Mapa na produção
**Quero** que seja alterado o tipo de avaliação em uma oportunidade em vigor
**Para** corrigir um equívoco.

### Contexto
Foi solicitado por meio da gerência de Sistemas, nas pessoa da Hellen que seja alterado o  tipo de avaliação na submissão de trabalhos do I Fórum SMAPS. Onde atualmente está Avaliação Técnica (não se aplica) 
para Avaliação Técnica.

### Escopo
- Alterar tipo de avaliação em oportunidade

### Critérios de Aceitação

- [ ] Alterar tipo de avaliação em oportunidade
Eu como administrador da oportunidade I Fórum SMAPS
Quando disponibilize a oportunidade no mapa
Então esteja como Avaliação Técnica

**Comment by vicmagpac** [comment]
Iniciando atividade.

**Comment by vicmagpac** [comment]
Atualizado em produção.
@helenhilario e @rmadev-master necessário atualizar da mesma forma como foi atualizado na homologação.
