### ISSUE TITLE
Adicionar repositórios de Plugins no board de gestão e desenvolvimento

### ISSUE THREAD

**Issue by vicmagpac** [FeliciLab/mapadasaude#714]
## **Objetivo**

**Como** pessoa analista de negócio (B.A)  
**Quero** criar issues vinculadas ao repositório responsável 
**Para** verificar o histórico dos commits vinculados as issues do repositório responsável 

## **Contexto**

- Atualmente os repositórios de plugins não estão vinculados aos boards

## **Escopo**

- [x] Adicionar repositório de plugins no board de gestão
- [x] Adicionar repositório de plugins no board de desenvolvimento

## **Fora de Escopo**

- Não se aplica

## **Critérios de Aceitação**

- [ ] Adicionar repositório de plugins no board de gestão e desenvolvimento  
**Dado que** acesso o board de gestão ou desenvolvimento  
**Quando** criar uma novo issue  
**então** posso vincular a issue ao repositório responsável pela atividade

**Comment by victorMagalhaesPacheco** [comment]
Foram adicionar 5 novos repositórios:

- plugin-sealCertified
- plugin-EvaluationMethodHomolog
- plugin-PDFReport
- plugin-EvaluationMethodTechnicalNa
- plugin-EditRegistration

**Comment by vicmagpac** [comment]
_*Correção_
Foram adicionados 5 novos repositórios:

- plugin-sealCertified
- plugin-EvaluationMethodHomolog
- plugin-PDFReport
- plugin-EvaluationMethodTechnicalNa
- plugin-EditRegistration
