### ISSUE TITLE
Criar documento para especificar e detalhar as principais funcionalidades da nova versão

### ISSUE THREAD

**Issue by vicmagpac** [FeliciLab/mapadasaude#716]
## **Objetivo**

**Como** pessoa B.A
**Quero** criar um documento especificando as principais funcionalidades de mudanças da versão antiga para a nova 5.0.0 ->5.3.1
**Para** passar o documento para a gerência do projeto mapa

## **Contexto**

- Foi solicitado a especificação das principais mudanças da nova versão do mapa. Deve ser implementado um documento contendo o detalhamento do escopo de cada funcionalidade.

## **Escopo**

- [ ] Criar documento de especificação mudanças de versões

## **Fora de Escopo**

- não se aplica

# Observações

Não se aplica

**Comment by victorMagalhaesPacheco** [comment]
@thaistoscano segue o documento com as especificação das principais mudanças: https://docs.google.com/document/d/1q89AWwWtfhLRSEcsRpzSx0EFNY8ozGG8WibMB9DldYM/edit?usp=sharing

**Comment by vicmagpac** [comment]
@thaistoscano segue o documento com a especificação das principais mudanças: https://docs.google.com/document/d/1q89AWwWtfhLRSEcsRpzSx0EFNY8ozGG8WibMB9DldYM/edit?usp=sharing
