### ISSUE TITLE
Implementar botão da funcionalidade de exportação no Mapa

### ISSUE THREAD

**Issue by nestorufpe** [FeliciLab/mapadasaude#721]
## **Contexto**

Precisa ser implementado um botão no MAPA para que o gestor de curso possa exportar os alunos inscritos selecionados em oportunidades no MAPA para cadastro de pessoa física no SAGU. O botão será focado na versão desktop do MAPA.

## **Escopo Design/UX**

- [x] Proposta do botão: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=3646%3A3658

## **Fora de Escopo**

- [ ] 

## **Critérios de Aceitação**

- [x] Implementar botão de exportação no MAPA
**Dado que**  o usuário entre no MAPA
**Quando** acessar a tela dos inscritos em uma oportunidade
**então** aparecerá um botão para exportação de dados do MAPA e o cadastro automático de pessoa física no SAGU

## Observações
Links de apoio e informações adicionais

**Comment by ricardopoppi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/mapadasaude/721?planning-poker) with ZenHub @victorMagalhaesPacheco @andersondantas81 @jeff-doliveira1

**Comment by caldy94** [comment]
Atualização, a tabela está inexistente na versão mobile, isso terá que ser ajeitado pelos devs, como mostra no link https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=3646%3A3658

**Comment by caldy94** [comment]
Sugestão de tabela para mobile sugerida no link: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=3646%3A3658
