### ISSUE TITLE
Permitir excluir conta quando os dados do CPF estão duplicados

### ISSUE THREAD

**Issue by nestorufpe** [FeliciLab/mapadasaude#732]
## **Contexto**

-Quando a pessoa tem dois cadastros no Mapa vinculados ao mesmo CPF,  ela não  consegue se inscrever em um curso. O problema aparece na hora de excluir um dos cadastros, vinculando as informações ao outro cadastro, para utilizar apenas um (link 1). Mas, ao tentar excluir, o sistema dá erro (links 2 e 3), faz logout e entra na página inicial do Mapa, sem excluir a conta, e o problema permanece. A pessoa continua com as duas contas, sem conseguir se inscrever na oportunidade.

## **Critérios de Aceitação**

- [x] Excluir conta e vincular as informações a outro cadastro quando os dados de CPF estão duplicados no mapa
**Dado que** o aluno
**Quando** verificar que seu CPF está duplicado no mapa no momento de uma inscrição
**então** consiga excluir uma de suas contas e vincular as informações a outro cadastro

## Observações
Link 1-> https://drive.google.com/file/d/1fhzSHMIiWiFuoASJLkXPEJBUW6MbowWt/view?usp=sharing
Link 2-> https://drive.google.com/file/d/1gHoejiKGI4rRYuas_Jj6cQghuC9kdvUE/view?usp=sharing
Link 3-> https://drive.google.com/file/d/17d-15pHErTXqDIt2Pr9TWwfVY2PTMtyH/view?usp=sharing

**Comment by jeff-doliveira1** [comment]
### SQL usado para remover os CPF duplicados
```
UPDATE agent_meta
SET value = null
FROM (
	SELECT value, COUNT(value)
	FROM agent_meta
	WHERE key = 'documento' AND value IS NOT NULL
	GROUP BY value
	HAVING COUNT(value) > 1
) AS duplicateCPF
WHERE agent_meta.value = duplicateCPF.value
```
