### ISSUE TITLE
Solucionar bug dos relatórios no mapa da saúde [gráficos]

### ISSUE THREAD

**Issue by nestorufpe** [FeliciLab/mapadasaude#733]
## **Contexto**

- Quando o usuário tenta realizar a ação de exportar gráfico dos inscritos em uma oportunidade do Mapa da saúde está dando o problema de não conseguir gerar os gráficos.  

## **Critérios de Aceitação**

- [x] Correção do bug de geração de gráficos

## Observações
Links de apoio e informações adicionais
https://drive.google.com/file/d/1SDOFcJN_2WI8mXxtRSjKiUCO_7M8y5L8/view?usp=sharing
https://drive.google.com/file/d/1o1Hik94UO7o-kpgJWxh5HHmbiY1irBL8/view?usp=sharing

**Comment by nestorufpe** [comment]
Foi realizado o pull-request com as correções para o Mapas Culturais. Essa correção depende da alteração no código core deles.

**Comment by vicmagpac** [comment]
@nestorufpe PR aceito pelo hacklab no core e atualizado no ambiente de homologação.
