### ISSUE TITLE
Corrigir bug de gerar PDF com o detalhamento da inscrição 

### ISSUE THREAD

**Issue by nestorufpe** [FeliciLab/mapadasaude#734]
## **Contexto**

-Quando uma pessoa se inscreve em uma oportunidade e acessa os dados de inscrição tem a opção de gerar um PDF com o detalhamento da inscrição. No momento de gerar esse PDF está com problemas para exibir a data de nascimento e o RG do inscrito. 

## **Critérios de Aceitação**

- [x] Corrigir bug de gerar PDF com o detalhamento da inscrição  
**Dado que** inscrito em um oportunidade no mapa
**Quando**  selecionar a opção de gerar PDF com o detalhamento da inscrição
**então** gere um PDF com todas informações necessárias, incluindo RG e data de nascimento 

## Observações
Links de apoio e informações adicionais

**Comment by vicmagpac** [comment]
Task atualizada no ambiente de homologação.
