### ISSUE TITLE
painel do candidato: exibir as oportunidades das quais está participando

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#82]
![Captura de tela de 2020-12-15 13-07-06](https://user-images.githubusercontent.com/57232674/102240420-96459c80-3ed6-11eb-92fa-604a1dea6067.png)
![Captura de tela de 2020-12-15 13-07-48](https://user-images.githubusercontent.com/57232674/102240437-9e054100-3ed6-11eb-968e-aa23a4f284f0.png)

**Comment by Junior-Shyko** [comment]
Aparentemente está tudo normal.
![Captura de tela de 2021-01-27 16-00-39](https://user-images.githubusercontent.com/7341117/106040193-dcd30d00-60b8-11eb-8963-f7baf37a27c6.png)
