### ISSUE TITLE
Perfil do agente na oportunidade

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#84]
### Objetivo
**Como** agente participante
**Quando** for avaliador ou administrador de uma oportunidade
**Então** não poderá se inscrever como participante

### Escopo
Um agente participante de uma oportunidade não poderá, ao mesmo tempo, ser administrador ou avaliador de uma oportunidade estando na condição de candidato.

Caso seja candidato na oportunidade, seu acesso como administrador ou avaliador deverá ser impedido.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x] O candidato não poderá se inscrever em oportunidades das quais foi selecionado como administrador ou avaliador
- [x] O candidato, depois de inscrito em uma oportunidade, não poderá ser adicionado como avaliador da mesma.

**Comment by Junior-Shyko** [comment]
![Captura de tela de 2021-02-04 17-11-05](https://user-images.githubusercontent.com/7341117/106949704-11c00f00-670c-11eb-900a-d234623fb444.png)

**Comment by Junior-Shyko** [comment]
Tarefa realidade e está em homologação.

![photo_2021-02-05_18-05-29](https://user-images.githubusercontent.com/7341117/107089112-d6d9dc00-67dc-11eb-859f-25533a9fe10b.jpg)

**Comment by Junior-Shyko** [comment]
Tarefa realizada, mas está tendo um conflito com o plugin [LocationStateCity](https://github.com/EscolaDeSaudePublica/pluginsDoMapa/tree/main/LocationStateCity) , então estou revendo o plugin para correção.
