### ISSUE TITLE
relação de inscritos: resolver problema de paginação

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#86]
Só mostra 50 inscritos por página, mas a paginação é através da rolagem.

**Comment by Junior-Shyko** [comment]
Na verdade não tem problema, esse é realmente o funcionamento da paginação em todos os mapas culturais que usam o padrão.
Porém, precisamos desenvolver uma paginação apropriada para nossa necessidade.
