### ISSUE TITLE
Criando oportunidades

### ISSUE THREAD

**Issue by Junior-Shyko** [FeliciLab/mapadasaude#9]
**Criar oportunidades com vários senários como:**

- [ ] 2 etapas com avaliação técnica com peso de notas

- [ ] 1 etapa com avaliação técnica com peso de notas

- [ ] Oportunidade com 02 vagas para saber como é o critério de desempates

- [ ] Oportunidade com avaliação documental

- [ ] Oportunidade com duas etapas acontecendo ao mesmo tempo, mas as duas darão um resultado final.

- [ ] Limite de vagas de cadastro

- [ ] Oportunidade com duas fase, uma simples e uma documental

**Comment by thaistoscano** [comment]
Refere-se ao treinamento realizado pelo @Junior-Shyko . Não será tramitado pelo board do Zenhub.
