### ISSUE TITLE
Resultados: não há resultado preliminar

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#92]
### Objetivo
**Como** administrador de oportunidade
**Quando** se precisa de um resultado preliminar de uma das fases de uma oportunidade, onde fases posteriores serão acionadas mediante prévio resultado
**Então** o sistema deverá emitir um relatório preliminar de classificação e um definitivo por fase

### Escopo
Comumente, acontece em processos seletivos, quando existem fases que são necessárias de aprovação e classificação com ou sem limitação de vagas.

Quando uma determinada fase da oportunidade é expirada, uma lista de participantes aprovados naquele momento deve ser expedida pelo sistema. Esse relatório, se dá devido às leis de transparência e faz-se necessária a exibição dos resultados de forma clara para todos os participantes no processo.

Portanto, uma solução de relatórios preliminares e definitivos deve ser criada para expedição e exibição desses resultados.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [x] Adicionar na área do candidato a nota preliminar
- [x] Rotina padronizada de emissão de resultados preliminares
- [x] Rotina padronizada de emissão de resultados definitivos
- [x] Opção de download/impressão de relatórios expedidos em PDF implantada (condicionado a outra issue)

**Comment by Junior-Shyko** [comment]
Em análise feita junto com o @victorMagalhaesPacheco e @rmadev-master percebemos que precisa de um planejamento maior, pois precisamos das notas do recurso para ser dado a nota preliminar, então decidimos criar como teste uma oportunidade com recurso como fase para colocar em produção enquanto analisamos o que poderá ser alterado no banco para mostrar o resultado preliminar do candidato.

**Comment by vicmagpac** [comment]
Relacionamentos oportunidades e registration (inscrição)
![registration (inscricao)](https://user-images.githubusercontent.com/3487411/107521821-c38a9000-6b91-11eb-95f3-a803e695ed3a.png)
![oportunidade-relacionamento](https://user-images.githubusercontent.com/3487411/107521824-c4bbbd00-6b91-11eb-9c78-3ec38dda5fe0.png)

**Comment by vicmagpac** [comment]
Em produção sem o ultimo critério pois é necessário o relatório.
