### ISSUE TITLE
Verificar erro pós login

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#97]
Considerar uma forma amigável de mostrar ao usuário os erros.

![Captura de tela de 2020-12-18 14-50-18](https://user-images.githubusercontent.com/57232674/102644951-74e7e900-4140-11eb-9d28-23447f317ace.png)

**Comment by Junior-Shyko** [comment]
Em produção do debuguer é desligado, mas no homolog vai persistir para perceber que foi o erro.

**Comment by Junior-Shyko** [comment]
Eu forcei um erro no mapa em produção e constatei que o debuguer está false, porém percebi que poderíamos criar uma **página de erro personalizada**.

_Atualmente está assim:_
![Captura de tela de 2021-01-13 09-15-55](https://user-images.githubusercontent.com/7341117/104451305-1ae01500-5580-11eb-8a88-b9dd43143833.png)

**Comment by rafaelmassuncao** [comment]
> Eu forcei um erro no mapa em produção e constatei que o debuguer está false, porém percebi que poderíamos criar uma **página de erro personalizada**.
> 
> _Atualmente está assim:_
> ![Captura de tela de 2021-01-13 09-15-55](https://user-images.githubusercontent.com/7341117/104451305-1ae01500-5580-11eb-8a88-b9dd43143833.png)

Pode colocar os símbolos do mapas, governo e esp-ce.

**Comment by Junior-Shyko** [comment]
Link relacionado: https://github.com/EscolaDeSaudePublica/mapadasaude/issues/129
